// Code generated by kds. DO NOT EDIT.
// source: kds/example.kds

using System;
using System.Collections.Generic;

namespace Kds
{
	public class All : Kdsync.IMessage
	{
		private readonly long _id;
		public long Id => _id;

		public All(long id)
		{
			_id = id;
			types_ = new AllType();
			lists_ = new AllList();
			maps_ = new AllMap();
		}

		private AllType types_;
		public AllType Types => types_;

		private AllList lists_;
		public AllList Lists => lists_;

		private AllMap maps_;
		public AllMap Maps => maps_;

		private long _changed;

		public event Action<All, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Types => (_changed & (0x01 << 1)) != 0;
			public bool Lists => (_changed & (0x01 << 2)) != 0;
			public bool Maps => (_changed & (0x01 << 3)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void MergeFrom(ref Kdsync.ParseContext ctx)
		{
			uint tag;
			while ((tag = ctx.ReadTag()) != 0)
			{
				var num = Kdsync.WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
					case 1:
						ctx.ReadMessage(types_);
						_changed |= 0x01 << 1;
						break;
					case 2:
						ctx.ReadMessage(lists_);
						_changed |= 0x01 << 2;
						break;
					case 3:
						ctx.ReadMessage(maps_);
						_changed |= 0x01 << 3;
						break;
					default:
						ctx.SkipLastField();
						break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				types_.RaiseChanged();
			if ((_changed & (0x01 << 2)) != 0)
				lists_.RaiseChanged();
			if ((_changed & (0x01 << 3)) != 0)
				maps_.RaiseChanged();
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				types_.ClearChanged();
			if ((_changed & (0x01 << 2)) != 0)
				lists_.ClearChanged();
			if ((_changed & (0x01 << 3)) != 0)
				maps_.ClearChanged();
			_changed = 0;
		}

		public void Write(Kdsync.JsonWriter writer)
		{
			writer.WriteStartObject();
			writer.WriteMessage("Types", types_);
			writer.WriteMessage("Lists", lists_);
			writer.WriteMessage("Maps", maps_);
			writer.WriteEndObject();
		}

		public override string ToString()
		{
			Kdsync.JsonWriter writer = new Kdsync.JsonWriter();
			writer.WriteMessageValue(this);
			return writer.ToString();
		}

		public void MergeFrom(byte[] buffer)
		{
			ReadOnlySpan<byte> readOnlySpan = new ReadOnlySpan<byte>(buffer);
			Kdsync.ParseContext.Initialize(readOnlySpan, out var ctx);
			MergeFrom(ref ctx);
		}
	}

	public class AllType : Kdsync.IMessage
	{
		public AllType()
		{
			stringVal_ = string.Empty;
			bytesVal_ = new byte[0];
			itemData_ = new ItemData();
		}

		private int int32Val_;
		public int Int32Val => int32Val_;

		private long int64Val_;
		public long Int64Val => int64Val_;

		private uint uint32Val_;
		public uint Uint32Val => uint32Val_;

		private ulong uint64Val_;
		public ulong Uint64Val => uint64Val_;

		private int sint32Val_;
		public int Sint32Val => sint32Val_;

		private long sint64Val_;
		public long Sint64Val => sint64Val_;

		private uint fixed32Val_;
		public uint Fixed32Val => fixed32Val_;

		private ulong fixed64Val_;
		public ulong Fixed64Val => fixed64Val_;

		private int sfixed32Val_;
		public int Sfixed32Val => sfixed32Val_;

		private long sfixed64Val_;
		public long Sfixed64Val => sfixed64Val_;

		private float floatVal_;
		public float FloatVal => floatVal_;

		private double doubleVal_;
		public double DoubleVal => doubleVal_;

		private bool boolVal_;
		public bool BoolVal => boolVal_;

		private string stringVal_;
		public string StringVal => stringVal_;

		private byte[] bytesVal_;
		public byte[] BytesVal => bytesVal_;

		private Kdsync.Timestamp timestampVal_;
		public Kdsync.Timestamp TimestampVal => timestampVal_;

		private Kdsync.Duration durationVal_;
		public Kdsync.Duration DurationVal => durationVal_;

		private Kdsync.Empty emptyVal_;
		public Kdsync.Empty EmptyVal => emptyVal_;

		private ItemType enumVal_;
		public ItemType EnumVal => enumVal_;

		private ItemData itemData_;
		public ItemData ItemData => itemData_;

		private long _changed;

		public event Action<AllType, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Int32Val => (_changed & (0x01 << 1)) != 0;
			public bool Int64Val => (_changed & (0x01 << 2)) != 0;
			public bool Uint32Val => (_changed & (0x01 << 3)) != 0;
			public bool Uint64Val => (_changed & (0x01 << 4)) != 0;
			public bool Sint32Val => (_changed & (0x01 << 5)) != 0;
			public bool Sint64Val => (_changed & (0x01 << 6)) != 0;
			public bool Fixed32Val => (_changed & (0x01 << 7)) != 0;
			public bool Fixed64Val => (_changed & (0x01 << 8)) != 0;
			public bool Sfixed32Val => (_changed & (0x01 << 9)) != 0;
			public bool Sfixed64Val => (_changed & (0x01 << 10)) != 0;
			public bool FloatVal => (_changed & (0x01 << 11)) != 0;
			public bool DoubleVal => (_changed & (0x01 << 12)) != 0;
			public bool BoolVal => (_changed & (0x01 << 13)) != 0;
			public bool StringVal => (_changed & (0x01 << 14)) != 0;
			public bool BytesVal => (_changed & (0x01 << 15)) != 0;
			public bool TimestampVal => (_changed & (0x01 << 16)) != 0;
			public bool DurationVal => (_changed & (0x01 << 17)) != 0;
			public bool EmptyVal => (_changed & (0x01 << 18)) != 0;
			public bool EnumVal => (_changed & (0x01 << 19)) != 0;
			public bool ItemData => (_changed & (0x01 << 20)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void MergeFrom(ref Kdsync.ParseContext ctx)
		{
			uint tag;
			while ((tag = ctx.ReadTag()) != 0)
			{
				var num = Kdsync.WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
					case 1:
						int32Val_ = ctx.ReadInt32();
						_changed |= 0x01 << 1;
						break;
					case 2:
						int64Val_ = ctx.ReadInt64();
						_changed |= 0x01 << 2;
						break;
					case 3:
						uint32Val_ = ctx.ReadUInt32();
						_changed |= 0x01 << 3;
						break;
					case 4:
						uint64Val_ = ctx.ReadUInt64();
						_changed |= 0x01 << 4;
						break;
					case 5:
						sint32Val_ = ctx.ReadSInt32();
						_changed |= 0x01 << 5;
						break;
					case 6:
						sint64Val_ = ctx.ReadSInt64();
						_changed |= 0x01 << 6;
						break;
					case 7:
						fixed32Val_ = ctx.ReadFixed32();
						_changed |= 0x01 << 7;
						break;
					case 8:
						fixed64Val_ = ctx.ReadFixed64();
						_changed |= 0x01 << 8;
						break;
					case 9:
						sfixed32Val_ = ctx.ReadSFixed32();
						_changed |= 0x01 << 9;
						break;
					case 10:
						sfixed64Val_ = ctx.ReadSFixed64();
						_changed |= 0x01 << 10;
						break;
					case 11:
						floatVal_ = ctx.ReadFloat();
						_changed |= 0x01 << 11;
						break;
					case 12:
						doubleVal_ = ctx.ReadDouble();
						_changed |= 0x01 << 12;
						break;
					case 13:
						boolVal_ = ctx.ReadBool();
						_changed |= 0x01 << 13;
						break;
					case 14:
						stringVal_ = ctx.ReadString();
						_changed |= 0x01 << 14;
						break;
					case 15:
						bytesVal_ = ctx.ReadBytes();
						_changed |= 0x01 << 15;
						break;
					case 16:
						timestampVal_ = ctx.ReadTimestamp();
						_changed |= 0x01 << 16;
						break;
					case 17:
						durationVal_ = ctx.ReadDuration();
						_changed |= 0x01 << 17;
						break;
					case 18:
						emptyVal_ = ctx.ReadEmpty();
						_changed |= 0x01 << 18;
						break;
					case 19:
						enumVal_ = (ItemType)ctx.ReadEnum();
						_changed |= 0x01 << 19;
						break;
					case 20:
						ctx.ReadMessage(itemData_);
						_changed |= 0x01 << 20;
						break;
					default:
						ctx.SkipLastField();
						break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 20)) != 0)
				itemData_.RaiseChanged();
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 20)) != 0)
				itemData_.ClearChanged();
			_changed = 0;
		}

		public void Write(Kdsync.JsonWriter writer)
		{
			writer.WriteStartObject();
			writer.WriteNumber("Int32Val", int32Val_);
			writer.WriteNumber("Int64Val", int64Val_);
			writer.WriteNumber("Uint32Val", uint32Val_);
			writer.WriteNumber("Uint64Val", uint64Val_);
			writer.WriteNumber("Sint32Val", sint32Val_);
			writer.WriteNumber("Sint64Val", sint64Val_);
			writer.WriteNumber("Fixed32Val", fixed32Val_);
			writer.WriteNumber("Fixed64Val", fixed64Val_);
			writer.WriteNumber("Sfixed32Val", sfixed32Val_);
			writer.WriteNumber("Sfixed64Val", sfixed64Val_);
			writer.WriteNumber("FloatVal", floatVal_);
			writer.WriteNumber("DoubleVal", doubleVal_);
			writer.WriteBoolean("BoolVal", boolVal_);
			writer.WriteString("StringVal", stringVal_);
			writer.WriteBase64("BytesVal", bytesVal_);
			writer.WriteTimestamp("TimestampVal", timestampVal_);
			writer.WriteDuration("DurationVal", durationVal_);
			writer.WriteEmpty("EmptyVal", emptyVal_);
			writer.WriteEnum("EnumVal", enumVal_);
			writer.WriteMessage("ItemData", itemData_);
			writer.WriteEndObject();
		}

		public override string ToString()
		{
			Kdsync.JsonWriter writer = new Kdsync.JsonWriter();
			writer.WriteMessageValue(this);
			return writer.ToString();
		}
	}

	public class AllList : Kdsync.IMessage
	{
		public AllList()
		{
			int32List_ = new Kdsync.Repeated<int>();
			uint32List_ = new Kdsync.Repeated<uint>();
			int64List_ = new Kdsync.Repeated<long>();
			uint64List_ = new Kdsync.Repeated<ulong>();
			floatList_ = new Kdsync.Repeated<float>();
			doubleList_ = new Kdsync.Repeated<double>();
			boolList_ = new Kdsync.Repeated<bool>();
			stringList_ = new Kdsync.Repeated<string>();
			timestampList_ = new Kdsync.Repeated<Kdsync.Timestamp>();
			durationList_ = new Kdsync.Repeated<Kdsync.Duration>();
			emptyList_ = new Kdsync.Repeated<Kdsync.Empty>();
			enumList_ = new Kdsync.Repeated<ItemType>();
			itemList_ = new Kdsync.Repeated<ItemData>();
		}

		private static readonly Kdsync.FieldCodec<int> _list_int32List__codec = Kdsync.FieldCodec.ForInt32();
		private Kdsync.Repeated<int> int32List_;
		public Kdsync.Repeated<int> Int32List => int32List_;

		private static readonly Kdsync.FieldCodec<uint> _list_uint32List__codec = Kdsync.FieldCodec.ForUInt32();
		private Kdsync.Repeated<uint> uint32List_;
		public Kdsync.Repeated<uint> Uint32List => uint32List_;

		private static readonly Kdsync.FieldCodec<long> _list_int64List__codec = Kdsync.FieldCodec.ForInt64();
		private Kdsync.Repeated<long> int64List_;
		public Kdsync.Repeated<long> Int64List => int64List_;

		private static readonly Kdsync.FieldCodec<ulong> _list_uint64List__codec = Kdsync.FieldCodec.ForUInt64();
		private Kdsync.Repeated<ulong> uint64List_;
		public Kdsync.Repeated<ulong> Uint64List => uint64List_;

		private static readonly Kdsync.FieldCodec<float> _list_floatList__codec = Kdsync.FieldCodec.ForFloat();
		private Kdsync.Repeated<float> floatList_;
		public Kdsync.Repeated<float> FloatList => floatList_;

		private static readonly Kdsync.FieldCodec<double> _list_doubleList__codec = Kdsync.FieldCodec.ForDouble();
		private Kdsync.Repeated<double> doubleList_;
		public Kdsync.Repeated<double> DoubleList => doubleList_;

		private static readonly Kdsync.FieldCodec<bool> _list_boolList__codec = Kdsync.FieldCodec.ForBool();
		private Kdsync.Repeated<bool> boolList_;
		public Kdsync.Repeated<bool> BoolList => boolList_;

		private static readonly Kdsync.FieldCodec<string> _list_stringList__codec = Kdsync.FieldCodec.ForString();
		private Kdsync.Repeated<string> stringList_;
		public Kdsync.Repeated<string> StringList => stringList_;

		private static readonly Kdsync.FieldCodec<Kdsync.Timestamp> _list_timestampList__codec = Kdsync.FieldCodec.ForTimestamp();
		private Kdsync.Repeated<Kdsync.Timestamp> timestampList_;
		public Kdsync.Repeated<Kdsync.Timestamp> TimestampList => timestampList_;

		private static readonly Kdsync.FieldCodec<Kdsync.Duration> _list_durationList__codec = Kdsync.FieldCodec.ForDuration();
		private Kdsync.Repeated<Kdsync.Duration> durationList_;
		public Kdsync.Repeated<Kdsync.Duration> DurationList => durationList_;

		private static readonly Kdsync.FieldCodec<Kdsync.Empty> _list_emptyList__codec = Kdsync.FieldCodec.ForEmpty();
		private Kdsync.Repeated<Kdsync.Empty> emptyList_;
		public Kdsync.Repeated<Kdsync.Empty> EmptyList => emptyList_;

		private static readonly Kdsync.FieldCodec<ItemType> _list_enumList__codec = Kdsync.FieldCodec.ForEnum(x => (int)x, x => (ItemType)x);
		private Kdsync.Repeated<ItemType> enumList_;
		public Kdsync.Repeated<ItemType> EnumList => enumList_;

		private static readonly Kdsync.FieldCodec<ItemData> _list_itemList__codec = Kdsync.FieldCodec.ForMessage<ItemData>();
		private Kdsync.Repeated<ItemData> itemList_;
		public Kdsync.Repeated<ItemData> ItemList => itemList_;

		private long _changed;

		public event Action<AllList, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Int32List => (_changed & (0x01 << 1)) != 0;
			public bool Uint32List => (_changed & (0x01 << 2)) != 0;
			public bool Int64List => (_changed & (0x01 << 3)) != 0;
			public bool Uint64List => (_changed & (0x01 << 4)) != 0;
			public bool FloatList => (_changed & (0x01 << 5)) != 0;
			public bool DoubleList => (_changed & (0x01 << 6)) != 0;
			public bool BoolList => (_changed & (0x01 << 7)) != 0;
			public bool StringList => (_changed & (0x01 << 8)) != 0;
			public bool TimestampList => (_changed & (0x01 << 9)) != 0;
			public bool DurationList => (_changed & (0x01 << 10)) != 0;
			public bool EmptyList => (_changed & (0x01 << 11)) != 0;
			public bool EnumList => (_changed & (0x01 << 12)) != 0;
			public bool ItemList => (_changed & (0x01 << 13)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void MergeFrom(ref Kdsync.ParseContext ctx)
		{
			uint tag;
			while ((tag = ctx.ReadTag()) != 0)
			{
				var num = Kdsync.WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
					case 1:
						int32List_.MergeFrom(ref ctx, _list_int32List__codec);
						_changed |= 0x01 << 1;
						break;
					case 2:
						uint32List_.MergeFrom(ref ctx, _list_uint32List__codec);
						_changed |= 0x01 << 2;
						break;
					case 3:
						int64List_.MergeFrom(ref ctx, _list_int64List__codec);
						_changed |= 0x01 << 3;
						break;
					case 4:
						uint64List_.MergeFrom(ref ctx, _list_uint64List__codec);
						_changed |= 0x01 << 4;
						break;
					case 5:
						floatList_.MergeFrom(ref ctx, _list_floatList__codec);
						_changed |= 0x01 << 5;
						break;
					case 6:
						doubleList_.MergeFrom(ref ctx, _list_doubleList__codec);
						_changed |= 0x01 << 6;
						break;
					case 7:
						boolList_.MergeFrom(ref ctx, _list_boolList__codec);
						_changed |= 0x01 << 7;
						break;
					case 8:
						stringList_.MergeFrom(ref ctx, _list_stringList__codec);
						_changed |= 0x01 << 8;
						break;
					case 9:
						timestampList_.MergeFrom(ref ctx, _list_timestampList__codec);
						_changed |= 0x01 << 9;
						break;
					case 10:
						durationList_.MergeFrom(ref ctx, _list_durationList__codec);
						_changed |= 0x01 << 10;
						break;
					case 11:
						emptyList_.MergeFrom(ref ctx, _list_emptyList__codec);
						_changed |= 0x01 << 11;
						break;
					case 12:
						enumList_.MergeFrom(ref ctx, _list_enumList__codec);
						_changed |= 0x01 << 12;
						break;
					case 13:
						itemList_.MergeFrom(ref ctx, _list_itemList__codec);
						_changed |= 0x01 << 13;
						break;
					default:
						ctx.SkipLastField();
						break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				int32List_.RaiseChanged();
			if ((_changed & (0x01 << 2)) != 0)
				uint32List_.RaiseChanged();
			if ((_changed & (0x01 << 3)) != 0)
				int64List_.RaiseChanged();
			if ((_changed & (0x01 << 4)) != 0)
				uint64List_.RaiseChanged();
			if ((_changed & (0x01 << 5)) != 0)
				floatList_.RaiseChanged();
			if ((_changed & (0x01 << 6)) != 0)
				doubleList_.RaiseChanged();
			if ((_changed & (0x01 << 7)) != 0)
				boolList_.RaiseChanged();
			if ((_changed & (0x01 << 8)) != 0)
				stringList_.RaiseChanged();
			if ((_changed & (0x01 << 9)) != 0)
				timestampList_.RaiseChanged();
			if ((_changed & (0x01 << 10)) != 0)
				durationList_.RaiseChanged();
			if ((_changed & (0x01 << 11)) != 0)
				emptyList_.RaiseChanged();
			if ((_changed & (0x01 << 12)) != 0)
				enumList_.RaiseChanged();
			if ((_changed & (0x01 << 13)) != 0)
				itemList_.RaiseChanged();
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				int32List_.ClearChanged();
			if ((_changed & (0x01 << 2)) != 0)
				uint32List_.ClearChanged();
			if ((_changed & (0x01 << 3)) != 0)
				int64List_.ClearChanged();
			if ((_changed & (0x01 << 4)) != 0)
				uint64List_.ClearChanged();
			if ((_changed & (0x01 << 5)) != 0)
				floatList_.ClearChanged();
			if ((_changed & (0x01 << 6)) != 0)
				doubleList_.ClearChanged();
			if ((_changed & (0x01 << 7)) != 0)
				boolList_.ClearChanged();
			if ((_changed & (0x01 << 8)) != 0)
				stringList_.ClearChanged();
			if ((_changed & (0x01 << 9)) != 0)
				timestampList_.ClearChanged();
			if ((_changed & (0x01 << 10)) != 0)
				durationList_.ClearChanged();
			if ((_changed & (0x01 << 11)) != 0)
				emptyList_.ClearChanged();
			if ((_changed & (0x01 << 12)) != 0)
				enumList_.ClearChanged();
			if ((_changed & (0x01 << 13)) != 0)
				itemList_.ClearChanged();
			_changed = 0;
		}

		public void Write(Kdsync.JsonWriter writer)
		{
			writer.WriteStartObject();
			writer.WriteRepeated("Int32List", int32List_);
			writer.WriteRepeated("Uint32List", uint32List_);
			writer.WriteRepeated("Int64List", int64List_);
			writer.WriteRepeated("Uint64List", uint64List_);
			writer.WriteRepeated("FloatList", floatList_);
			writer.WriteRepeated("DoubleList", doubleList_);
			writer.WriteRepeated("BoolList", boolList_);
			writer.WriteRepeated("StringList", stringList_);
			writer.WriteRepeated("TimestampList", timestampList_);
			writer.WriteRepeated("DurationList", durationList_);
			writer.WriteRepeated("EmptyList", emptyList_);
			writer.WriteRepeated("EnumList", enumList_);
			writer.WriteRepeated("ItemList", itemList_);
			writer.WriteEndObject();
		}

		public override string ToString()
		{
			Kdsync.JsonWriter writer = new Kdsync.JsonWriter();
			writer.WriteMessageValue(this);
			return writer.ToString();
		}
	}

	public class AllMap : Kdsync.IMessage
	{
		public AllMap()
		{
			int32Int32Map_ = new Kdsync.Map<int, int>();
			int64Int64Map_ = new Kdsync.Map<long, long>();
			uint32Uint32Map_ = new Kdsync.Map<uint, uint>();
			uint64Uint64Map_ = new Kdsync.Map<ulong, ulong>();
			boolFloatMap_ = new Kdsync.Map<bool, float>();
			stringDoubleMap_ = new Kdsync.Map<string, double>();
			int32BoolMap_ = new Kdsync.Map<int, bool>();
			int64StringMap_ = new Kdsync.Map<long, string>();
			uint32BytesMap_ = new Kdsync.Map<uint, byte[]>();
			uint64TimestampMap_ = new Kdsync.Map<ulong, Kdsync.Timestamp>();
			boolDurationMap_ = new Kdsync.Map<bool, Kdsync.Duration>();
			stringEmptyMap_ = new Kdsync.Map<string, Kdsync.Empty>();
			int32ItemTypeMap_ = new Kdsync.Map<int, ItemType>();
			int64ItemDataMap_ = new Kdsync.Map<long, ItemData>();
		}

		private static readonly Kdsync.Map<int, int>.Codec _map_int32Int32Map__codec = new Kdsync.Map<int, int>.Codec(Kdsync.FieldCodec.ForInt32(), Kdsync.FieldCodec.ForInt32(), 1);
		private Kdsync.Map<int, int> int32Int32Map_;
		public Kdsync.Map<int, int> Int32Int32Map => int32Int32Map_;

		private static readonly Kdsync.Map<long, long>.Codec _map_int64Int64Map__codec = new Kdsync.Map<long, long>.Codec(Kdsync.FieldCodec.ForInt64(), Kdsync.FieldCodec.ForInt64(), 2);
		private Kdsync.Map<long, long> int64Int64Map_;
		public Kdsync.Map<long, long> Int64Int64Map => int64Int64Map_;

		private static readonly Kdsync.Map<uint, uint>.Codec _map_uint32Uint32Map__codec = new Kdsync.Map<uint, uint>.Codec(Kdsync.FieldCodec.ForUInt32(), Kdsync.FieldCodec.ForUInt32(), 3);
		private Kdsync.Map<uint, uint> uint32Uint32Map_;
		public Kdsync.Map<uint, uint> Uint32Uint32Map => uint32Uint32Map_;

		private static readonly Kdsync.Map<ulong, ulong>.Codec _map_uint64Uint64Map__codec = new Kdsync.Map<ulong, ulong>.Codec(Kdsync.FieldCodec.ForUInt64(), Kdsync.FieldCodec.ForUInt64(), 4);
		private Kdsync.Map<ulong, ulong> uint64Uint64Map_;
		public Kdsync.Map<ulong, ulong> Uint64Uint64Map => uint64Uint64Map_;

		private static readonly Kdsync.Map<bool, float>.Codec _map_boolFloatMap__codec = new Kdsync.Map<bool, float>.Codec(Kdsync.FieldCodec.ForBool(), Kdsync.FieldCodec.ForFloat(), 5);
		private Kdsync.Map<bool, float> boolFloatMap_;
		public Kdsync.Map<bool, float> BoolFloatMap => boolFloatMap_;

		private static readonly Kdsync.Map<string, double>.Codec _map_stringDoubleMap__codec = new Kdsync.Map<string, double>.Codec(Kdsync.FieldCodec.ForString(), Kdsync.FieldCodec.ForDouble(), 6);
		private Kdsync.Map<string, double> stringDoubleMap_;
		public Kdsync.Map<string, double> StringDoubleMap => stringDoubleMap_;

		private static readonly Kdsync.Map<int, bool>.Codec _map_int32BoolMap__codec = new Kdsync.Map<int, bool>.Codec(Kdsync.FieldCodec.ForInt32(), Kdsync.FieldCodec.ForBool(), 7);
		private Kdsync.Map<int, bool> int32BoolMap_;
		public Kdsync.Map<int, bool> Int32BoolMap => int32BoolMap_;

		private static readonly Kdsync.Map<long, string>.Codec _map_int64StringMap__codec = new Kdsync.Map<long, string>.Codec(Kdsync.FieldCodec.ForInt64(), Kdsync.FieldCodec.ForString(), 8);
		private Kdsync.Map<long, string> int64StringMap_;
		public Kdsync.Map<long, string> Int64StringMap => int64StringMap_;

		private static readonly Kdsync.Map<uint, byte[]>.Codec _map_uint32BytesMap__codec = new Kdsync.Map<uint, byte[]>.Codec(Kdsync.FieldCodec.ForUInt32(), Kdsync.FieldCodec.ForBytes(), 9);
		private Kdsync.Map<uint, byte[]> uint32BytesMap_;
		public Kdsync.Map<uint, byte[]> Uint32BytesMap => uint32BytesMap_;

		private static readonly Kdsync.Map<ulong, Kdsync.Timestamp>.Codec _map_uint64TimestampMap__codec = new Kdsync.Map<ulong, Kdsync.Timestamp>.Codec(Kdsync.FieldCodec.ForUInt64(), Kdsync.FieldCodec.ForTimestamp(), 10);
		private Kdsync.Map<ulong, Kdsync.Timestamp> uint64TimestampMap_;
		public Kdsync.Map<ulong, Kdsync.Timestamp> Uint64TimestampMap => uint64TimestampMap_;

		private static readonly Kdsync.Map<bool, Kdsync.Duration>.Codec _map_boolDurationMap__codec = new Kdsync.Map<bool, Kdsync.Duration>.Codec(Kdsync.FieldCodec.ForBool(), Kdsync.FieldCodec.ForDuration(), 11);
		private Kdsync.Map<bool, Kdsync.Duration> boolDurationMap_;
		public Kdsync.Map<bool, Kdsync.Duration> BoolDurationMap => boolDurationMap_;

		private static readonly Kdsync.Map<string, Kdsync.Empty>.Codec _map_stringEmptyMap__codec = new Kdsync.Map<string, Kdsync.Empty>.Codec(Kdsync.FieldCodec.ForString(), Kdsync.FieldCodec.ForEmpty(), 12);
		private Kdsync.Map<string, Kdsync.Empty> stringEmptyMap_;
		public Kdsync.Map<string, Kdsync.Empty> StringEmptyMap => stringEmptyMap_;

		private static readonly Kdsync.Map<int, ItemType>.Codec _map_int32ItemTypeMap__codec = new Kdsync.Map<int, ItemType>.Codec(Kdsync.FieldCodec.ForInt32(), Kdsync.FieldCodec.ForEnum(x => (int)x, x => (ItemType)x), 13);
		private Kdsync.Map<int, ItemType> int32ItemTypeMap_;
		public Kdsync.Map<int, ItemType> Int32ItemTypeMap => int32ItemTypeMap_;

		private static readonly Kdsync.Map<long, ItemData>.Codec _map_int64ItemDataMap__codec = new Kdsync.Map<long, ItemData>.Codec(Kdsync.FieldCodec.ForInt64(), Kdsync.FieldCodec.ForMessage<ItemData>(), 14);
		private Kdsync.Map<long, ItemData> int64ItemDataMap_;
		public Kdsync.Map<long, ItemData> Int64ItemDataMap => int64ItemDataMap_;

		private long _changed;

		public event Action<AllMap, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Int32Int32Map => (_changed & (0x01 << 1)) != 0;
			public bool Int64Int64Map => (_changed & (0x01 << 2)) != 0;
			public bool Uint32Uint32Map => (_changed & (0x01 << 3)) != 0;
			public bool Uint64Uint64Map => (_changed & (0x01 << 4)) != 0;
			public bool BoolFloatMap => (_changed & (0x01 << 5)) != 0;
			public bool StringDoubleMap => (_changed & (0x01 << 6)) != 0;
			public bool Int32BoolMap => (_changed & (0x01 << 7)) != 0;
			public bool Int64StringMap => (_changed & (0x01 << 8)) != 0;
			public bool Uint32BytesMap => (_changed & (0x01 << 9)) != 0;
			public bool Uint64TimestampMap => (_changed & (0x01 << 10)) != 0;
			public bool BoolDurationMap => (_changed & (0x01 << 11)) != 0;
			public bool StringEmptyMap => (_changed & (0x01 << 12)) != 0;
			public bool Int32ItemTypeMap => (_changed & (0x01 << 13)) != 0;
			public bool Int64ItemDataMap => (_changed & (0x01 << 14)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void MergeFrom(ref Kdsync.ParseContext ctx)
		{
			uint tag;
			while ((tag = ctx.ReadTag()) != 0)
			{
				var num = Kdsync.WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
					case 1:
						int32Int32Map_.MergeFrom(ref ctx, _map_int32Int32Map__codec);
						_changed |= 0x01 << 1;
						break;
					case 2:
						int64Int64Map_.MergeFrom(ref ctx, _map_int64Int64Map__codec);
						_changed |= 0x01 << 2;
						break;
					case 3:
						uint32Uint32Map_.MergeFrom(ref ctx, _map_uint32Uint32Map__codec);
						_changed |= 0x01 << 3;
						break;
					case 4:
						uint64Uint64Map_.MergeFrom(ref ctx, _map_uint64Uint64Map__codec);
						_changed |= 0x01 << 4;
						break;
					case 5:
						boolFloatMap_.MergeFrom(ref ctx, _map_boolFloatMap__codec);
						_changed |= 0x01 << 5;
						break;
					case 6:
						stringDoubleMap_.MergeFrom(ref ctx, _map_stringDoubleMap__codec);
						_changed |= 0x01 << 6;
						break;
					case 7:
						int32BoolMap_.MergeFrom(ref ctx, _map_int32BoolMap__codec);
						_changed |= 0x01 << 7;
						break;
					case 8:
						int64StringMap_.MergeFrom(ref ctx, _map_int64StringMap__codec);
						_changed |= 0x01 << 8;
						break;
					case 9:
						uint32BytesMap_.MergeFrom(ref ctx, _map_uint32BytesMap__codec);
						_changed |= 0x01 << 9;
						break;
					case 10:
						uint64TimestampMap_.MergeFrom(ref ctx, _map_uint64TimestampMap__codec);
						_changed |= 0x01 << 10;
						break;
					case 11:
						boolDurationMap_.MergeFrom(ref ctx, _map_boolDurationMap__codec);
						_changed |= 0x01 << 11;
						break;
					case 12:
						stringEmptyMap_.MergeFrom(ref ctx, _map_stringEmptyMap__codec);
						_changed |= 0x01 << 12;
						break;
					case 13:
						int32ItemTypeMap_.MergeFrom(ref ctx, _map_int32ItemTypeMap__codec);
						_changed |= 0x01 << 13;
						break;
					case 14:
						int64ItemDataMap_.MergeFrom(ref ctx, _map_int64ItemDataMap__codec);
						_changed |= 0x01 << 14;
						break;
					default:
						ctx.SkipLastField();
						break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				int32Int32Map_.RaiseChanged();
			if ((_changed & (0x01 << 2)) != 0)
				int64Int64Map_.RaiseChanged();
			if ((_changed & (0x01 << 3)) != 0)
				uint32Uint32Map_.RaiseChanged();
			if ((_changed & (0x01 << 4)) != 0)
				uint64Uint64Map_.RaiseChanged();
			if ((_changed & (0x01 << 5)) != 0)
				boolFloatMap_.RaiseChanged();
			if ((_changed & (0x01 << 6)) != 0)
				stringDoubleMap_.RaiseChanged();
			if ((_changed & (0x01 << 7)) != 0)
				int32BoolMap_.RaiseChanged();
			if ((_changed & (0x01 << 8)) != 0)
				int64StringMap_.RaiseChanged();
			if ((_changed & (0x01 << 9)) != 0)
				uint32BytesMap_.RaiseChanged();
			if ((_changed & (0x01 << 10)) != 0)
				uint64TimestampMap_.RaiseChanged();
			if ((_changed & (0x01 << 11)) != 0)
				boolDurationMap_.RaiseChanged();
			if ((_changed & (0x01 << 12)) != 0)
				stringEmptyMap_.RaiseChanged();
			if ((_changed & (0x01 << 13)) != 0)
				int32ItemTypeMap_.RaiseChanged();
			if ((_changed & (0x01 << 14)) != 0)
				int64ItemDataMap_.RaiseChanged();
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				int32Int32Map_.ClearChanged();
			if ((_changed & (0x01 << 2)) != 0)
				int64Int64Map_.ClearChanged();
			if ((_changed & (0x01 << 3)) != 0)
				uint32Uint32Map_.ClearChanged();
			if ((_changed & (0x01 << 4)) != 0)
				uint64Uint64Map_.ClearChanged();
			if ((_changed & (0x01 << 5)) != 0)
				boolFloatMap_.ClearChanged();
			if ((_changed & (0x01 << 6)) != 0)
				stringDoubleMap_.ClearChanged();
			if ((_changed & (0x01 << 7)) != 0)
				int32BoolMap_.ClearChanged();
			if ((_changed & (0x01 << 8)) != 0)
				int64StringMap_.ClearChanged();
			if ((_changed & (0x01 << 9)) != 0)
				uint32BytesMap_.ClearChanged();
			if ((_changed & (0x01 << 10)) != 0)
				uint64TimestampMap_.ClearChanged();
			if ((_changed & (0x01 << 11)) != 0)
				boolDurationMap_.ClearChanged();
			if ((_changed & (0x01 << 12)) != 0)
				stringEmptyMap_.ClearChanged();
			if ((_changed & (0x01 << 13)) != 0)
				int32ItemTypeMap_.ClearChanged();
			if ((_changed & (0x01 << 14)) != 0)
				int64ItemDataMap_.ClearChanged();
			_changed = 0;
		}

		public void Write(Kdsync.JsonWriter writer)
		{
			writer.WriteStartObject();
			writer.WriteMap("Int32Int32Map", int32Int32Map_);
			writer.WriteMap("Int64Int64Map", int64Int64Map_);
			writer.WriteMap("Uint32Uint32Map", uint32Uint32Map_);
			writer.WriteMap("Uint64Uint64Map", uint64Uint64Map_);
			writer.WriteMap("BoolFloatMap", boolFloatMap_);
			writer.WriteMap("StringDoubleMap", stringDoubleMap_);
			writer.WriteMap("Int32BoolMap", int32BoolMap_);
			writer.WriteMap("Int64StringMap", int64StringMap_);
			writer.WriteMap("Uint32BytesMap", uint32BytesMap_);
			writer.WriteMap("Uint64TimestampMap", uint64TimestampMap_);
			writer.WriteMap("BoolDurationMap", boolDurationMap_);
			writer.WriteMap("StringEmptyMap", stringEmptyMap_);
			writer.WriteMap("Int32ItemTypeMap", int32ItemTypeMap_);
			writer.WriteMap("Int64ItemDataMap", int64ItemDataMap_);
			writer.WriteEndObject();
		}

		public override string ToString()
		{
			Kdsync.JsonWriter writer = new Kdsync.JsonWriter();
			writer.WriteMessageValue(this);
			return writer.ToString();
		}
	}
}
