// Code generated by kds. DO NOT EDIT.
// source: example2.kds

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: example2.proto

package kdspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type City struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PlayerId        int64                  `protobuf:"varint,1,opt,name=PlayerId"`
	xxx_hidden_PlayerBasicInfo *PlayerBasicInfo       `protobuf:"bytes,2,opt,name=PlayerBasicInfo"`
	xxx_hidden_CityInfo        *CityBaseInfo          `protobuf:"bytes,3,opt,name=CityInfo"`
	xxx_hidden_Troops          []int64                `protobuf:"varint,4,rep,packed,name=Troops"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *City) Reset() {
	*x = City{}
	mi := &file_example2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_example2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *City) GetPlayerId() int64 {
	if x != nil {
		return x.xxx_hidden_PlayerId
	}
	return 0
}

func (x *City) GetPlayerBasicInfo() *PlayerBasicInfo {
	if x != nil {
		return x.xxx_hidden_PlayerBasicInfo
	}
	return nil
}

func (x *City) GetCityInfo() *CityBaseInfo {
	if x != nil {
		return x.xxx_hidden_CityInfo
	}
	return nil
}

func (x *City) GetTroops() []int64 {
	if x != nil {
		return x.xxx_hidden_Troops
	}
	return nil
}

func (x *City) SetPlayerId(v int64) {
	x.xxx_hidden_PlayerId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *City) SetPlayerBasicInfo(v *PlayerBasicInfo) {
	x.xxx_hidden_PlayerBasicInfo = v
}

func (x *City) SetCityInfo(v *CityBaseInfo) {
	x.xxx_hidden_CityInfo = v
}

func (x *City) SetTroops(v []int64) {
	x.xxx_hidden_Troops = v
}

func (x *City) HasPlayerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *City) HasPlayerBasicInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PlayerBasicInfo != nil
}

func (x *City) HasCityInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CityInfo != nil
}

func (x *City) ClearPlayerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PlayerId = 0
}

func (x *City) ClearPlayerBasicInfo() {
	x.xxx_hidden_PlayerBasicInfo = nil
}

func (x *City) ClearCityInfo() {
	x.xxx_hidden_CityInfo = nil
}

type City_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PlayerId        *int64
	PlayerBasicInfo *PlayerBasicInfo
	CityInfo        *CityBaseInfo
	Troops          []int64
}

func (b0 City_builder) Build() *City {
	m0 := &City{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PlayerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_PlayerId = *b.PlayerId
	}
	x.xxx_hidden_PlayerBasicInfo = b.PlayerBasicInfo
	x.xxx_hidden_CityInfo = b.CityInfo
	x.xxx_hidden_Troops = b.Troops
	return m0
}

type CityBaseInfo struct {
	state                  protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Positions   *[]*Vector               `protobuf:"bytes,1,rep,name=Positions"`
	xxx_hidden_Troops      map[int32]*emptypb.Empty `protobuf:"bytes,2,rep,name=Troops" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_BuildInfo   []byte                   `protobuf:"bytes,3,opt,name=BuildInfo"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CityBaseInfo) Reset() {
	*x = CityBaseInfo{}
	mi := &file_example2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityBaseInfo) ProtoMessage() {}

func (x *CityBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_example2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CityBaseInfo) GetPositions() []*Vector {
	if x != nil {
		if x.xxx_hidden_Positions != nil {
			return *x.xxx_hidden_Positions
		}
	}
	return nil
}

func (x *CityBaseInfo) GetTroops() map[int32]*emptypb.Empty {
	if x != nil {
		return x.xxx_hidden_Troops
	}
	return nil
}

func (x *CityBaseInfo) GetBuildInfo() []byte {
	if x != nil {
		return x.xxx_hidden_BuildInfo
	}
	return nil
}

func (x *CityBaseInfo) SetPositions(v []*Vector) {
	x.xxx_hidden_Positions = &v
}

func (x *CityBaseInfo) SetTroops(v map[int32]*emptypb.Empty) {
	x.xxx_hidden_Troops = v
}

func (x *CityBaseInfo) SetBuildInfo(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_BuildInfo = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CityBaseInfo) HasBuildInfo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CityBaseInfo) ClearBuildInfo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_BuildInfo = nil
}

type CityBaseInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Positions []*Vector
	Troops    map[int32]*emptypb.Empty
	BuildInfo []byte
}

func (b0 CityBaseInfo_builder) Build() *CityBaseInfo {
	m0 := &CityBaseInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Positions = &b.Positions
	x.xxx_hidden_Troops = b.Troops
	if b.BuildInfo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_BuildInfo = b.BuildInfo
	}
	return m0
}

type Vector struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_X           int32                  `protobuf:"varint,1,opt,name=X"`
	xxx_hidden_Y           int32                  `protobuf:"varint,2,opt,name=Y"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_example2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_example2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Vector) GetX() int32 {
	if x != nil {
		return x.xxx_hidden_X
	}
	return 0
}

func (x *Vector) GetY() int32 {
	if x != nil {
		return x.xxx_hidden_Y
	}
	return 0
}

func (x *Vector) SetX(v int32) {
	x.xxx_hidden_X = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Vector) SetY(v int32) {
	x.xxx_hidden_Y = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Vector) HasX() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Vector) HasY() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Vector) ClearX() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_X = 0
}

func (x *Vector) ClearY() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Y = 0
}

type Vector_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	X *int32
	Y *int32
}

func (b0 Vector_builder) Build() *Vector {
	m0 := &Vector{}
	b, x := &b0, m0
	_, _ = b, x
	if b.X != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_X = *b.X
	}
	if b.Y != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Y = *b.Y
	}
	return m0
}

var File_example2_proto protoreflect.FileDescriptor

const file_example2_proto_rawDesc = "" +
	"\n" +
	"\x0eexample2.proto\x12\x03kds\x1a\x0eexample1.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa9\x01\n" +
	"\x04City\x12\x1a\n" +
	"\bPlayerId\x18\x01 \x01(\x03R\bPlayerId\x12>\n" +
	"\x0fPlayerBasicInfo\x18\x02 \x01(\v2\x14.kds.PlayerBasicInfoR\x0fPlayerBasicInfo\x12-\n" +
	"\bCityInfo\x18\x03 \x01(\v2\x11.kds.CityBaseInfoR\bCityInfo\x12\x16\n" +
	"\x06Troops\x18\x04 \x03(\x03R\x06Troops\"\xe1\x01\n" +
	"\fCityBaseInfo\x12)\n" +
	"\tPositions\x18\x01 \x03(\v2\v.kds.VectorR\tPositions\x125\n" +
	"\x06Troops\x18\x02 \x03(\v2\x1d.kds.CityBaseInfo.TroopsEntryR\x06Troops\x12\x1c\n" +
	"\tBuildInfo\x18\x03 \x01(\fR\tBuildInfo\x1aQ\n" +
	"\vTroopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.EmptyR\x05value:\x028\x01\"$\n" +
	"\x06Vector\x12\f\n" +
	"\x01X\x18\x01 \x01(\x05R\x01X\x12\f\n" +
	"\x01Y\x18\x02 \x01(\x05R\x01YB/Z-github.com/iakud/knoll/kds/kdsc/example/kdspbb\beditionsp\xe8\a"

var file_example2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_example2_proto_goTypes = []any{
	(*City)(nil),            // 0: kds.City
	(*CityBaseInfo)(nil),    // 1: kds.CityBaseInfo
	(*Vector)(nil),          // 2: kds.Vector
	nil,                     // 3: kds.CityBaseInfo.TroopsEntry
	(*PlayerBasicInfo)(nil), // 4: kds.PlayerBasicInfo
	(*emptypb.Empty)(nil),   // 5: google.protobuf.Empty
}
var file_example2_proto_depIdxs = []int32{
	4, // 0: kds.City.PlayerBasicInfo:type_name -> kds.PlayerBasicInfo
	1, // 1: kds.City.CityInfo:type_name -> kds.CityBaseInfo
	2, // 2: kds.CityBaseInfo.Positions:type_name -> kds.Vector
	3, // 3: kds.CityBaseInfo.Troops:type_name -> kds.CityBaseInfo.TroopsEntry
	5, // 4: kds.CityBaseInfo.TroopsEntry.value:type_name -> google.protobuf.Empty
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_example2_proto_init() }
func file_example2_proto_init() {
	if File_example2_proto != nil {
		return
	}
	file_example1_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example2_proto_rawDesc), len(file_example2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example2_proto_goTypes,
		DependencyIndexes: file_example2_proto_depIdxs,
		MessageInfos:      file_example2_proto_msgTypes,
	}.Build()
	File_example2_proto = out.File
	file_example2_proto_goTypes = nil
	file_example2_proto_depIdxs = nil
}
