{{- /* BEGIN DEFINE */ -}}

{{- define "Enum"}}
enum {{.Name}} {
{{- range .EnumFields}}
	{{.Name}} = {{.Value}};
{{- end}}
}
{{- end}}

{{- define "Entity"}}
message {{.Name}} {
{{- range .Fields}}
	{{.Type}} {{.Name}} = {{.Number}};
{{- end}}
}
{{- end}}

{{- define "Component"}}
message {{.Name}} {
{{- range .Fields}}
	{{.Type}} {{.Name}} = {{.Number}};
{{- end}}
}
{{- end}}

{{- /* END DEFINE */ -}}

// Code generated by kds. DO NOT EDIT.

syntax = "proto3";

package {{.Package}};
{{""}}
{{- range .Imports}}
import "{{.}}.proto";
{{- end}}
import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";

option go_package="github.com/iakud/keeper/kds/kdsc/example/pb";

{{- range .Defs}}
{{- if IsEnum .}}
{{template "Enum" .}}
{{- else if IsEntity .}}
{{template "Entity" .}}
{{- else if IsComponent .}}
{{template "Component" .}}
{{- end}}
{{- end}}