// Code generated by kds. DO NOT EDIT.

syntax = "proto3";

package {{.Package}};
{{""}}
{{- range .Imports}}
import "{{.}}.proto";
{{- end}}
import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";

option go_package="github.com/iakud/keeper/kds/kdsc/example/pb";

{{""}}
{{- range .Entities}}
message {{.Name}} {
{{- range .Fields}}
	{{.Type}} {{.Name}} = {{.Number}};
{{- end}}
}
{{- end}}

{{- range .Components}}
{{""}}
message {{.Name}} {
{{- range .Fields}}
	{{.Type}} {{.Name}} = {{.Number}};
{{- end}}
}
{{- end}}