// Code generated by kds. DO NOT EDIT.
// source: example1.kds

using System;
using System.Collections.Generic;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;

namespace kds
{
	public class Player
	{
		private readonly long _id;
		public long Id => _id;

		public Player(long id)
		{
			_id = id;
			info_ = new PlayerBasicInfo();
			hero_ = new PlayerHero();
			bag_ = new PlayerBag();
		}

		private PlayerBasicInfo info_;
		public PlayerBasicInfo Info => info_;
		public bool IsInfoChanged => (_changed & (0x01 << 1)) != 0;

		private PlayerHero hero_;
		public PlayerHero Hero => hero_;
		public bool IsHeroChanged => (_changed & (0x01 << 2)) != 0;

		private PlayerBag bag_;
		public PlayerBag Bag => bag_;
		public bool IsBagChanged => (_changed & (0x01 << 3)) != 0;

		private long _changed;

		public event Action<Player>? OnChanged;

		public void InvokeChange()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				info_.InvokeChange();
			if ((_changed & (0x01 << 2)) != 0)
				hero_.InvokeChange();
			if ((_changed & (0x01 << 3)) != 0)
				bag_.InvokeChange();
			OnChanged?.Invoke(this);
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					info_.Unmarshal(stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 1;
					break;
				case 2:
					hero_.Unmarshal(stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 2;
					break;
				case 3:
					bag_.Unmarshal(stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 3;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class PlayerBasicInfo
	{
		public PlayerBasicInfo()
		{
			name_ = string.Empty;
		}

		private string name_;
		public string Name => name_;
		public bool IsNameChanged => (_changed & (0x01 << 1)) != 0;

		private bool isNew_;
		public bool IsNew => isNew_;
		public bool IsIsNewChanged => (_changed & (0x01 << 3)) != 0;

		private DateTime createTime_;
		public DateTime CreateTime => createTime_;
		public bool IsCreateTimeChanged => (_changed & (0x01 << 5)) != 0;

		private long _changed;

		public event Action<PlayerBasicInfo>? OnChanged;

		public void InvokeChange()
		{
			if (_changed == 0)
				return;
			OnChanged?.Invoke(this);
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					name_ = stream.ReadString();
					_changed |= 0x01 << 1;
					break;
				case 3:
					isNew_ = stream.ReadBool();
					_changed |= 0x01 << 3;
					break;
				case 5:
					createTime_ = Timestamp.Parser.ParseFrom(stream).ToDateTime();
					_changed |= 0x01 << 5;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class PlayerHero
	{
		public PlayerHero()
		{
			heroes_ = new Dictionary<long, Hero>();
		}

		private Dictionary<long, Hero> heroes_;
		public Dictionary<long, Hero> Heroes => heroes_;
		public bool IsHeroesChanged => (_changed & (0x01 << 1)) != 0;

		private long _changed;

		public event Action<PlayerHero>? OnChanged;

		public void InvokeChange()
		{
			if (_changed == 0)
				return;
			OnChanged?.Invoke(this);
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					Int64Hero_map.Unmarshal(heroes_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 1;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class PlayerBag
	{
		public PlayerBag()
		{
			resources_ = new Dictionary<int, int>();
		}

		private Dictionary<int, int> resources_;
		public Dictionary<int, int> Resources => resources_;
		public bool IsResourcesChanged => (_changed & (0x01 << 1)) != 0;

		private long _changed;

		public event Action<PlayerBag>? OnChanged;

		public void InvokeChange()
		{
			if (_changed == 0)
				return;
			OnChanged?.Invoke(this);
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					Int32Int32_map.Unmarshal(resources_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 1;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class Hero
	{
		public Hero()
		{
		}

		private int heroId_;
		public int HeroId => heroId_;
		public bool IsHeroIdChanged => (_changed & (0x01 << 1)) != 0;

		private int heroLevel_;
		public int HeroLevel => heroLevel_;
		public bool IsHeroLevelChanged => (_changed & (0x01 << 2)) != 0;

		private HeroType type_;
		public HeroType Type => type_;
		public bool IsTypeChanged => (_changed & (0x01 << 3)) != 0;

		private TimeSpan needTime_;
		public TimeSpan NeedTime => needTime_;
		public bool IsNeedTimeChanged => (_changed & (0x01 << 4)) != 0;

		private long _changed;

		public event Action<Hero>? OnChanged;

		public void InvokeChange()
		{
			if (_changed == 0)
				return;
			OnChanged?.Invoke(this);
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					heroId_ = stream.ReadInt32();
					_changed |= 0x01 << 1;
					break;
				case 2:
					heroLevel_ = stream.ReadInt32();
					_changed |= 0x01 << 2;
					break;
				case 3:
					type_ = (HeroType)stream.ReadEnum();
					_changed |= 0x01 << 3;
					break;
				case 4:
					needTime_ = Duration.Parser.ParseFrom(stream).ToTimeSpan();
					_changed |= 0x01 << 4;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}

	public static class Int64Hero_map
	{
		public static void Unmarshal(Dictionary<long, Hero> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt64());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				long k = default;
				byte[] v = [];
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt64();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadBytes().ToByteArray();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				if (data.TryGetValue(k, out var c))
				{
					c.Unmarshal(v);	
				}
				else
				{
					c = new Hero();
					c.Unmarshal(v);
					data[k] = c;
				}
			}
		}
	}
	public enum HeroType
	{
		HeroType1 = 0,
		HeroType2 = 2,
		HeroType3 = -5,
	}
}
