// Code generated by kds. DO NOT EDIT.
// source: kds/sync.kds

using System;
using System.Collections.Generic;
using Google.Protobuf;

namespace kds
{
	public class PlayerSync
	{
		private readonly long _id;
		public long Id => _id;

		public PlayerSync(long id)
		{
			_id = id;
			info_ = new PlayerSyncInfo();
			hero_ = new PlayerSyncHero();
			bag_ = new PlayerSyncBag();
		}

		private PlayerSyncInfo info_;
		public PlayerSyncInfo Info => info_;
		public bool IsInfoChanged => (_changed & (0x01 << 1)) != 0;

		private PlayerSyncHero hero_;
		public PlayerSyncHero Hero => hero_;
		public bool IsHeroChanged => (_changed & (0x01 << 2)) != 0;

		private PlayerSyncBag bag_;
		public PlayerSyncBag Bag => bag_;
		public bool IsBagChanged => (_changed & (0x01 << 3)) != 0;

		private long _changed;

		public event Action<PlayerSync, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Info => (_changed & (0x01 << 1)) != 0;
			public bool Hero => (_changed & (0x01 << 2)) != 0;
			public bool Bag => (_changed & (0x01 << 3)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void ApplySync(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					info_.ApplySync(stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 1;
					break;
				case 2:
					hero_.ApplySync(stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 2;
					break;
				case 3:
					bag_.ApplySync(stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 3;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				info_.RaiseChanged();
			if ((_changed & (0x01 << 2)) != 0)
				hero_.RaiseChanged();
			if ((_changed & (0x01 << 3)) != 0)
				bag_.RaiseChanged();
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				info_.ClearChanged();
			if ((_changed & (0x01 << 2)) != 0)
				hero_.ClearChanged();
			if ((_changed & (0x01 << 3)) != 0)
				bag_.ClearChanged();
			_changed = 0;
		}
	}
	public class PlayerSyncInfo
	{
		public PlayerSyncInfo()
		{
			name_ = string.Empty;
		}

		private string name_;
		public string Name => name_;
		public bool IsNameChanged => (_changed & (0x01 << 1)) != 0;

		private int level_;
		public int Level => level_;
		public bool IsLevelChanged => (_changed & (0x01 << 2)) != 0;

		private bool isNew_;
		public bool IsNew => isNew_;
		public bool IsIsNewChanged => (_changed & (0x01 << 3)) != 0;

		private long _changed;

		public event Action<PlayerSyncInfo, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Name => (_changed & (0x01 << 1)) != 0;
			public bool Level => (_changed & (0x01 << 2)) != 0;
			public bool IsNew => (_changed & (0x01 << 3)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void ApplySync(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					name_ = stream.ReadString();
					_changed |= 0x01 << 1;
					break;
				case 2:
					level_ = stream.ReadInt32();
					_changed |= 0x01 << 2;
					break;
				case 3:
					isNew_ = stream.ReadBool();
					_changed |= 0x01 << 3;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			_changed = 0;
		}
	}
	public class PlayerSyncHero
	{
		public PlayerSyncHero()
		{
			heroes_ = new Dictionary<long, SyncHero>();
		}

		private Dictionary<long, SyncHero> heroes_;
		public Dictionary<long, SyncHero> Heroes => heroes_;
		public bool IsHeroesChanged => (_changed & (0x01 << 1)) != 0;

		private long _changed;

		public event Action<PlayerSyncHero, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Heroes => (_changed & (0x01 << 1)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void ApplySync(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					Int64SyncHero_map.ApplySync(heroes_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 1;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				Int64SyncHero_map.RaiseChanged(heroes_);
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				Int64SyncHero_map.ClearChanged(heroes_);
			_changed = 0;
		}
	}
	public class PlayerSyncBag
	{
		public PlayerSyncBag()
		{
			items_ = new Dictionary<int, int>();
			currencies_ = new Dictionary<int, int>();
		}

		private Dictionary<int, int> items_;
		public Dictionary<int, int> Items => items_;
		public bool IsItemsChanged => (_changed & (0x01 << 1)) != 0;

		private Dictionary<int, int> currencies_;
		public Dictionary<int, int> Currencies => currencies_;
		public bool IsCurrenciesChanged => (_changed & (0x01 << 2)) != 0;

		private long _changed;

		public event Action<PlayerSyncBag, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Items => (_changed & (0x01 << 1)) != 0;
			public bool Currencies => (_changed & (0x01 << 2)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void ApplySync(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					Int32Int32_map.ApplySync(items_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 1;
					break;
				case 2:
					Int32Int32_map.ApplySync(currencies_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 2;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				Int32Int32_map.RaiseChanged(items_);
			if ((_changed & (0x01 << 2)) != 0)
				Int32Int32_map.RaiseChanged(currencies_);
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				Int32Int32_map.ClearChanged(items_);
			if ((_changed & (0x01 << 2)) != 0)
				Int32Int32_map.ClearChanged(currencies_);
			_changed = 0;
		}
	}
	public class SyncHero
	{
		public SyncHero()
		{
		}

		private int heroId_;
		public int HeroId => heroId_;
		public bool IsHeroIdChanged => (_changed & (0x01 << 1)) != 0;

		private int level_;
		public int Level => level_;
		public bool IsLevelChanged => (_changed & (0x01 << 2)) != 0;

		private int star_;
		public int Star => star_;
		public bool IsStarChanged => (_changed & (0x01 << 3)) != 0;

		private int exp_;
		public int Exp => exp_;
		public bool IsExpChanged => (_changed & (0x01 << 4)) != 0;

		private long _changed;

		public event Action<SyncHero, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool HeroId => (_changed & (0x01 << 1)) != 0;
			public bool Level => (_changed & (0x01 << 2)) != 0;
			public bool Star => (_changed & (0x01 << 3)) != 0;
			public bool Exp => (_changed & (0x01 << 4)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void ApplySync(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					heroId_ = stream.ReadInt32();
					_changed |= 0x01 << 1;
					break;
				case 2:
					level_ = stream.ReadInt32();
					_changed |= 0x01 << 2;
					break;
				case 3:
					star_ = stream.ReadInt32();
					_changed |= 0x01 << 3;
					break;
				case 4:
					exp_ = stream.ReadInt32();
					_changed |= 0x01 << 4;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			_changed = 0;
		}
	}

	public static class Int64SyncHero_map
	{
		public static void ApplySync(Dictionary<long, SyncHero> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt64());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				long k = default;
				byte[] v = [];
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt64();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadBytes().ToByteArray();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				if (data.TryGetValue(k, out var c))
				{
					c.ApplySync(v);	
				}
				else
				{
					c = new SyncHero();
					c.ApplySync(v);
					data[k] = c;
				}
			}
		}

		public static void RaiseChanged(Dictionary<long, SyncHero> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<long, SyncHero> data)
		{
			// FIXME:
		}
	}
}
