// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: knet.proto

package knetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg int32

const (
	Msg_INVALID        Msg = 0
	Msg_OK             Msg = 1
	Msg_ERROR          Msg = 2
	Msg_HANDSHAKE      Msg = 3
	Msg_PING           Msg = 4
	Msg_PONG           Msg = 5
	Msg_KICKED_OUT_NTF Msg = 6
	Msg_RESERVED_END   Msg = 100
)

// Enum value maps for Msg.
var (
	Msg_name = map[int32]string{
		0:   "INVALID",
		1:   "OK",
		2:   "ERROR",
		3:   "HANDSHAKE",
		4:   "PING",
		5:   "PONG",
		6:   "KICKED_OUT_NTF",
		100: "RESERVED_END",
	}
	Msg_value = map[string]int32{
		"INVALID":        0,
		"OK":             1,
		"ERROR":          2,
		"HANDSHAKE":      3,
		"PING":           4,
		"PONG":           5,
		"KICKED_OUT_NTF": 6,
		"RESERVED_END":   100,
	}
)

func (x Msg) Enum() *Msg {
	p := new(Msg)
	*p = x
	return p
}

func (x Msg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Msg) Descriptor() protoreflect.EnumDescriptor {
	return file_knet_proto_enumTypes[0].Descriptor()
}

func (Msg) Type() protoreflect.EnumType {
	return &file_knet_proto_enumTypes[0]
}

func (x Msg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Error struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Code        int32                  `protobuf:"varint,1,opt,name=Code"`
	xxx_hidden_Msg         *string                `protobuf:"bytes,2,opt,name=Msg"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_knet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_knet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.xxx_hidden_Code
	}
	return 0
}

func (x *Error) GetMsg() string {
	if x != nil {
		if x.xxx_hidden_Msg != nil {
			return *x.xxx_hidden_Msg
		}
		return ""
	}
	return ""
}

func (x *Error) SetCode(v int32) {
	x.xxx_hidden_Code = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Error) SetMsg(v string) {
	x.xxx_hidden_Msg = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Error) HasCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Error) HasMsg() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Error) ClearCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Code = 0
}

func (x *Error) ClearMsg() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Msg = nil
}

type Error_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Code *int32
	Msg  *string
}

func (b0 Error_builder) Build() *Error {
	m0 := &Error{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Code != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Code = *b.Code
	}
	if b.Msg != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Msg = b.Msg
	}
	return m0
}

type HandshakeRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Hash        uint64                 `protobuf:"varint,1,opt,name=Hash"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_knet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HandshakeRequest) GetHash() uint64 {
	if x != nil {
		return x.xxx_hidden_Hash
	}
	return 0
}

func (x *HandshakeRequest) SetHash(v uint64) {
	x.xxx_hidden_Hash = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *HandshakeRequest) HasHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HandshakeRequest) ClearHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Hash = 0
}

type HandshakeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Hash *uint64
}

func (b0 HandshakeRequest_builder) Build() *HandshakeRequest {
	m0 := &HandshakeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Hash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Hash = *b.Hash
	}
	return m0
}

type HandshakeReply struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeReply) Reset() {
	*x = HandshakeReply{}
	mi := &file_knet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeReply) ProtoMessage() {}

func (x *HandshakeReply) ProtoReflect() protoreflect.Message {
	mi := &file_knet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type HandshakeReply_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 HandshakeReply_builder) Build() *HandshakeReply {
	m0 := &HandshakeReply{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_knet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_knet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Ping_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Ping_builder) Build() *Ping {
	m0 := &Ping{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_knet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_knet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Pong_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Pong_builder) Build() *Pong {
	m0 := &Pong{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type KickedOutNotify struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message     *string                `protobuf:"bytes,1,opt,name=Message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *KickedOutNotify) Reset() {
	*x = KickedOutNotify{}
	mi := &file_knet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickedOutNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickedOutNotify) ProtoMessage() {}

func (x *KickedOutNotify) ProtoReflect() protoreflect.Message {
	mi := &file_knet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KickedOutNotify) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *KickedOutNotify) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *KickedOutNotify) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *KickedOutNotify) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Message = nil
}

type KickedOutNotify_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Message *string
}

func (b0 KickedOutNotify_builder) Build() *KickedOutNotify {
	m0 := &KickedOutNotify{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

var File_knet_proto protoreflect.FileDescriptor

const file_knet_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"knet.proto\x12\x06knetpb\"-\n" +
	"\x05Error\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x05R\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"&\n" +
	"\x10HandshakeRequest\x12\x12\n" +
	"\x04Hash\x18\x01 \x01(\x04R\x04Hash\"\x10\n" +
	"\x0eHandshakeReply\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong\"+\n" +
	"\x0fKickedOutNotify\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage*n\n" +
	"\x03Msg\x12\v\n" +
	"\aINVALID\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\r\n" +
	"\tHANDSHAKE\x10\x03\x12\b\n" +
	"\x04PING\x10\x04\x12\b\n" +
	"\x04PONG\x10\x05\x12\x12\n" +
	"\x0eKICKED_OUT_NTF\x10\x06\x12\x10\n" +
	"\fRESERVED_END\x10dB\x1eZ\x1cgithub.com/iakud/krpc/knetpbb\beditionsp\xe8\a"

var file_knet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_knet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_knet_proto_goTypes = []any{
	(Msg)(0),                 // 0: knetpb.Msg
	(*Error)(nil),            // 1: knetpb.Error
	(*HandshakeRequest)(nil), // 2: knetpb.HandshakeRequest
	(*HandshakeReply)(nil),   // 3: knetpb.HandshakeReply
	(*Ping)(nil),             // 4: knetpb.Ping
	(*Pong)(nil),             // 5: knetpb.Pong
	(*KickedOutNotify)(nil),  // 6: knetpb.KickedOutNotify
}
var file_knet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_knet_proto_init() }
func file_knet_proto_init() {
	if File_knet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_knet_proto_rawDesc), len(file_knet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_knet_proto_goTypes,
		DependencyIndexes: file_knet_proto_depIdxs,
		EnumInfos:         file_knet_proto_enumTypes,
		MessageInfos:      file_knet_proto_msgTypes,
	}.Build()
	File_knet_proto = out.File
	file_knet_proto_goTypes = nil
	file_knet_proto_depIdxs = nil
}
