// Code generated by kds. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: fieldmask.proto

package kdspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number     int32        `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	MapMask    *MapMask     `protobuf:"bytes,2,opt,name=MapMask,proto3" json:"MapMask,omitempty"`
	FieldMasks []*FieldMask `protobuf:"bytes,10,rep,name=FieldMasks,proto3" json:"FieldMasks,omitempty"`
}

func (x *FieldMask) Reset() {
	*x = FieldMask{}
	mi := &file_fieldmask_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMask) ProtoMessage() {}

func (x *FieldMask) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMask.ProtoReflect.Descriptor instead.
func (*FieldMask) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{0}
}

func (x *FieldMask) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *FieldMask) GetMapMask() *MapMask {
	if x != nil {
		return x.MapMask
	}
	return nil
}

func (x *FieldMask) GetFieldMasks() []*FieldMask {
	if x != nil {
		return x.FieldMasks
	}
	return nil
}

type Int32Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []int32 `protobuf:"varint,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
}

func (x *Int32Array) Reset() {
	*x = Int32Array{}
	mi := &file_fieldmask_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Array) ProtoMessage() {}

func (x *Int32Array) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Array.ProtoReflect.Descriptor instead.
func (*Int32Array) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{1}
}

func (x *Int32Array) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Int64Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []int64 `protobuf:"varint,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
}

func (x *Int64Array) Reset() {
	*x = Int64Array{}
	mi := &file_fieldmask_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Array) ProtoMessage() {}

func (x *Int64Array) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Array.ProtoReflect.Descriptor instead.
func (*Int64Array) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{2}
}

func (x *Int64Array) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type UInt32Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []uint32 `protobuf:"varint,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
}

func (x *UInt32Array) Reset() {
	*x = UInt32Array{}
	mi := &file_fieldmask_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UInt32Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInt32Array) ProtoMessage() {}

func (x *UInt32Array) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInt32Array.ProtoReflect.Descriptor instead.
func (*UInt32Array) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{3}
}

func (x *UInt32Array) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Uint64Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []uint64 `protobuf:"varint,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
}

func (x *Uint64Array) Reset() {
	*x = Uint64Array{}
	mi := &file_fieldmask_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint64Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64Array) ProtoMessage() {}

func (x *Uint64Array) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64Array.ProtoReflect.Descriptor instead.
func (*Uint64Array) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{4}
}

func (x *Uint64Array) GetValues() []uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type BoolArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []bool `protobuf:"varint,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
}

func (x *BoolArray) Reset() {
	*x = BoolArray{}
	mi := &file_fieldmask_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolArray) ProtoMessage() {}

func (x *BoolArray) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolArray.ProtoReflect.Descriptor instead.
func (*BoolArray) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{5}
}

func (x *BoolArray) GetValues() []bool {
	if x != nil {
		return x.Values
	}
	return nil
}

type StringArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *StringArray) Reset() {
	*x = StringArray{}
	mi := &file_fieldmask_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArray) ProtoMessage() {}

func (x *StringArray) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArray.ProtoReflect.Descriptor instead.
func (*StringArray) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{6}
}

func (x *StringArray) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type MapMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clear bool `protobuf:"varint,1,opt,name=Clear,proto3" json:"Clear,omitempty"`
	// Types that are assignable to DeleteKeys:
	//
	//	*MapMask_Int32DeleteKeys
	//	*MapMask_Int64DeleteKeys
	//	*MapMask_Uint32DeleteKeys
	//	*MapMask_Uint64DeleteKeys
	//	*MapMask_BoolDeleteKeys
	//	*MapMask_StringDeleteKeys
	DeleteKeys isMapMask_DeleteKeys `protobuf_oneof:"DeleteKeys"`
}

func (x *MapMask) Reset() {
	*x = MapMask{}
	mi := &file_fieldmask_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMask) ProtoMessage() {}

func (x *MapMask) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMask.ProtoReflect.Descriptor instead.
func (*MapMask) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{7}
}

func (x *MapMask) GetClear() bool {
	if x != nil {
		return x.Clear
	}
	return false
}

func (m *MapMask) GetDeleteKeys() isMapMask_DeleteKeys {
	if m != nil {
		return m.DeleteKeys
	}
	return nil
}

func (x *MapMask) GetInt32DeleteKeys() *Int32Array {
	if x, ok := x.GetDeleteKeys().(*MapMask_Int32DeleteKeys); ok {
		return x.Int32DeleteKeys
	}
	return nil
}

func (x *MapMask) GetInt64DeleteKeys() *Int64Array {
	if x, ok := x.GetDeleteKeys().(*MapMask_Int64DeleteKeys); ok {
		return x.Int64DeleteKeys
	}
	return nil
}

func (x *MapMask) GetUint32DeleteKeys() *UInt32Array {
	if x, ok := x.GetDeleteKeys().(*MapMask_Uint32DeleteKeys); ok {
		return x.Uint32DeleteKeys
	}
	return nil
}

func (x *MapMask) GetUint64DeleteKeys() *Uint64Array {
	if x, ok := x.GetDeleteKeys().(*MapMask_Uint64DeleteKeys); ok {
		return x.Uint64DeleteKeys
	}
	return nil
}

func (x *MapMask) GetBoolDeleteKeys() *BoolArray {
	if x, ok := x.GetDeleteKeys().(*MapMask_BoolDeleteKeys); ok {
		return x.BoolDeleteKeys
	}
	return nil
}

func (x *MapMask) GetStringDeleteKeys() *StringArray {
	if x, ok := x.GetDeleteKeys().(*MapMask_StringDeleteKeys); ok {
		return x.StringDeleteKeys
	}
	return nil
}

type isMapMask_DeleteKeys interface {
	isMapMask_DeleteKeys()
}

type MapMask_Int32DeleteKeys struct {
	Int32DeleteKeys *Int32Array `protobuf:"bytes,2,opt,name=Int32DeleteKeys,proto3,oneof"`
}

type MapMask_Int64DeleteKeys struct {
	Int64DeleteKeys *Int64Array `protobuf:"bytes,3,opt,name=Int64DeleteKeys,proto3,oneof"`
}

type MapMask_Uint32DeleteKeys struct {
	Uint32DeleteKeys *UInt32Array `protobuf:"bytes,4,opt,name=Uint32DeleteKeys,proto3,oneof"`
}

type MapMask_Uint64DeleteKeys struct {
	Uint64DeleteKeys *Uint64Array `protobuf:"bytes,5,opt,name=Uint64DeleteKeys,proto3,oneof"`
}

type MapMask_BoolDeleteKeys struct {
	BoolDeleteKeys *BoolArray `protobuf:"bytes,6,opt,name=BoolDeleteKeys,proto3,oneof"`
}

type MapMask_StringDeleteKeys struct {
	StringDeleteKeys *StringArray `protobuf:"bytes,7,opt,name=StringDeleteKeys,proto3,oneof"`
}

func (*MapMask_Int32DeleteKeys) isMapMask_DeleteKeys() {}

func (*MapMask_Int64DeleteKeys) isMapMask_DeleteKeys() {}

func (*MapMask_Uint32DeleteKeys) isMapMask_DeleteKeys() {}

func (*MapMask_Uint64DeleteKeys) isMapMask_DeleteKeys() {}

func (*MapMask_BoolDeleteKeys) isMapMask_DeleteKeys() {}

func (*MapMask_StringDeleteKeys) isMapMask_DeleteKeys() {}

type MapMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MapMessage) Reset() {
	*x = MapMessage{}
	mi := &file_fieldmask_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMessage) ProtoMessage() {}

func (x *MapMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMessage.ProtoReflect.Descriptor instead.
func (*MapMessage) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{8}
}

type MapMessage___Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MapMessage___Field) Reset() {
	*x = MapMessage___Field{}
	mi := &file_fieldmask_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapMessage___Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMessage___Field) ProtoMessage() {}

func (x *MapMessage___Field) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMessage___Field.ProtoReflect.Descriptor instead.
func (*MapMessage___Field) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{9}
}

type MapMessage_X struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Update uint64 `protobuf:"varint,1,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *MapMessage_X) Reset() {
	*x = MapMessage_X{}
	mi := &file_fieldmask_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapMessage_X) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMessage_X) ProtoMessage() {}

func (x *MapMessage_X) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMessage_X.ProtoReflect.Descriptor instead.
func (*MapMessage_X) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{8, 0}
}

func (x *MapMessage_X) GetUpdate() uint64 {
	if x != nil {
		return x.Update
	}
	return 0
}

var File_fieldmask_proto protoreflect.FileDescriptor

var file_fieldmask_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6b, 0x64, 0x73, 0x70, 0x62, 0x22, 0x7f, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x28, 0x0a,
	0x07, 0x4d, 0x61, 0x70, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6b, 0x64, 0x73, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x70, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x07,
	0x4d, 0x61, 0x70, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x30, 0x0a, 0x0a, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4d, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x64,
	0x73, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x0a, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x24, 0x0a, 0x0a, 0x49, 0x6e, 0x74,
	0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0x24, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x0b,
	0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08,
	0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0xad, 0x03, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x12, 0x3d, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6b, 0x64, 0x73,
	0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x48, 0x00, 0x52,
	0x0f, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x73,
	0x12, 0x3d, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6b, 0x64, 0x73, 0x70,
	0x62, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x48, 0x00, 0x52, 0x0f,
	0x49, 0x6e, 0x74, 0x36, 0x34, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x12,
	0x40, 0x0a, 0x10, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6b, 0x64, 0x73, 0x70,
	0x62, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x48, 0x00, 0x52,
	0x10, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x73, 0x12, 0x40, 0x0a, 0x10, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6b, 0x64,
	0x73, 0x70, 0x62, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x48,
	0x00, 0x52, 0x10, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x73, 0x12, 0x3a, 0x0a, 0x0e, 0x42, 0x6f, 0x6f, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x64,
	0x73, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79, 0x48, 0x00, 0x52,
	0x0e, 0x42, 0x6f, 0x6f, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x12,
	0x40, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6b, 0x64, 0x73, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x48, 0x00, 0x52,
	0x10, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x73, 0x42, 0x0c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x22,
	0x29, 0x0a, 0x0a, 0x4d, 0x61, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1b, 0x0a,
	0x01, 0x5f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x4d, 0x61,
	0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x5f, 0x5f, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x61, 0x6b, 0x75, 0x64, 0x2f, 0x6b, 0x64, 0x73, 0x2f, 0x6b, 0x64, 0x73, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fieldmask_proto_rawDescOnce sync.Once
	file_fieldmask_proto_rawDescData = file_fieldmask_proto_rawDesc
)

func file_fieldmask_proto_rawDescGZIP() []byte {
	file_fieldmask_proto_rawDescOnce.Do(func() {
		file_fieldmask_proto_rawDescData = protoimpl.X.CompressGZIP(file_fieldmask_proto_rawDescData)
	})
	return file_fieldmask_proto_rawDescData
}

var file_fieldmask_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_fieldmask_proto_goTypes = []any{
	(*FieldMask)(nil),          // 0: kdspb.FieldMask
	(*Int32Array)(nil),         // 1: kdspb.Int32Array
	(*Int64Array)(nil),         // 2: kdspb.Int64Array
	(*UInt32Array)(nil),        // 3: kdspb.UInt32Array
	(*Uint64Array)(nil),        // 4: kdspb.Uint64Array
	(*BoolArray)(nil),          // 5: kdspb.BoolArray
	(*StringArray)(nil),        // 6: kdspb.StringArray
	(*MapMask)(nil),            // 7: kdspb.MapMask
	(*MapMessage)(nil),         // 8: kdspb.MapMessage
	(*MapMessage___Field)(nil), // 9: kdspb.MapMessage___Field
	(*MapMessage_X)(nil),       // 10: kdspb.MapMessage._
}
var file_fieldmask_proto_depIdxs = []int32{
	7, // 0: kdspb.FieldMask.MapMask:type_name -> kdspb.MapMask
	0, // 1: kdspb.FieldMask.FieldMasks:type_name -> kdspb.FieldMask
	1, // 2: kdspb.MapMask.Int32DeleteKeys:type_name -> kdspb.Int32Array
	2, // 3: kdspb.MapMask.Int64DeleteKeys:type_name -> kdspb.Int64Array
	3, // 4: kdspb.MapMask.Uint32DeleteKeys:type_name -> kdspb.UInt32Array
	4, // 5: kdspb.MapMask.Uint64DeleteKeys:type_name -> kdspb.Uint64Array
	5, // 6: kdspb.MapMask.BoolDeleteKeys:type_name -> kdspb.BoolArray
	6, // 7: kdspb.MapMask.StringDeleteKeys:type_name -> kdspb.StringArray
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_fieldmask_proto_init() }
func file_fieldmask_proto_init() {
	if File_fieldmask_proto != nil {
		return
	}
	file_fieldmask_proto_msgTypes[7].OneofWrappers = []any{
		(*MapMask_Int32DeleteKeys)(nil),
		(*MapMask_Int64DeleteKeys)(nil),
		(*MapMask_Uint32DeleteKeys)(nil),
		(*MapMask_Uint64DeleteKeys)(nil),
		(*MapMask_BoolDeleteKeys)(nil),
		(*MapMask_StringDeleteKeys)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fieldmask_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fieldmask_proto_goTypes,
		DependencyIndexes: file_fieldmask_proto_depIdxs,
		MessageInfos:      file_fieldmask_proto_msgTypes,
	}.Build()
	File_fieldmask_proto = out.File
	file_fieldmask_proto_rawDesc = nil
	file_fieldmask_proto_goTypes = nil
	file_fieldmask_proto_depIdxs = nil
}
