// Code generated by kds. DO NOT EDIT.
// source: kds/common.kds

using System;
using System.Collections.Generic;
using System.Linq;
using System.Globalization;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;

namespace kds
{
	public class Bool_list : IList<bool>, ICollection<bool>, IEnumerable<bool>
	{
		private static readonly EqualityComparer<bool> EqualityComparer = Google.Protobuf.Collections.ProtobufEqualityComparers.GetEqualityComparer<bool>();

		private bool[] array = [];

		private int count = 0;

		public int Count => count;

		public bool IsReadOnly => false;

		public bool this[int index]
		{
			get
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				return array[index];
			}
			set
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				array[index] = value;
			}
		}

		private void EnsureSize(int size)
		{
			if (array.Length < size)
			{
				var newCapacity = array.Length == 0 ? 4 : array.Length * 2;
				if (newCapacity < size)
					newCapacity = size;
				var newData = new bool[newCapacity];
				Array.Copy(array, newData, count);
				array = newData;
			}
		}

		public void Add(bool item)
		{
			EnsureSize(count + 1);
			array[count++] = item;
		}

		public void Clear()
		{
			Array.Clear(array, 0, count);
			count = 0;
		}

		public bool Contains(bool item)
		{
			return IndexOf(item) != -1;
		}

		public void CopyTo(bool[] array, int arrayIndex)
		{
			Array.Copy(array, 0, array, arrayIndex, count);
		}

		public bool Remove(bool item)
		{
			var num = IndexOf(item);
			if (num == -1)
				return false;
			Array.Copy(array, num + 1, array, num, count - num - 1);
			count--;
			array[count] = default;
			return true;
		}

		public int IndexOf(bool item)
		{
			EqualityComparer<bool> equalityComparer = EqualityComparer;
			for (int i = 0; i < count; i++)
			{
				if (equalityComparer.Equals(array[i], item))
				{
					return i;
				}
			}
			return -1;
		}

		public void Insert(int index, bool item)
		{
			if (index < 0 || index > count)
				throw new ArgumentOutOfRangeException(nameof(index));
			EnsureSize(count + 1);
			Array.Copy(array, index, array, index + 1, count - index);
			array[index] = item;
			count++;
		}

		public void RemoveAt(int index)
		{
			if (index < 0 || index >= count)
				throw new ArgumentOutOfRangeException(nameof(index));
			Array.Copy(array, index + 1, array, index, count - index - 1);
			count--;
			array[count] = default;
		}

		public IEnumerator<bool> GetEnumerator()
		{
			for (int i = 0; i < count; i++)
			{
				yield return array[i];
			}
		}

		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

		public string ToString(string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			for (int i = 0; i < count; i++)
			{
				var v = array[i];
				sb.AppendLine(indent + "  " + v.ToString().ToLower());
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public void ApplySync(byte[] b)
		{
			Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				Add(stream.ReadBool());
			}
		}

		public void RaiseChanged()
		{

		}

		public void ClearChanged()
		{

		}
	}
	public class Double_list : IList<double>, ICollection<double>, IEnumerable<double>
	{
		private static readonly EqualityComparer<double> EqualityComparer = Google.Protobuf.Collections.ProtobufEqualityComparers.GetEqualityComparer<double>();

		private double[] array = [];

		private int count = 0;

		public int Count => count;

		public bool IsReadOnly => false;

		public double this[int index]
		{
			get
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				return array[index];
			}
			set
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				array[index] = value;
			}
		}

		private void EnsureSize(int size)
		{
			if (array.Length < size)
			{
				var newCapacity = array.Length == 0 ? 4 : array.Length * 2;
				if (newCapacity < size)
					newCapacity = size;
				var newData = new double[newCapacity];
				Array.Copy(array, newData, count);
				array = newData;
			}
		}

		public void Add(double item)
		{
			EnsureSize(count + 1);
			array[count++] = item;
		}

		public void Clear()
		{
			Array.Clear(array, 0, count);
			count = 0;
		}

		public bool Contains(double item)
		{
			return IndexOf(item) != -1;
		}

		public void CopyTo(double[] array, int arrayIndex)
		{
			Array.Copy(array, 0, array, arrayIndex, count);
		}

		public bool Remove(double item)
		{
			var num = IndexOf(item);
			if (num == -1)
				return false;
			Array.Copy(array, num + 1, array, num, count - num - 1);
			count--;
			array[count] = default;
			return true;
		}

		public int IndexOf(double item)
		{
			EqualityComparer<double> equalityComparer = EqualityComparer;
			for (int i = 0; i < count; i++)
			{
				if (equalityComparer.Equals(array[i], item))
				{
					return i;
				}
			}
			return -1;
		}

		public void Insert(int index, double item)
		{
			if (index < 0 || index > count)
				throw new ArgumentOutOfRangeException(nameof(index));
			EnsureSize(count + 1);
			Array.Copy(array, index, array, index + 1, count - index);
			array[index] = item;
			count++;
		}

		public void RemoveAt(int index)
		{
			if (index < 0 || index >= count)
				throw new ArgumentOutOfRangeException(nameof(index));
			Array.Copy(array, index + 1, array, index, count - index - 1);
			count--;
			array[count] = default;
		}

		public IEnumerator<double> GetEnumerator()
		{
			for (int i = 0; i < count; i++)
			{
				yield return array[i];
			}
		}

		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

		public string ToString(string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			for (int i = 0; i < count; i++)
			{
				var v = array[i];
				sb.AppendLine(indent + "  " + v.ToString(System.Globalization.CultureInfo.InvariantCulture));
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public void ApplySync(byte[] b)
		{
			Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				Add(stream.ReadDouble());
			}
		}

		public void RaiseChanged()
		{

		}

		public void ClearChanged()
		{

		}
	}
	public class Duration_list : IList<Duration>, ICollection<Duration>, IEnumerable<Duration>
	{
		private static readonly EqualityComparer<Duration> EqualityComparer = Google.Protobuf.Collections.ProtobufEqualityComparers.GetEqualityComparer<Duration>();

		private Duration[] array = [];

		private int count = 0;

		public int Count => count;

		public bool IsReadOnly => false;

		public Duration this[int index]
		{
			get
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				return array[index];
			}
			set
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				array[index] = value;
			}
		}

		private void EnsureSize(int size)
		{
			if (array.Length < size)
			{
				var newCapacity = array.Length == 0 ? 4 : array.Length * 2;
				if (newCapacity < size)
					newCapacity = size;
				var newData = new Duration[newCapacity];
				Array.Copy(array, newData, count);
				array = newData;
			}
		}

		public void Add(Duration item)
		{
			EnsureSize(count + 1);
			array[count++] = item;
		}

		public void Clear()
		{
			Array.Clear(array, 0, count);
			count = 0;
		}

		public bool Contains(Duration item)
		{
			return IndexOf(item) != -1;
		}

		public void CopyTo(Duration[] array, int arrayIndex)
		{
			Array.Copy(array, 0, array, arrayIndex, count);
		}

		public bool Remove(Duration item)
		{
			var num = IndexOf(item);
			if (num == -1)
				return false;
			Array.Copy(array, num + 1, array, num, count - num - 1);
			count--;
			array[count] = default;
			return true;
		}

		public int IndexOf(Duration item)
		{
			EqualityComparer<Duration> equalityComparer = EqualityComparer;
			for (int i = 0; i < count; i++)
			{
				if (equalityComparer.Equals(array[i], item))
				{
					return i;
				}
			}
			return -1;
		}

		public void Insert(int index, Duration item)
		{
			if (index < 0 || index > count)
				throw new ArgumentOutOfRangeException(nameof(index));
			EnsureSize(count + 1);
			Array.Copy(array, index, array, index + 1, count - index);
			array[index] = item;
			count++;
		}

		public void RemoveAt(int index)
		{
			if (index < 0 || index >= count)
				throw new ArgumentOutOfRangeException(nameof(index));
			Array.Copy(array, index + 1, array, index, count - index - 1);
			count--;
			array[count] = default;
		}

		public IEnumerator<Duration> GetEnumerator()
		{
			for (int i = 0; i < count; i++)
			{
				yield return array[i];
			}
		}

		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

		public string ToString(string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			for (int i = 0; i < count; i++)
			{
				var v = array[i];
				sb.AppendLine(indent + "  {Seconds: " + v.Seconds + ", Nanos: " + v.Nanos + "}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public void ApplySync(byte[] b)
		{
			Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				Add(Duration.Parser.ParseFrom(stream.ReadBytes().ToByteArray()));
			}
		}

		public void RaiseChanged()
		{

		}

		public void ClearChanged()
		{

		}
	}
	public static class BoolDuration_map
	{
		public static string ToString(Dictionary<bool, Duration> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort((a, b) => {
				if (a) return b ? 0 : 1;
				return b ? -1 : 0;
			});
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString().ToLower();
				sb.AppendLine(indent + "  " + key + " = {Seconds: " + v.Seconds + ", Nanos: " + v.Nanos + "}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<bool, Duration> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadBool());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				bool k = default;
				Duration v = new Duration();
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadBool();
						break;
					case 2: // MapEntryValueFieldNumber
						v = Duration.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<bool, Duration> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<bool, Duration> data)
		{
			// FIXME:
		}
	}
	public static class Int32Duration_map
	{
		public static string ToString(Dictionary<int, Duration> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = {Seconds: " + v.Seconds + ", Nanos: " + v.Nanos + "}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<int, Duration> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt32());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				int k = default;
				Duration v = new Duration();
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt32();
						break;
					case 2: // MapEntryValueFieldNumber
						v = Duration.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<int, Duration> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<int, Duration> data)
		{
			// FIXME:
		}
	}
	public static class Int64Duration_map
	{
		public static string ToString(Dictionary<long, Duration> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = {Seconds: " + v.Seconds + ", Nanos: " + v.Nanos + "}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<long, Duration> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt64());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				long k = default;
				Duration v = new Duration();
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt64();
						break;
					case 2: // MapEntryValueFieldNumber
						v = Duration.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<long, Duration> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<long, Duration> data)
		{
			// FIXME:
		}
	}
	public static class StringDuration_map
	{
		public static string ToString(Dictionary<string, Duration> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = {Seconds: " + v.Seconds + ", Nanos: " + v.Nanos + "}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<string, Duration> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadString());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				string k = string.Empty;
				Duration v = new Duration();
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadString();
						break;
					case 2: // MapEntryValueFieldNumber
						v = Duration.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<string, Duration> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<string, Duration> data)
		{
			// FIXME:
		}
	}
	public class Empty_list : IList<Empty>, ICollection<Empty>, IEnumerable<Empty>
	{
		private static readonly EqualityComparer<Empty> EqualityComparer = Google.Protobuf.Collections.ProtobufEqualityComparers.GetEqualityComparer<Empty>();

		private Empty[] array = [];

		private int count = 0;

		public int Count => count;

		public bool IsReadOnly => false;

		public Empty this[int index]
		{
			get
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				return array[index];
			}
			set
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				array[index] = value;
			}
		}

		private void EnsureSize(int size)
		{
			if (array.Length < size)
			{
				var newCapacity = array.Length == 0 ? 4 : array.Length * 2;
				if (newCapacity < size)
					newCapacity = size;
				var newData = new Empty[newCapacity];
				Array.Copy(array, newData, count);
				array = newData;
			}
		}

		public void Add(Empty item)
		{
			EnsureSize(count + 1);
			array[count++] = item;
		}

		public void Clear()
		{
			Array.Clear(array, 0, count);
			count = 0;
		}

		public bool Contains(Empty item)
		{
			return IndexOf(item) != -1;
		}

		public void CopyTo(Empty[] array, int arrayIndex)
		{
			Array.Copy(array, 0, array, arrayIndex, count);
		}

		public bool Remove(Empty item)
		{
			var num = IndexOf(item);
			if (num == -1)
				return false;
			Array.Copy(array, num + 1, array, num, count - num - 1);
			count--;
			array[count] = default;
			return true;
		}

		public int IndexOf(Empty item)
		{
			EqualityComparer<Empty> equalityComparer = EqualityComparer;
			for (int i = 0; i < count; i++)
			{
				if (equalityComparer.Equals(array[i], item))
				{
					return i;
				}
			}
			return -1;
		}

		public void Insert(int index, Empty item)
		{
			if (index < 0 || index > count)
				throw new ArgumentOutOfRangeException(nameof(index));
			EnsureSize(count + 1);
			Array.Copy(array, index, array, index + 1, count - index);
			array[index] = item;
			count++;
		}

		public void RemoveAt(int index)
		{
			if (index < 0 || index >= count)
				throw new ArgumentOutOfRangeException(nameof(index));
			Array.Copy(array, index + 1, array, index, count - index - 1);
			count--;
			array[count] = default;
		}

		public IEnumerator<Empty> GetEnumerator()
		{
			for (int i = 0; i < count; i++)
			{
				yield return array[i];
			}
		}

		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

		public string ToString(string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			for (int i = 0; i < count; i++)
			{
				var v = array[i];
				sb.AppendLine(indent + "  {}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public void ApplySync(byte[] b)
		{
			Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				Add(Empty.Parser.ParseFrom(stream.ReadBytes().ToByteArray()));
			}
		}

		public void RaiseChanged()
		{

		}

		public void ClearChanged()
		{

		}
	}
	public static class BoolEmpty_map
	{
		public static string ToString(Dictionary<bool, Empty> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort((a, b) => {
				if (a) return b ? 0 : 1;
				return b ? -1 : 0;
			});
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString().ToLower();
				sb.AppendLine(indent + "  " + key + " = {}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<bool, Empty> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadBool());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				bool k = default;
				Empty v = new Empty();
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadBool();
						break;
					case 2: // MapEntryValueFieldNumber
						v = Empty.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<bool, Empty> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<bool, Empty> data)
		{
			// FIXME:
		}
	}
	public static class Int32Empty_map
	{
		public static string ToString(Dictionary<int, Empty> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = {}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<int, Empty> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt32());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				int k = default;
				Empty v = new Empty();
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt32();
						break;
					case 2: // MapEntryValueFieldNumber
						v = Empty.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<int, Empty> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<int, Empty> data)
		{
			// FIXME:
		}
	}
	public static class Int64Empty_map
	{
		public static string ToString(Dictionary<long, Empty> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = {}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<long, Empty> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt64());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				long k = default;
				Empty v = new Empty();
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt64();
						break;
					case 2: // MapEntryValueFieldNumber
						v = Empty.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<long, Empty> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<long, Empty> data)
		{
			// FIXME:
		}
	}
	public static class StringEmpty_map
	{
		public static string ToString(Dictionary<string, Empty> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = {}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<string, Empty> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadString());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				string k = string.Empty;
				Empty v = new Empty();
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadString();
						break;
					case 2: // MapEntryValueFieldNumber
						v = Empty.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<string, Empty> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<string, Empty> data)
		{
			// FIXME:
		}
	}
	public class Float_list : IList<float>, ICollection<float>, IEnumerable<float>
	{
		private static readonly EqualityComparer<float> EqualityComparer = Google.Protobuf.Collections.ProtobufEqualityComparers.GetEqualityComparer<float>();

		private float[] array = [];

		private int count = 0;

		public int Count => count;

		public bool IsReadOnly => false;

		public float this[int index]
		{
			get
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				return array[index];
			}
			set
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				array[index] = value;
			}
		}

		private void EnsureSize(int size)
		{
			if (array.Length < size)
			{
				var newCapacity = array.Length == 0 ? 4 : array.Length * 2;
				if (newCapacity < size)
					newCapacity = size;
				var newData = new float[newCapacity];
				Array.Copy(array, newData, count);
				array = newData;
			}
		}

		public void Add(float item)
		{
			EnsureSize(count + 1);
			array[count++] = item;
		}

		public void Clear()
		{
			Array.Clear(array, 0, count);
			count = 0;
		}

		public bool Contains(float item)
		{
			return IndexOf(item) != -1;
		}

		public void CopyTo(float[] array, int arrayIndex)
		{
			Array.Copy(array, 0, array, arrayIndex, count);
		}

		public bool Remove(float item)
		{
			var num = IndexOf(item);
			if (num == -1)
				return false;
			Array.Copy(array, num + 1, array, num, count - num - 1);
			count--;
			array[count] = default;
			return true;
		}

		public int IndexOf(float item)
		{
			EqualityComparer<float> equalityComparer = EqualityComparer;
			for (int i = 0; i < count; i++)
			{
				if (equalityComparer.Equals(array[i], item))
				{
					return i;
				}
			}
			return -1;
		}

		public void Insert(int index, float item)
		{
			if (index < 0 || index > count)
				throw new ArgumentOutOfRangeException(nameof(index));
			EnsureSize(count + 1);
			Array.Copy(array, index, array, index + 1, count - index);
			array[index] = item;
			count++;
		}

		public void RemoveAt(int index)
		{
			if (index < 0 || index >= count)
				throw new ArgumentOutOfRangeException(nameof(index));
			Array.Copy(array, index + 1, array, index, count - index - 1);
			count--;
			array[count] = default;
		}

		public IEnumerator<float> GetEnumerator()
		{
			for (int i = 0; i < count; i++)
			{
				yield return array[i];
			}
		}

		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

		public string ToString(string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			for (int i = 0; i < count; i++)
			{
				var v = array[i];
				sb.AppendLine(indent + "  " + v.ToString(System.Globalization.CultureInfo.InvariantCulture));
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public void ApplySync(byte[] b)
		{
			Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				Add(stream.ReadFloat());
			}
		}

		public void RaiseChanged()
		{

		}

		public void ClearChanged()
		{

		}
	}
	public class Int32_list : IList<int>, ICollection<int>, IEnumerable<int>
	{
		private static readonly EqualityComparer<int> EqualityComparer = Google.Protobuf.Collections.ProtobufEqualityComparers.GetEqualityComparer<int>();

		private int[] array = [];

		private int count = 0;

		public int Count => count;

		public bool IsReadOnly => false;

		public int this[int index]
		{
			get
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				return array[index];
			}
			set
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				array[index] = value;
			}
		}

		private void EnsureSize(int size)
		{
			if (array.Length < size)
			{
				var newCapacity = array.Length == 0 ? 4 : array.Length * 2;
				if (newCapacity < size)
					newCapacity = size;
				var newData = new int[newCapacity];
				Array.Copy(array, newData, count);
				array = newData;
			}
		}

		public void Add(int item)
		{
			EnsureSize(count + 1);
			array[count++] = item;
		}

		public void Clear()
		{
			Array.Clear(array, 0, count);
			count = 0;
		}

		public bool Contains(int item)
		{
			return IndexOf(item) != -1;
		}

		public void CopyTo(int[] array, int arrayIndex)
		{
			Array.Copy(array, 0, array, arrayIndex, count);
		}

		public bool Remove(int item)
		{
			var num = IndexOf(item);
			if (num == -1)
				return false;
			Array.Copy(array, num + 1, array, num, count - num - 1);
			count--;
			array[count] = default;
			return true;
		}

		public int IndexOf(int item)
		{
			EqualityComparer<int> equalityComparer = EqualityComparer;
			for (int i = 0; i < count; i++)
			{
				if (equalityComparer.Equals(array[i], item))
				{
					return i;
				}
			}
			return -1;
		}

		public void Insert(int index, int item)
		{
			if (index < 0 || index > count)
				throw new ArgumentOutOfRangeException(nameof(index));
			EnsureSize(count + 1);
			Array.Copy(array, index, array, index + 1, count - index);
			array[index] = item;
			count++;
		}

		public void RemoveAt(int index)
		{
			if (index < 0 || index >= count)
				throw new ArgumentOutOfRangeException(nameof(index));
			Array.Copy(array, index + 1, array, index, count - index - 1);
			count--;
			array[count] = default;
		}

		public IEnumerator<int> GetEnumerator()
		{
			for (int i = 0; i < count; i++)
			{
				yield return array[i];
			}
		}

		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

		public string ToString(string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			for (int i = 0; i < count; i++)
			{
				var v = array[i];
				sb.AppendLine(indent + "  " + v.ToString());
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public void ApplySync(byte[] b)
		{
			Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				Add(stream.ReadInt32());
			}
		}

		public void RaiseChanged()
		{

		}

		public void ClearChanged()
		{

		}
	}
	public static class BoolInt32_map
	{
		public static string ToString(Dictionary<bool, int> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort((a, b) => {
				if (a) return b ? 0 : 1;
				return b ? -1 : 0;
			});
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString().ToLower();
				sb.AppendLine(indent + "  " + key + " = " + v.ToString());
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<bool, int> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadBool());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				bool k = default;
				int v = default;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadBool();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadInt32();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<bool, int> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<bool, int> data)
		{
			// FIXME:
		}
	}
	public static class Int32Int32_map
	{
		public static string ToString(Dictionary<int, int> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = " + v.ToString());
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<int, int> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt32());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				int k = default;
				int v = default;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt32();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadInt32();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<int, int> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<int, int> data)
		{
			// FIXME:
		}
	}
	public static class StringInt32_map
	{
		public static string ToString(Dictionary<string, int> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = " + v.ToString());
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<string, int> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadString());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				string k = string.Empty;
				int v = default;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadString();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadInt32();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<string, int> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<string, int> data)
		{
			// FIXME:
		}
	}
	public class Int64_list : IList<long>, ICollection<long>, IEnumerable<long>
	{
		private static readonly EqualityComparer<long> EqualityComparer = Google.Protobuf.Collections.ProtobufEqualityComparers.GetEqualityComparer<long>();

		private long[] array = [];

		private int count = 0;

		public int Count => count;

		public bool IsReadOnly => false;

		public long this[int index]
		{
			get
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				return array[index];
			}
			set
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				array[index] = value;
			}
		}

		private void EnsureSize(int size)
		{
			if (array.Length < size)
			{
				var newCapacity = array.Length == 0 ? 4 : array.Length * 2;
				if (newCapacity < size)
					newCapacity = size;
				var newData = new long[newCapacity];
				Array.Copy(array, newData, count);
				array = newData;
			}
		}

		public void Add(long item)
		{
			EnsureSize(count + 1);
			array[count++] = item;
		}

		public void Clear()
		{
			Array.Clear(array, 0, count);
			count = 0;
		}

		public bool Contains(long item)
		{
			return IndexOf(item) != -1;
		}

		public void CopyTo(long[] array, int arrayIndex)
		{
			Array.Copy(array, 0, array, arrayIndex, count);
		}

		public bool Remove(long item)
		{
			var num = IndexOf(item);
			if (num == -1)
				return false;
			Array.Copy(array, num + 1, array, num, count - num - 1);
			count--;
			array[count] = default;
			return true;
		}

		public int IndexOf(long item)
		{
			EqualityComparer<long> equalityComparer = EqualityComparer;
			for (int i = 0; i < count; i++)
			{
				if (equalityComparer.Equals(array[i], item))
				{
					return i;
				}
			}
			return -1;
		}

		public void Insert(int index, long item)
		{
			if (index < 0 || index > count)
				throw new ArgumentOutOfRangeException(nameof(index));
			EnsureSize(count + 1);
			Array.Copy(array, index, array, index + 1, count - index);
			array[index] = item;
			count++;
		}

		public void RemoveAt(int index)
		{
			if (index < 0 || index >= count)
				throw new ArgumentOutOfRangeException(nameof(index));
			Array.Copy(array, index + 1, array, index, count - index - 1);
			count--;
			array[count] = default;
		}

		public IEnumerator<long> GetEnumerator()
		{
			for (int i = 0; i < count; i++)
			{
				yield return array[i];
			}
		}

		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

		public string ToString(string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			for (int i = 0; i < count; i++)
			{
				var v = array[i];
				sb.AppendLine(indent + "  " + v.ToString());
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public void ApplySync(byte[] b)
		{
			Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				Add(stream.ReadInt64());
			}
		}

		public void RaiseChanged()
		{

		}

		public void ClearChanged()
		{

		}
	}
	public static class Int64Int64_map
	{
		public static string ToString(Dictionary<long, long> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = " + v.ToString());
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<long, long> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt64());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				long k = default;
				long v = default;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt64();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadInt64();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<long, long> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<long, long> data)
		{
			// FIXME:
		}
	}
	public class String_list : IList<string>, ICollection<string>, IEnumerable<string>
	{
		private static readonly EqualityComparer<string> EqualityComparer = Google.Protobuf.Collections.ProtobufEqualityComparers.GetEqualityComparer<string>();

		private string[] array = [];

		private int count = 0;

		public int Count => count;

		public bool IsReadOnly => false;

		public string this[int index]
		{
			get
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				return array[index];
			}
			set
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				array[index] = value;
			}
		}

		private void EnsureSize(int size)
		{
			if (array.Length < size)
			{
				var newCapacity = array.Length == 0 ? 4 : array.Length * 2;
				if (newCapacity < size)
					newCapacity = size;
				var newData = new string[newCapacity];
				Array.Copy(array, newData, count);
				array = newData;
			}
		}

		public void Add(string item)
		{
			EnsureSize(count + 1);
			array[count++] = item;
		}

		public void Clear()
		{
			Array.Clear(array, 0, count);
			count = 0;
		}

		public bool Contains(string item)
		{
			return IndexOf(item) != -1;
		}

		public void CopyTo(string[] array, int arrayIndex)
		{
			Array.Copy(array, 0, array, arrayIndex, count);
		}

		public bool Remove(string item)
		{
			var num = IndexOf(item);
			if (num == -1)
				return false;
			Array.Copy(array, num + 1, array, num, count - num - 1);
			count--;
			array[count] = default;
			return true;
		}

		public int IndexOf(string item)
		{
			EqualityComparer<string> equalityComparer = EqualityComparer;
			for (int i = 0; i < count; i++)
			{
				if (equalityComparer.Equals(array[i], item))
				{
					return i;
				}
			}
			return -1;
		}

		public void Insert(int index, string item)
		{
			if (index < 0 || index > count)
				throw new ArgumentOutOfRangeException(nameof(index));
			EnsureSize(count + 1);
			Array.Copy(array, index, array, index + 1, count - index);
			array[index] = item;
			count++;
		}

		public void RemoveAt(int index)
		{
			if (index < 0 || index >= count)
				throw new ArgumentOutOfRangeException(nameof(index));
			Array.Copy(array, index + 1, array, index, count - index - 1);
			count--;
			array[count] = default;
		}

		public IEnumerator<string> GetEnumerator()
		{
			for (int i = 0; i < count; i++)
			{
				yield return array[i];
			}
		}

		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

		public string ToString(string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			for (int i = 0; i < count; i++)
			{
				var v = array[i];
				sb.AppendLine(indent + "  " + v);
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public void ApplySync(byte[] b)
		{
			Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				Add(stream.ReadString());
			}
		}

		public void RaiseChanged()
		{

		}

		public void ClearChanged()
		{

		}
	}
	public static class BoolString_map
	{
		public static string ToString(Dictionary<bool, string> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort((a, b) => {
				if (a) return b ? 0 : 1;
				return b ? -1 : 0;
			});
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString().ToLower();
				sb.AppendLine(indent + "  " + key + " = " + v);
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<bool, string> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadBool());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				bool k = default;
				string v = string.Empty;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadBool();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadString();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<bool, string> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<bool, string> data)
		{
			// FIXME:
		}
	}
	public static class Int32String_map
	{
		public static string ToString(Dictionary<int, string> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = " + v);
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<int, string> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt32());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				int k = default;
				string v = string.Empty;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt32();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadString();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<int, string> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<int, string> data)
		{
			// FIXME:
		}
	}
	public static class Int64String_map
	{
		public static string ToString(Dictionary<long, string> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = " + v);
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<long, string> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt64());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				long k = default;
				string v = string.Empty;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt64();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadString();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<long, string> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<long, string> data)
		{
			// FIXME:
		}
	}
	public static class StringString_map
	{
		public static string ToString(Dictionary<string, string> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = " + v);
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<string, string> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadString());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				string k = string.Empty;
				string v = string.Empty;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadString();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadString();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<string, string> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<string, string> data)
		{
			// FIXME:
		}
	}
	public class Timestamp_list : IList<Timestamp>, ICollection<Timestamp>, IEnumerable<Timestamp>
	{
		private static readonly EqualityComparer<Timestamp> EqualityComparer = Google.Protobuf.Collections.ProtobufEqualityComparers.GetEqualityComparer<Timestamp>();

		private Timestamp[] array = [];

		private int count = 0;

		public int Count => count;

		public bool IsReadOnly => false;

		public Timestamp this[int index]
		{
			get
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				return array[index];
			}
			set
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				array[index] = value;
			}
		}

		private void EnsureSize(int size)
		{
			if (array.Length < size)
			{
				var newCapacity = array.Length == 0 ? 4 : array.Length * 2;
				if (newCapacity < size)
					newCapacity = size;
				var newData = new Timestamp[newCapacity];
				Array.Copy(array, newData, count);
				array = newData;
			}
		}

		public void Add(Timestamp item)
		{
			EnsureSize(count + 1);
			array[count++] = item;
		}

		public void Clear()
		{
			Array.Clear(array, 0, count);
			count = 0;
		}

		public bool Contains(Timestamp item)
		{
			return IndexOf(item) != -1;
		}

		public void CopyTo(Timestamp[] array, int arrayIndex)
		{
			Array.Copy(array, 0, array, arrayIndex, count);
		}

		public bool Remove(Timestamp item)
		{
			var num = IndexOf(item);
			if (num == -1)
				return false;
			Array.Copy(array, num + 1, array, num, count - num - 1);
			count--;
			array[count] = default;
			return true;
		}

		public int IndexOf(Timestamp item)
		{
			EqualityComparer<Timestamp> equalityComparer = EqualityComparer;
			for (int i = 0; i < count; i++)
			{
				if (equalityComparer.Equals(array[i], item))
				{
					return i;
				}
			}
			return -1;
		}

		public void Insert(int index, Timestamp item)
		{
			if (index < 0 || index > count)
				throw new ArgumentOutOfRangeException(nameof(index));
			EnsureSize(count + 1);
			Array.Copy(array, index, array, index + 1, count - index);
			array[index] = item;
			count++;
		}

		public void RemoveAt(int index)
		{
			if (index < 0 || index >= count)
				throw new ArgumentOutOfRangeException(nameof(index));
			Array.Copy(array, index + 1, array, index, count - index - 1);
			count--;
			array[count] = default;
		}

		public IEnumerator<Timestamp> GetEnumerator()
		{
			for (int i = 0; i < count; i++)
			{
				yield return array[i];
			}
		}

		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

		public string ToString(string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			for (int i = 0; i < count; i++)
			{
				var v = array[i];
				sb.AppendLine(indent + "  {Seconds: " + v.Seconds + ", Nanos: " + v.Nanos + "}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public void ApplySync(byte[] b)
		{
			Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				Add(Timestamp.Parser.ParseFrom(stream.ReadBytes().ToByteArray()));
			}
		}

		public void RaiseChanged()
		{

		}

		public void ClearChanged()
		{

		}
	}
	public static class BoolTimestamp_map
	{
		public static string ToString(Dictionary<bool, Timestamp> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort((a, b) => {
				if (a) return b ? 0 : 1;
				return b ? -1 : 0;
			});
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString().ToLower();
				sb.AppendLine(indent + "  " + key + " = {Seconds: " + v.Seconds + ", Nanos: " + v.Nanos + "}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<bool, Timestamp> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadBool());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				bool k = default;
				Timestamp v = new Timestamp();
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadBool();
						break;
					case 2: // MapEntryValueFieldNumber
						v = Timestamp.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<bool, Timestamp> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<bool, Timestamp> data)
		{
			// FIXME:
		}
	}
	public static class Int32Timestamp_map
	{
		public static string ToString(Dictionary<int, Timestamp> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = {Seconds: " + v.Seconds + ", Nanos: " + v.Nanos + "}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<int, Timestamp> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt32());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				int k = default;
				Timestamp v = new Timestamp();
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt32();
						break;
					case 2: // MapEntryValueFieldNumber
						v = Timestamp.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<int, Timestamp> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<int, Timestamp> data)
		{
			// FIXME:
		}
	}
	public static class Int64Timestamp_map
	{
		public static string ToString(Dictionary<long, Timestamp> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = {Seconds: " + v.Seconds + ", Nanos: " + v.Nanos + "}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<long, Timestamp> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt64());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				long k = default;
				Timestamp v = new Timestamp();
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt64();
						break;
					case 2: // MapEntryValueFieldNumber
						v = Timestamp.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<long, Timestamp> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<long, Timestamp> data)
		{
			// FIXME:
		}
	}
	public static class StringTimestamp_map
	{
		public static string ToString(Dictionary<string, Timestamp> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = {Seconds: " + v.Seconds + ", Nanos: " + v.Nanos + "}");
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<string, Timestamp> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadString());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				string k = string.Empty;
				Timestamp v = new Timestamp();
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadString();
						break;
					case 2: // MapEntryValueFieldNumber
						v = Timestamp.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<string, Timestamp> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<string, Timestamp> data)
		{
			// FIXME:
		}
	}
	public enum ItemType
	{
		ItemTypeNone = 0,
		ItemTypeWeapon = 1,
		ItemTypeArmor = 2,
		ItemTypePotion = 3,
	}

	public class ItemType_list : IList<ItemType>, ICollection<ItemType>, IEnumerable<ItemType>
	{
		private static readonly EqualityComparer<ItemType> EqualityComparer = Google.Protobuf.Collections.ProtobufEqualityComparers.GetEqualityComparer<ItemType>();

		private ItemType[] array = [];

		private int count = 0;

		public int Count => count;

		public bool IsReadOnly => false;

		public ItemType this[int index]
		{
			get
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				return array[index];
			}
			set
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				array[index] = value;
			}
		}

		private void EnsureSize(int size)
		{
			if (array.Length < size)
			{
				var newCapacity = array.Length == 0 ? 4 : array.Length * 2;
				if (newCapacity < size)
					newCapacity = size;
				var newData = new ItemType[newCapacity];
				Array.Copy(array, newData, count);
				array = newData;
			}
		}

		public void Add(ItemType item)
		{
			EnsureSize(count + 1);
			array[count++] = item;
		}

		public void Clear()
		{
			Array.Clear(array, 0, count);
			count = 0;
		}

		public bool Contains(ItemType item)
		{
			return IndexOf(item) != -1;
		}

		public void CopyTo(ItemType[] array, int arrayIndex)
		{
			Array.Copy(array, 0, array, arrayIndex, count);
		}

		public bool Remove(ItemType item)
		{
			var num = IndexOf(item);
			if (num == -1)
				return false;
			Array.Copy(array, num + 1, array, num, count - num - 1);
			count--;
			array[count] = default;
			return true;
		}

		public int IndexOf(ItemType item)
		{
			EqualityComparer<ItemType> equalityComparer = EqualityComparer;
			for (int i = 0; i < count; i++)
			{
				if (equalityComparer.Equals(array[i], item))
				{
					return i;
				}
			}
			return -1;
		}

		public void Insert(int index, ItemType item)
		{
			if (index < 0 || index > count)
				throw new ArgumentOutOfRangeException(nameof(index));
			EnsureSize(count + 1);
			Array.Copy(array, index, array, index + 1, count - index);
			array[index] = item;
			count++;
		}

		public void RemoveAt(int index)
		{
			if (index < 0 || index >= count)
				throw new ArgumentOutOfRangeException(nameof(index));
			Array.Copy(array, index + 1, array, index, count - index - 1);
			count--;
			array[count] = default;
		}

		public IEnumerator<ItemType> GetEnumerator()
		{
			for (int i = 0; i < count; i++)
			{
				yield return array[i];
			}
		}

		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

		public string ToString(string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			for (int i = 0; i < count; i++)
			{
				var v = array[i];
				sb.AppendLine(indent + "  " + ((int)v).ToString());
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public void ApplySync(byte[] b)
		{
			Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				Add((ItemType)stream.ReadEnum());
			}
		}

		public void RaiseChanged()
		{

		}

		public void ClearChanged()
		{

		}
	}

	public static class BoolItemType_map
	{
		public static string ToString(Dictionary<bool, ItemType> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort((a, b) => {
				if (a) return b ? 0 : 1;
				return b ? -1 : 0;
			});
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString().ToLower();
				sb.AppendLine(indent + "  " + key + " = " + ((int)v).ToString());
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<bool, ItemType> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadBool());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				bool k = default;
				ItemType v = default;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadBool();
						break;
					case 2: // MapEntryValueFieldNumber
						v = (ItemType)stream.ReadEnum();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<bool, ItemType> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<bool, ItemType> data)
		{
			// FIXME:
		}
	}

	public static class Int32ItemType_map
	{
		public static string ToString(Dictionary<int, ItemType> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = " + ((int)v).ToString());
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<int, ItemType> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt32());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				int k = default;
				ItemType v = default;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt32();
						break;
					case 2: // MapEntryValueFieldNumber
						v = (ItemType)stream.ReadEnum();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<int, ItemType> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<int, ItemType> data)
		{
			// FIXME:
		}
	}

	public static class Int64ItemType_map
	{
		public static string ToString(Dictionary<long, ItemType> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = " + ((int)v).ToString());
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<long, ItemType> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt64());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				long k = default;
				ItemType v = default;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt64();
						break;
					case 2: // MapEntryValueFieldNumber
						v = (ItemType)stream.ReadEnum();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<long, ItemType> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<long, ItemType> data)
		{
			// FIXME:
		}
	}

	public static class StringItemType_map
	{
		public static string ToString(Dictionary<string, ItemType> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = " + ((int)v).ToString());
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<string, ItemType> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadString());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				string k = string.Empty;
				ItemType v = default;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadString();
						break;
					case 2: // MapEntryValueFieldNumber
						v = (ItemType)stream.ReadEnum();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				data[k] = v;
			}
		}

		public static void RaiseChanged(Dictionary<string, ItemType> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<string, ItemType> data)
		{
			// FIXME:
		}
	}
	public class ItemData
	{
		public ItemData()
		{
			name_ = string.Empty;
		}

		private int id_;
		public int Id => id_;

		private string name_;
		public string Name => name_;

		private int count_;
		public int Count => count_;

		private long _changed;

		public event Action<ItemData, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Id => (_changed & (0x01 << 1)) != 0;
			public bool Name => (_changed & (0x01 << 2)) != 0;
			public bool Count => (_changed & (0x01 << 3)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public string ToString(string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("{\n");
			sb.AppendLine(indent + "  Id = " + id_.ToString());
			sb.AppendLine(indent + "  Name = " + name_);
			sb.AppendLine(indent + "  Count = " + count_.ToString());
			sb.Append(indent + "}");
			return sb.ToString();
		}

		public void ApplySync(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					id_ = stream.ReadInt32();
					_changed |= 0x01 << 1;
					break;
				case 2:
					name_ = stream.ReadString();
					_changed |= 0x01 << 2;
					break;
				case 3:
					count_ = stream.ReadInt32();
					_changed |= 0x01 << 3;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			_changed = 0;
		}
	}

	public class ItemData_list : IList<ItemData>, ICollection<ItemData>, IEnumerable<ItemData>
	{
		private static readonly EqualityComparer<ItemData> EqualityComparer = Google.Protobuf.Collections.ProtobufEqualityComparers.GetEqualityComparer<ItemData>();

		private ItemData[] array = [];

		private int count = 0;

		public int Count => count;

		public bool IsReadOnly => false;

		public ItemData this[int index]
		{
			get
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				return array[index];
			}
			set
			{
				if (index < 0 || index >= count)
					throw new ArgumentOutOfRangeException(nameof(index));
				array[index] = value;
			}
		}

		private void EnsureSize(int size)
		{
			if (array.Length < size)
			{
				var newCapacity = array.Length == 0 ? 4 : array.Length * 2;
				if (newCapacity < size)
					newCapacity = size;
				var newData = new ItemData[newCapacity];
				Array.Copy(array, newData, count);
				array = newData;
			}
		}

		public void Add(ItemData item)
		{
			EnsureSize(count + 1);
			array[count++] = item;
		}

		public void Clear()
		{
			Array.Clear(array, 0, count);
			count = 0;
		}

		public bool Contains(ItemData item)
		{
			return IndexOf(item) != -1;
		}

		public void CopyTo(ItemData[] array, int arrayIndex)
		{
			Array.Copy(array, 0, array, arrayIndex, count);
		}

		public bool Remove(ItemData item)
		{
			var num = IndexOf(item);
			if (num == -1)
				return false;
			Array.Copy(array, num + 1, array, num, count - num - 1);
			count--;
			array[count] = default;
			return true;
		}

		public int IndexOf(ItemData item)
		{
			EqualityComparer<ItemData> equalityComparer = EqualityComparer;
			for (int i = 0; i < count; i++)
			{
				if (equalityComparer.Equals(array[i], item))
				{
					return i;
				}
			}
			return -1;
		}

		public void Insert(int index, ItemData item)
		{
			if (index < 0 || index > count)
				throw new ArgumentOutOfRangeException(nameof(index));
			EnsureSize(count + 1);
			Array.Copy(array, index, array, index + 1, count - index);
			array[index] = item;
			count++;
		}

		public void RemoveAt(int index)
		{
			if (index < 0 || index >= count)
				throw new ArgumentOutOfRangeException(nameof(index));
			Array.Copy(array, index + 1, array, index, count - index - 1);
			count--;
			array[count] = default;
		}

		public IEnumerator<ItemData> GetEnumerator()
		{
			for (int i = 0; i < count; i++)
			{
				yield return array[i];
			}
		}

		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

		public string ToString(string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			for (int i = 0; i < count; i++)
			{
				var v = array[i];
				sb.AppendLine(indent + "  " + v.ToString(indent + "  "));
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public void ApplySync(byte[] b)
		{
			Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				var v = new ItemData();
				v.ApplySync(stream.ReadBytes().ToByteArray());
				Add(v);
			}
		}

		public void RaiseChanged()
		{

		}

		public void ClearChanged()
		{

		}
	}

	public static class BoolItemData_map
	{
		public static string ToString(Dictionary<bool, ItemData> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort((a, b) => {
				if (a) return b ? 0 : 1;
				return b ? -1 : 0;
			});
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString().ToLower();
				sb.AppendLine(indent + "  " + key + " = " + v.ToString(indent + "  "));
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<bool, ItemData> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadBool());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				bool k = default;
				byte[] v = [];
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadBool();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadBytes().ToByteArray();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				if (data.TryGetValue(k, out var c))
				{
					c.ApplySync(v);	
				}
				else
				{
					c = new ItemData();
					c.ApplySync(v);
					data[k] = c;
				}
			}
		}

		public static void RaiseChanged(Dictionary<bool, ItemData> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<bool, ItemData> data)
		{
			// FIXME:
		}
	}

	public static class Int32ItemData_map
	{
		public static string ToString(Dictionary<int, ItemData> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = " + v.ToString(indent + "  "));
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<int, ItemData> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt32());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				int k = default;
				byte[] v = [];
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt32();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadBytes().ToByteArray();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				if (data.TryGetValue(k, out var c))
				{
					c.ApplySync(v);	
				}
				else
				{
					c = new ItemData();
					c.ApplySync(v);
					data[k] = c;
				}
			}
		}

		public static void RaiseChanged(Dictionary<int, ItemData> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<int, ItemData> data)
		{
			// FIXME:
		}
	}

	public static class Int64ItemData_map
	{
		public static string ToString(Dictionary<long, ItemData> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = " + v.ToString(indent + "  "));
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<long, ItemData> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt64());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				long k = default;
				byte[] v = [];
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt64();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadBytes().ToByteArray();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				if (data.TryGetValue(k, out var c))
				{
					c.ApplySync(v);	
				}
				else
				{
					c = new ItemData();
					c.ApplySync(v);
					data[k] = c;
				}
			}
		}

		public static void RaiseChanged(Dictionary<long, ItemData> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<long, ItemData> data)
		{
			// FIXME:
		}
	}

	public static class StringItemData_map
	{
		public static string ToString(Dictionary<string, ItemData> data, string indent)
		{
			var sb = new System.Text.StringBuilder();
			sb.Append("[\n");
			var keys = data.Keys.ToList();
			keys.Sort();
			foreach (var k in keys)
			{
				var v = data[k];
				var key = k.ToString();
				sb.AppendLine(indent + "  " + key + " = " + v.ToString(indent + "  "));
			}
			sb.Append(indent + "]");
			return sb.ToString();
		}

		public static void ApplySync(Dictionary<string, ItemData> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = [];
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadString());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				string k = string.Empty;
				byte[] v = [];
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadString();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadBytes().ToByteArray();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				if (data.TryGetValue(k, out var c))
				{
					c.ApplySync(v);	
				}
				else
				{
					c = new ItemData();
					c.ApplySync(v);
					data[k] = c;
				}
			}
		}

		public static void RaiseChanged(Dictionary<string, ItemData> data)
		{
			// FIXME:
		}

		public static void ClearChanged(Dictionary<string, ItemData> data)
		{
			// FIXME:
		}
	}
}
