// Code generated by kds. DO NOT EDIT.
// source: kds/common.kds

namespace Kds;

public enum ItemType
{
	ItemTypeNone = 0,
	ItemTypeWeapon = 1,
	ItemTypeArmor = 2,
	ItemTypePotion = 3,
}

public class ItemData : Kdsync.IMessage
{
	public ItemData()
	{
		name_ = string.Empty;
	}

	private int id_;
	public int Id => id_;

	private string name_;
	public string Name => name_;

	private int count_;
	public int Count => count_;

	private long _changed;

	public event Action<ItemData, EventChanged>? OnChanged;

	public class EventChanged
	{
		public long _changed;
		public bool Id => (_changed & (0x01 << 1)) != 0;
		public bool Name => (_changed & (0x01 << 2)) != 0;
		public bool Count => (_changed & (0x01 << 3)) != 0;

		public EventChanged(long changed)
		{
			_changed = changed;
		}
	}

	public void MergeFrom(ref Kdsync.ParseContext ctx)
	{
		uint tag;
		while ((tag = ctx.ReadTag()) != 0)
		{
			var num = Kdsync.WireFormat.GetTagFieldNumber(tag);
			switch (num)
			{
			case 1:
				id_ = ctx.ReadInt32();
				_changed |= 0x01 << 1;
				break;
			case 2:
				name_ = ctx.ReadString();
				_changed |= 0x01 << 2;
				break;
			case 3:
				count_ = ctx.ReadInt32();
				_changed |= 0x01 << 3;
				break;
			default:
				ctx.SkipLastField();
				break;
			}
		}
	}

	public void RaiseChanged()
	{
		if (_changed == 0)
			return;
		OnChanged?.Invoke(this, new EventChanged(_changed));
	}

	public void ClearChanged()
	{
		if (_changed == 0)
			return;
		_changed = 0;
	}

	public IEnumerable<KeyValuePair<string, object>> GetFields()
	{
		var fields = new List<KeyValuePair<string, object>>();
		fields.Add(new KeyValuePair<string, object>("Id", id_));
		fields.Add(new KeyValuePair<string, object>("Name", name_));
		fields.Add(new KeyValuePair<string, object>("Count", count_));
		return fields;
	}

	public override string ToString()
	{
		return Kdsync.JsonFormatter.Format(this);
	}
}

