// Code generated by kds. DO NOT EDIT.
// source: TODO: Source File

package kds;
import (
	"google.golang.org/protobuf/types/known/emptypb"
)

type int32_empty_Map struct {
	syncable map[int32]struct{}
}

type int32_int32_Map struct {
	syncable map[int32]int32
}