// Code generated by kds. DO NOT EDIT.
// source: example2.kds

using System;
using System.Collections.Generic;
using Google.Protobuf;

namespace kds
{
	public class City
	{
		private readonly long _id_;
		public long Id => _id_;

		public City(long id)
		{
			_id_ = id;
			_playerBasicInfo = new PlayerBasicInfo();
			_cityInfo = new CityBaseInfo();
			_troops = new List<long>();
		}

		private long _playerId;
		public long PlayerId => _playerId;

		private PlayerBasicInfo _playerBasicInfo;
		public PlayerBasicInfo PlayerBasicInfo => _playerBasicInfo;

		private CityBaseInfo _cityInfo;
		public CityBaseInfo CityInfo => _cityInfo;

		private List<long> _troops;
		public List<long> Troops => _troops;

		private string _city;
		public string City_ => _city;

		private int _id;
		public int Id_ => _id;

		public class Events
		{
			public event Action<City> Event;

			public void TriggerEvent(City v)
			{
				Event?.Invoke(v);
			}
			public event Action<long, long> EventPlayerId;

			public void TriggerEventPlayerId(long v1, long v2)
			{
				EventPlayerId?.Invoke(v1, v2);
			}
			public readonly PlayerBasicInfo.Events EventPlayerBasicInfo = new PlayerBasicInfo.Events();
			public readonly CityBaseInfo.Events EventCityInfo = new CityBaseInfo.Events();
			public event Action<List<long>> EventTroops;

			public void TriggerEventTroops(List<long> v)
			{
				EventTroops?.Invoke(v);
			}
			public event Action<string, string> EventCity;

			public void TriggerEventCity(string v1, string v2)
			{
				EventCity?.Invoke(v1, v2);
			}
			public event Action<int, int> EventId;

			public void TriggerEventId(int v1, int v2)
			{
				EventId?.Invoke(v1, v2);
			}

			public Events()
			{
			}
		}

		public void Unmarshal(byte[] b, Events events)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					var oldPlayerId = _playerId;
					_playerId = stream.ReadInt64();
					events.TriggerEventPlayerId(oldPlayerId, _playerId);
					break;
				case 2:
					_playerBasicInfo.Unmarshal(stream.ReadBytes().ToByteArray(), events.EventPlayerBasicInfo);
					break;
				case 3:
					_cityInfo.Unmarshal(stream.ReadBytes().ToByteArray(), events.EventCityInfo);
					break;
				case 4:
					Int64_list.Unmarshal(_troops, stream.ReadBytes().ToByteArray());
					events.TriggerEventTroops(_troops);
					break;
				case 5:
					var oldCity = _city;
					_city = stream.ReadString();
					events.TriggerEventCity(oldCity, _city);
					break;
				case 6:
					var oldId = _id;
					_id = stream.ReadInt32();
					events.TriggerEventId(oldId, _id);
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}

		public void Unmarshal(byte[] b)
		{
			Unmarshal(b, City.Event);
		}

		public static readonly Events Event = new Events();
	}
	public class CityBaseInfo
	{
		public CityBaseInfo()
		{
			_positions = new List<Vector>();
			_troops = new Dictionary<int, object>();
		}

		private List<Vector> _positions;
		public List<Vector> Positions => _positions;

		private Dictionary<int, object> _troops;
		public Dictionary<int, object> Troops => _troops;

		private byte[] _buildInfo;
		public byte[] BuildInfo => _buildInfo;

		public class Events
		{
			public event Action<CityBaseInfo> Event;

			public void TriggerEvent(CityBaseInfo v)
			{
				Event?.Invoke(v);
			}
			public event Action<List<Vector>> EventPositions;

			public void TriggerEventPositions(List<Vector> v)
			{
				EventPositions?.Invoke(v);
			}
			public event Action<Dictionary<int, object>> EventTroops;

			public void TriggerEventTroops(Dictionary<int, object> v)
			{
				EventTroops?.Invoke(v);
			}
			public event Action<byte[], byte[]> EventBuildInfo;

			public void TriggerEventBuildInfo(byte[] v1, byte[] v2)
			{
				EventBuildInfo?.Invoke(v1, v2);
			}

			public Events()
			{
			}
		}

		public void Unmarshal(byte[] b, Events events)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					Vector_list.Unmarshal(_positions, stream.ReadBytes().ToByteArray());
					events.TriggerEventPositions(_positions);
					break;
				case 2:
					Int32Empty_map.Unmarshal(_troops, stream.ReadBytes().ToByteArray());
					events.TriggerEventTroops(_troops);
					break;
				case 3:
					var oldBuildInfo = _buildInfo;
					_buildInfo = stream.ReadBytes().ToByteArray();
					events.TriggerEventBuildInfo(oldBuildInfo, _buildInfo);
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class Vector
	{
		public Vector()
		{
		}

		private int _x;
		public int X => _x;

		private int _y;
		public int Y => _y;

		public class Events
		{
			public event Action<Vector> Event;

			public void TriggerEvent(Vector v)
			{
				Event?.Invoke(v);
			}
			public event Action<int, int> EventX;

			public void TriggerEventX(int v1, int v2)
			{
				EventX?.Invoke(v1, v2);
			}
			public event Action<int, int> EventY;

			public void TriggerEventY(int v1, int v2)
			{
				EventY?.Invoke(v1, v2);
			}

			public Events()
			{
			}
		}

		public void Unmarshal(byte[] b, Events events)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					var oldX = _x;
					_x = stream.ReadInt32();
					events.TriggerEventX(oldX, _x);
					break;
				case 2:
					var oldY = _y;
					_y = stream.ReadInt32();
					events.TriggerEventY(oldY, _y);
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}

	public static class Vector_list
	{
		public static void Unmarshal(List<Vector> data, byte[] b)
		{
			data.Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				var v = new Vector();
				v.Unmarshal(stream.ReadBytes().ToByteArray());
				data.Add(v);
			}
		}
	}
}
