// Code generated by kds. DO NOT EDIT.
// source: example1.kds

using System;
using System.Collections.Generic;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;

namespace kds
{
	public class Player
	{
		private readonly long _id_;
		public long Id => _id_;

		private PlayerBasicInfo _info;
		public PlayerBasicInfo Info => _info;

		private PlayerHero _hero;
		public PlayerHero Hero => _hero;

		private PlayerBag _bag;
		public PlayerBag Bag => _bag;

		public Player(long id)
		{
			_id_ = id;
			_info = new PlayerBasicInfo();
			_hero = new PlayerHero();
			_bag = new PlayerBag();
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					_info.Unmarshal(stream.ReadBytes().ToByteArray());
					break;
				case 2:
					_hero.Unmarshal(stream.ReadBytes().ToByteArray());
					break;
				case 3:
					_bag.Unmarshal(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class PlayerBasicInfo
	{
		private string _name;
		public string Name => _name;
		
		private bool _isNew;
		public bool IsNew => _isNew;
		
		private DateTime _createTime;
		public DateTime CreateTime => _createTime;
		
		public PlayerBasicInfo()
		{
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					_name = stream.ReadString();
					break;
				case 3:
					_isNew = stream.ReadBool();
					break;
				case 5:
					_createTime = Timestamp.Parser.ParseFrom(stream).ToDateTime();
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class PlayerHero
	{
		private Dictionary<long, Hero> _heroes;
		public Dictionary<long, Hero> Heroes => _heroes;
		
		public PlayerHero()
		{
			_heroes = new Dictionary<long, Hero>();
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					Int64Hero_map.Unmarshal(_heroes, stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class PlayerBag
	{
		private Dictionary<int, int> _resources;
		public Dictionary<int, int> Resources => _resources;
		
		public PlayerBag()
		{
			_resources = new Dictionary<int, int>();
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					Int32Int32_map.Unmarshal(_resources, stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class Hero
	{
		private int _heroId;
		public int HeroId => _heroId;
		
		private int _heroLevel;
		public int HeroLevel => _heroLevel;
		
		private HeroType _type;
		public HeroType Type => _type;
		
		private TimeSpan _needTime;
		public TimeSpan NeedTime => _needTime;
		
		public Hero()
		{
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					_heroId = stream.ReadInt32();
					break;
				case 2:
					_heroLevel = stream.ReadInt32();
					break;
				case 3:
					_type = (HeroType)stream.ReadEnum();
					break;
				case 4:
					_needTime = Duration.Parser.ParseFrom(stream).ToTimeSpan();
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}

	public static class Int64Hero_map
	{
		public static void Unmarshal(Dictionary<long, Hero> data, byte[] b)
		{
			var stream = new CodedInputStream(b);
			var clear = false;
			byte[] deletes = null;
			var entries = new List<byte[]>();
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1: // MapClearFieldNumber
					clear = stream.ReadBool();
					break;
				case 2: // MapDeleteFieldNumber
					deletes = stream.ReadBytes().ToByteArray();
					break;
				case 3: // MapEntryFieldNumber
					entries.Add(stream.ReadBytes().ToByteArray());
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
			if (clear)
			{
				data.Clear();
			}
			stream = new CodedInputStream(deletes);
			while (!stream.IsAtEnd)
			{
				data.Remove(stream.ReadInt64());
			}
			foreach (var entry in entries)
			{
				stream = new CodedInputStream(entry);
				long k = default;
				byte[] v = null;
				while ((tag = stream.ReadTag()) != 0)
				{
					var num = WireFormat.GetTagFieldNumber(tag);
					switch (num)
					{
					case 1: // MapEntryKeyFieldNumber
						k = stream.ReadInt64();
						break;
					case 2: // MapEntryValueFieldNumber
						v = stream.ReadBytes().ToByteArray();
						break;
					default:
						stream.SkipLastField();
						break;
					}
				}
				Hero c = null;
				if (!data.TryGetValue(k, out c))
				{
					c = new Hero();
					c.Unmarshal(v);
					data[k] = c;
				}
				else
				{
					c.Unmarshal(v);
				}
			}
		}
	}
	public enum HeroType
	{
		HeroType1 = 0,
		HeroType2 = 2,
		HeroType3 = -5,
	}
}
