// Code generated by kds. DO NOT EDIT.
// source: kds/example.kds

namespace Kds;

public class All : Kdsync.IMessage
{
	private readonly long _id;
	public long Id => _id;

	public All(long id)
	{
		_id = id;
		types_ = new AllType();
		lists_ = new AllList();
		maps_ = new AllMap();
	}

	private AllType types_;
	public AllType Types => types_;

	private AllList lists_;
	public AllList Lists => lists_;

	private AllMap maps_;
	public AllMap Maps => maps_;

	private long _changed;

	public event Action<All, EventChanged>? OnChanged;

	public class EventChanged
	{
		public long _changed;
		public bool Types => (_changed & (0x01 << 1)) != 0;
		public bool Lists => (_changed & (0x01 << 2)) != 0;
		public bool Maps => (_changed & (0x01 << 3)) != 0;

		public EventChanged(long changed)
		{
			_changed = changed;
		}
	}

	public void MergeFrom(ref Kdsync.ParseContext ctx)
	{
		uint tag;
		while ((tag = ctx.ReadTag()) != 0)
		{
			var num = Kdsync.WireFormat.GetTagFieldNumber(tag);
			switch (num)
			{
			case 1:
				ctx.ReadMessage(types_);
				_changed |= 0x01 << 1;
				break;
			case 2:
				ctx.ReadMessage(lists_);
				_changed |= 0x01 << 2;
				break;
			case 3:
				ctx.ReadMessage(maps_);
				_changed |= 0x01 << 3;
				break;
			default:
				ctx.SkipLastField();
				break;
			}
		}
	}

	public void WriteTo(Kdsync.CodedOutputStream output)
	{
	}

    public int CalculateSize()
	{
		return 0;
	}

	public void RaiseChanged()
	{
		if (_changed == 0)
			return;
		if ((_changed & (0x01 << 1)) != 0)
			types_.RaiseChanged();
		if ((_changed & (0x01 << 2)) != 0)
			lists_.RaiseChanged();
		if ((_changed & (0x01 << 3)) != 0)
			maps_.RaiseChanged();
		OnChanged?.Invoke(this, new EventChanged(_changed));
	}

	public void ClearChanged()
	{
		if (_changed == 0)
			return;
		if ((_changed & (0x01 << 1)) != 0)
			types_.ClearChanged();
		if ((_changed & (0x01 << 2)) != 0)
			lists_.ClearChanged();
		if ((_changed & (0x01 << 3)) != 0)
			maps_.ClearChanged();
		_changed = 0;
	}

	public IEnumerable<KeyValuePair<string, object>> GetFields()
	{
		var fields = new List<KeyValuePair<string, object>>();
		fields.Add(new KeyValuePair<string, object>("Types", types_));
		fields.Add(new KeyValuePair<string, object>("Lists", lists_));
		fields.Add(new KeyValuePair<string, object>("Maps", maps_));
		return fields;
	}

	public override string ToString()
	{
		return Kdsync.JsonFormatter.Format(this);
	}

	public void MergeFrom(byte[] buffer)
	{
		ReadOnlySpan<byte> readOnlySpan = new ReadOnlySpan<byte>(buffer);
		Kdsync.ParseContext.Initialize(readOnlySpan, out var ctx);
		MergeFrom(ref ctx);
	}
}

public class AllType : Kdsync.IMessage
{
	public AllType()
	{
		stringVal_ = string.Empty;
		bytesVal_ = new byte[0];
		itemData_ = new ItemData();
	}

	private int int32Val_;
	public int Int32Val => int32Val_;

	private long int64Val_;
	public long Int64Val => int64Val_;

	private uint uint32Val_;
	public uint Uint32Val => uint32Val_;

	private ulong uint64Val_;
	public ulong Uint64Val => uint64Val_;

	private int sint32Val_;
	public int Sint32Val => sint32Val_;

	private long sint64Val_;
	public long Sint64Val => sint64Val_;

	private uint fixed32Val_;
	public uint Fixed32Val => fixed32Val_;

	private ulong fixed64Val_;
	public ulong Fixed64Val => fixed64Val_;

	private int sfixed32Val_;
	public int Sfixed32Val => sfixed32Val_;

	private long sfixed64Val_;
	public long Sfixed64Val => sfixed64Val_;

	private float floatVal_;
	public float FloatVal => floatVal_;

	private double doubleVal_;
	public double DoubleVal => doubleVal_;

	private bool boolVal_;
	public bool BoolVal => boolVal_;

	private string stringVal_;
	public string StringVal => stringVal_;

	private byte[] bytesVal_;
	public byte[] BytesVal => bytesVal_;

	private Kdsync.Timestamp timestampVal_;
	public Kdsync.Timestamp TimestampVal => timestampVal_;

	private Kdsync.Duration durationVal_;
	public Kdsync.Duration DurationVal => durationVal_;

	private Kdsync.Empty emptyVal_;
	public Kdsync.Empty EmptyVal => emptyVal_;

	private ItemType enumVal_;
	public ItemType EnumVal => enumVal_;

	private ItemData itemData_;
	public ItemData ItemData => itemData_;

	private long _changed;

	public event Action<AllType, EventChanged>? OnChanged;

	public class EventChanged
	{
		public long _changed;
		public bool Int32Val => (_changed & (0x01 << 1)) != 0;
		public bool Int64Val => (_changed & (0x01 << 2)) != 0;
		public bool Uint32Val => (_changed & (0x01 << 3)) != 0;
		public bool Uint64Val => (_changed & (0x01 << 4)) != 0;
		public bool Sint32Val => (_changed & (0x01 << 5)) != 0;
		public bool Sint64Val => (_changed & (0x01 << 6)) != 0;
		public bool Fixed32Val => (_changed & (0x01 << 7)) != 0;
		public bool Fixed64Val => (_changed & (0x01 << 8)) != 0;
		public bool Sfixed32Val => (_changed & (0x01 << 9)) != 0;
		public bool Sfixed64Val => (_changed & (0x01 << 10)) != 0;
		public bool FloatVal => (_changed & (0x01 << 11)) != 0;
		public bool DoubleVal => (_changed & (0x01 << 12)) != 0;
		public bool BoolVal => (_changed & (0x01 << 13)) != 0;
		public bool StringVal => (_changed & (0x01 << 14)) != 0;
		public bool BytesVal => (_changed & (0x01 << 15)) != 0;
		public bool TimestampVal => (_changed & (0x01 << 16)) != 0;
		public bool DurationVal => (_changed & (0x01 << 17)) != 0;
		public bool EmptyVal => (_changed & (0x01 << 18)) != 0;
		public bool EnumVal => (_changed & (0x01 << 19)) != 0;
		public bool ItemData => (_changed & (0x01 << 20)) != 0;

		public EventChanged(long changed)
		{
			_changed = changed;
		}
	}

	public void MergeFrom(ref Kdsync.ParseContext ctx)
	{
		uint tag;
		while ((tag = ctx.ReadTag()) != 0)
		{
			var num = Kdsync.WireFormat.GetTagFieldNumber(tag);
			switch (num)
			{
			case 1:
				int32Val_ = ctx.ReadInt32();
				_changed |= 0x01 << 1;
				break;
			case 2:
				int64Val_ = ctx.ReadInt64();
				_changed |= 0x01 << 2;
				break;
			case 3:
				uint32Val_ = ctx.ReadUInt32();
				_changed |= 0x01 << 3;
				break;
			case 4:
				uint64Val_ = ctx.ReadUInt64();
				_changed |= 0x01 << 4;
				break;
			case 5:
				sint32Val_ = ctx.ReadSInt32();
				_changed |= 0x01 << 5;
				break;
			case 6:
				sint64Val_ = ctx.ReadSInt64();
				_changed |= 0x01 << 6;
				break;
			case 7:
				fixed32Val_ = ctx.ReadFixed32();
				_changed |= 0x01 << 7;
				break;
			case 8:
				fixed64Val_ = ctx.ReadFixed64();
				_changed |= 0x01 << 8;
				break;
			case 9:
				sfixed32Val_ = ctx.ReadSFixed32();
				_changed |= 0x01 << 9;
				break;
			case 10:
				sfixed64Val_ = ctx.ReadSFixed64();
				_changed |= 0x01 << 10;
				break;
			case 11:
				floatVal_ = ctx.ReadFloat();
				_changed |= 0x01 << 11;
				break;
			case 12:
				doubleVal_ = ctx.ReadDouble();
				_changed |= 0x01 << 12;
				break;
			case 13:
				boolVal_ = ctx.ReadBool();
				_changed |= 0x01 << 13;
				break;
			case 14:
				stringVal_ = ctx.ReadString();
				_changed |= 0x01 << 14;
				break;
			case 15:
				bytesVal_ = ctx.ReadBytes();
				_changed |= 0x01 << 15;
				break;
			case 16:
				timestampVal_ = ctx.ReadTimestamp();
				_changed |= 0x01 << 16;
				break;
			case 17:
				durationVal_ = ctx.ReadDuration();
				_changed |= 0x01 << 17;
				break;
			case 18:
				emptyVal_ = ctx.ReadEmpty();
				_changed |= 0x01 << 18;
				break;
			case 19:
				enumVal_ = (ItemType)ctx.ReadEnum();
				_changed |= 0x01 << 19;
				break;
			case 20:
				ctx.ReadMessage(itemData_);
				_changed |= 0x01 << 20;
				break;
			default:
				ctx.SkipLastField();
				break;
			}
		}
	}

	public void WriteTo(Kdsync.CodedOutputStream output)
	{
	}

    public int CalculateSize()
	{
		return 0;
	}

	public void RaiseChanged()
	{
		if (_changed == 0)
			return;
		if ((_changed & (0x01 << 20)) != 0)
			itemData_.RaiseChanged();
		OnChanged?.Invoke(this, new EventChanged(_changed));
	}

	public void ClearChanged()
	{
		if (_changed == 0)
			return;
		if ((_changed & (0x01 << 20)) != 0)
			itemData_.ClearChanged();
		_changed = 0;
	}

	public IEnumerable<KeyValuePair<string, object>> GetFields()
	{
		var fields = new List<KeyValuePair<string, object>>();
		fields.Add(new KeyValuePair<string, object>("Int32Val", int32Val_));
		fields.Add(new KeyValuePair<string, object>("Int64Val", int64Val_));
		fields.Add(new KeyValuePair<string, object>("Uint32Val", uint32Val_));
		fields.Add(new KeyValuePair<string, object>("Uint64Val", uint64Val_));
		fields.Add(new KeyValuePair<string, object>("Sint32Val", sint32Val_));
		fields.Add(new KeyValuePair<string, object>("Sint64Val", sint64Val_));
		fields.Add(new KeyValuePair<string, object>("Fixed32Val", fixed32Val_));
		fields.Add(new KeyValuePair<string, object>("Fixed64Val", fixed64Val_));
		fields.Add(new KeyValuePair<string, object>("Sfixed32Val", sfixed32Val_));
		fields.Add(new KeyValuePair<string, object>("Sfixed64Val", sfixed64Val_));
		fields.Add(new KeyValuePair<string, object>("FloatVal", floatVal_));
		fields.Add(new KeyValuePair<string, object>("DoubleVal", doubleVal_));
		fields.Add(new KeyValuePair<string, object>("BoolVal", boolVal_));
		fields.Add(new KeyValuePair<string, object>("StringVal", stringVal_));
		fields.Add(new KeyValuePair<string, object>("BytesVal", bytesVal_));
		fields.Add(new KeyValuePair<string, object>("TimestampVal", timestampVal_));
		fields.Add(new KeyValuePair<string, object>("DurationVal", durationVal_));
		fields.Add(new KeyValuePair<string, object>("EmptyVal", emptyVal_));
		fields.Add(new KeyValuePair<string, object>("EnumVal", enumVal_));
		fields.Add(new KeyValuePair<string, object>("ItemData", itemData_));
		return fields;
	}

	public override string ToString()
	{
		return Kdsync.JsonFormatter.Format(this);
	}
}

public class AllList : Kdsync.IMessage
{
	public AllList()
	{
		int32List_ = new Kdsync.Repeated<int>();
		int64List_ = new Kdsync.Repeated<long>();
		floatList_ = new Kdsync.Repeated<float>();
		doubleList_ = new Kdsync.Repeated<double>();
		boolList_ = new Kdsync.Repeated<bool>();
		stringList_ = new Kdsync.Repeated<string>();
		timestampList_ = new Kdsync.Repeated<Kdsync.Timestamp>();
		durationList_ = new Kdsync.Repeated<Kdsync.Duration>();
		emptyList_ = new Kdsync.Repeated<Kdsync.Empty>();
		enumList_ = new Kdsync.Repeated<ItemType>();
		itemList_ = new Kdsync.Repeated<ItemData>();
	}

	private static readonly Kdsync.FieldCodec<int> _list_int32List__codec = Kdsync.FieldCodec.ForInt32(1);
	private Kdsync.Repeated<int> int32List_;
	public Kdsync.Repeated<int> Int32List => int32List_;

	private static readonly Kdsync.FieldCodec<long> _list_int64List__codec = Kdsync.FieldCodec.ForInt64(2);
	private Kdsync.Repeated<long> int64List_;
	public Kdsync.Repeated<long> Int64List => int64List_;

	private static readonly Kdsync.FieldCodec<float> _list_floatList__codec = Kdsync.FieldCodec.ForFloat(3);
	private Kdsync.Repeated<float> floatList_;
	public Kdsync.Repeated<float> FloatList => floatList_;

	private static readonly Kdsync.FieldCodec<double> _list_doubleList__codec = Kdsync.FieldCodec.ForDouble(4);
	private Kdsync.Repeated<double> doubleList_;
	public Kdsync.Repeated<double> DoubleList => doubleList_;

	private static readonly Kdsync.FieldCodec<bool> _list_boolList__codec = Kdsync.FieldCodec.ForBool(5);
	private Kdsync.Repeated<bool> boolList_;
	public Kdsync.Repeated<bool> BoolList => boolList_;

	private static readonly Kdsync.FieldCodec<string> _list_stringList__codec = Kdsync.FieldCodec.ForString(6);
	private Kdsync.Repeated<string> stringList_;
	public Kdsync.Repeated<string> StringList => stringList_;

	private static readonly Kdsync.FieldCodec<Kdsync.Timestamp> _list_timestampList__codec = Kdsync.FieldCodec.ForTimestamp(7);
	private Kdsync.Repeated<Kdsync.Timestamp> timestampList_;
	public Kdsync.Repeated<Kdsync.Timestamp> TimestampList => timestampList_;

	private static readonly Kdsync.FieldCodec<Kdsync.Duration> _list_durationList__codec = Kdsync.FieldCodec.ForDuration(8);
	private Kdsync.Repeated<Kdsync.Duration> durationList_;
	public Kdsync.Repeated<Kdsync.Duration> DurationList => durationList_;

	private static readonly Kdsync.FieldCodec<Kdsync.Empty> _list_emptyList__codec = Kdsync.FieldCodec.ForEmpty(9);
	private Kdsync.Repeated<Kdsync.Empty> emptyList_;
	public Kdsync.Repeated<Kdsync.Empty> EmptyList => emptyList_;

	private static readonly Kdsync.FieldCodec<ItemType> _list_enumList__codec = Kdsync.FieldCodec.ForEnum(10, x => (int) x, x => (ItemType) x);
	private Kdsync.Repeated<ItemType> enumList_;
	public Kdsync.Repeated<ItemType> EnumList => enumList_;

	private static readonly Kdsync.FieldCodec<ItemData> _list_itemList__codec = Kdsync.FieldCodec.ForMessage<ItemData>(11);
	private Kdsync.Repeated<ItemData> itemList_;
	public Kdsync.Repeated<ItemData> ItemList => itemList_;

	private long _changed;

	public event Action<AllList, EventChanged>? OnChanged;

	public class EventChanged
	{
		public long _changed;
		public bool Int32List => (_changed & (0x01 << 1)) != 0;
		public bool Int64List => (_changed & (0x01 << 2)) != 0;
		public bool FloatList => (_changed & (0x01 << 3)) != 0;
		public bool DoubleList => (_changed & (0x01 << 4)) != 0;
		public bool BoolList => (_changed & (0x01 << 5)) != 0;
		public bool StringList => (_changed & (0x01 << 6)) != 0;
		public bool TimestampList => (_changed & (0x01 << 7)) != 0;
		public bool DurationList => (_changed & (0x01 << 8)) != 0;
		public bool EmptyList => (_changed & (0x01 << 9)) != 0;
		public bool EnumList => (_changed & (0x01 << 10)) != 0;
		public bool ItemList => (_changed & (0x01 << 11)) != 0;

		public EventChanged(long changed)
		{
			_changed = changed;
		}
	}

	public void MergeFrom(ref Kdsync.ParseContext ctx)
	{
		uint tag;
		while ((tag = ctx.ReadTag()) != 0)
		{
			var num = Kdsync.WireFormat.GetTagFieldNumber(tag);
			switch (num)
			{
			case 1:
				int32List_.AddEntriesFrom(ref ctx, _list_int32List__codec);
				_changed |= 0x01 << 1;
				break;
			case 2:
				int64List_.AddEntriesFrom(ref ctx, _list_int64List__codec);
				_changed |= 0x01 << 2;
				break;
			case 3:
				floatList_.AddEntriesFrom(ref ctx, _list_floatList__codec);
				_changed |= 0x01 << 3;
				break;
			case 4:
				doubleList_.AddEntriesFrom(ref ctx, _list_doubleList__codec);
				_changed |= 0x01 << 4;
				break;
			case 5:
				boolList_.AddEntriesFrom(ref ctx, _list_boolList__codec);
				_changed |= 0x01 << 5;
				break;
			case 6:
				stringList_.AddEntriesFrom(ref ctx, _list_stringList__codec);
				_changed |= 0x01 << 6;
				break;
			case 7:
				timestampList_.AddEntriesFrom(ref ctx, _list_timestampList__codec);
				_changed |= 0x01 << 7;
				break;
			case 8:
				durationList_.AddEntriesFrom(ref ctx, _list_durationList__codec);
				_changed |= 0x01 << 8;
				break;
			case 9:
				emptyList_.AddEntriesFrom(ref ctx, _list_emptyList__codec);
				_changed |= 0x01 << 9;
				break;
			case 10:
				enumList_.AddEntriesFrom(ref ctx, _list_enumList__codec);
				_changed |= 0x01 << 10;
				break;
			case 11:
				itemList_.AddEntriesFrom(ref ctx, _list_itemList__codec);
				_changed |= 0x01 << 11;
				break;
			default:
				ctx.SkipLastField();
				break;
			}
		}
	}

	public void WriteTo(Kdsync.CodedOutputStream output)
	{
	}

    public int CalculateSize()
	{
		return 0;
	}

	public void RaiseChanged()
	{
		if (_changed == 0)
			return;
		if ((_changed & (0x01 << 1)) != 0)
			int32List_.RaiseChanged();
		if ((_changed & (0x01 << 2)) != 0)
			int64List_.RaiseChanged();
		if ((_changed & (0x01 << 3)) != 0)
			floatList_.RaiseChanged();
		if ((_changed & (0x01 << 4)) != 0)
			doubleList_.RaiseChanged();
		if ((_changed & (0x01 << 5)) != 0)
			boolList_.RaiseChanged();
		if ((_changed & (0x01 << 6)) != 0)
			stringList_.RaiseChanged();
		if ((_changed & (0x01 << 7)) != 0)
			timestampList_.RaiseChanged();
		if ((_changed & (0x01 << 8)) != 0)
			durationList_.RaiseChanged();
		if ((_changed & (0x01 << 9)) != 0)
			emptyList_.RaiseChanged();
		if ((_changed & (0x01 << 10)) != 0)
			enumList_.RaiseChanged();
		if ((_changed & (0x01 << 11)) != 0)
			itemList_.RaiseChanged();
		OnChanged?.Invoke(this, new EventChanged(_changed));
	}

	public void ClearChanged()
	{
		if (_changed == 0)
			return;
		if ((_changed & (0x01 << 1)) != 0)
			int32List_.ClearChanged();
		if ((_changed & (0x01 << 2)) != 0)
			int64List_.ClearChanged();
		if ((_changed & (0x01 << 3)) != 0)
			floatList_.ClearChanged();
		if ((_changed & (0x01 << 4)) != 0)
			doubleList_.ClearChanged();
		if ((_changed & (0x01 << 5)) != 0)
			boolList_.ClearChanged();
		if ((_changed & (0x01 << 6)) != 0)
			stringList_.ClearChanged();
		if ((_changed & (0x01 << 7)) != 0)
			timestampList_.ClearChanged();
		if ((_changed & (0x01 << 8)) != 0)
			durationList_.ClearChanged();
		if ((_changed & (0x01 << 9)) != 0)
			emptyList_.ClearChanged();
		if ((_changed & (0x01 << 10)) != 0)
			enumList_.ClearChanged();
		if ((_changed & (0x01 << 11)) != 0)
			itemList_.ClearChanged();
		_changed = 0;
	}

	public IEnumerable<KeyValuePair<string, object>> GetFields()
	{
		var fields = new List<KeyValuePair<string, object>>();
		fields.Add(new KeyValuePair<string, object>("Int32List", int32List_));
		fields.Add(new KeyValuePair<string, object>("Int64List", int64List_));
		fields.Add(new KeyValuePair<string, object>("FloatList", floatList_));
		fields.Add(new KeyValuePair<string, object>("DoubleList", doubleList_));
		fields.Add(new KeyValuePair<string, object>("BoolList", boolList_));
		fields.Add(new KeyValuePair<string, object>("StringList", stringList_));
		fields.Add(new KeyValuePair<string, object>("TimestampList", timestampList_));
		fields.Add(new KeyValuePair<string, object>("DurationList", durationList_));
		fields.Add(new KeyValuePair<string, object>("EmptyList", emptyList_));
		fields.Add(new KeyValuePair<string, object>("EnumList", enumList_));
		fields.Add(new KeyValuePair<string, object>("ItemList", itemList_));
		return fields;
	}

	public override string ToString()
	{
		return Kdsync.JsonFormatter.Format(this);
	}
}

public class AllMap : Kdsync.IMessage
{
	public AllMap()
	{
		int32Int32_ = new Kdsync.Map<int, int>();
		int32String_ = new Kdsync.Map<int, string>();
		int32Timestamp_ = new Kdsync.Map<int, Kdsync.Timestamp>();
		int32Duration_ = new Kdsync.Map<int, Kdsync.Duration>();
		int32Empty_ = new Kdsync.Map<int, Kdsync.Empty>();
		int32Enum_ = new Kdsync.Map<int, ItemType>();
		int32ItemData_ = new Kdsync.Map<int, ItemData>();
		int64Int64_ = new Kdsync.Map<long, long>();
		int64String_ = new Kdsync.Map<long, string>();
		int64Timestamp_ = new Kdsync.Map<long, Kdsync.Timestamp>();
		int64Duration_ = new Kdsync.Map<long, Kdsync.Duration>();
		int64Empty_ = new Kdsync.Map<long, Kdsync.Empty>();
		int64Enum_ = new Kdsync.Map<long, ItemType>();
		int64ItemData_ = new Kdsync.Map<long, ItemData>();
		stringInt32_ = new Kdsync.Map<string, int>();
		stringString_ = new Kdsync.Map<string, string>();
		stringTimestamp_ = new Kdsync.Map<string, Kdsync.Timestamp>();
		stringDuration_ = new Kdsync.Map<string, Kdsync.Duration>();
		stringEmpty_ = new Kdsync.Map<string, Kdsync.Empty>();
		stringEnum_ = new Kdsync.Map<string, ItemType>();
		stringItemData_ = new Kdsync.Map<string, ItemData>();
		boolInt32_ = new Kdsync.Map<bool, int>();
		boolString_ = new Kdsync.Map<bool, string>();
		boolTimestamp_ = new Kdsync.Map<bool, Kdsync.Timestamp>();
		boolDuration_ = new Kdsync.Map<bool, Kdsync.Duration>();
		boolEmpty_ = new Kdsync.Map<bool, Kdsync.Empty>();
		boolEnum_ = new Kdsync.Map<bool, ItemType>();
		boolItemData_ = new Kdsync.Map<bool, ItemData>();
	}

	private static readonly Kdsync.Map<int, int>.Codec _map_int32Int32__codec = new Kdsync.Map<int, int>.Codec(Kdsync.FieldCodec.ForInt32(1), Kdsync.FieldCodec.ForInt32(2), 1);
	private Kdsync.Map<int, int> int32Int32_;
	public Kdsync.Map<int, int> Int32Int32 => int32Int32_;

	private static readonly Kdsync.Map<int, string>.Codec _map_int32String__codec = new Kdsync.Map<int, string>.Codec(Kdsync.FieldCodec.ForInt32(1), Kdsync.FieldCodec.ForString(2), 2);
	private Kdsync.Map<int, string> int32String_;
	public Kdsync.Map<int, string> Int32String => int32String_;

	private static readonly Kdsync.Map<int, Kdsync.Timestamp>.Codec _map_int32Timestamp__codec = new Kdsync.Map<int, Kdsync.Timestamp>.Codec(Kdsync.FieldCodec.ForInt32(1), Kdsync.FieldCodec.ForTimestamp(2), 3);
	private Kdsync.Map<int, Kdsync.Timestamp> int32Timestamp_;
	public Kdsync.Map<int, Kdsync.Timestamp> Int32Timestamp => int32Timestamp_;

	private static readonly Kdsync.Map<int, Kdsync.Duration>.Codec _map_int32Duration__codec = new Kdsync.Map<int, Kdsync.Duration>.Codec(Kdsync.FieldCodec.ForInt32(1), Kdsync.FieldCodec.ForDuration(2), 4);
	private Kdsync.Map<int, Kdsync.Duration> int32Duration_;
	public Kdsync.Map<int, Kdsync.Duration> Int32Duration => int32Duration_;

	private static readonly Kdsync.Map<int, Kdsync.Empty>.Codec _map_int32Empty__codec = new Kdsync.Map<int, Kdsync.Empty>.Codec(Kdsync.FieldCodec.ForInt32(1), Kdsync.FieldCodec.ForEmpty(2), 5);
	private Kdsync.Map<int, Kdsync.Empty> int32Empty_;
	public Kdsync.Map<int, Kdsync.Empty> Int32Empty => int32Empty_;

	private static readonly Kdsync.Map<int, ItemType>.Codec _map_int32Enum__codec = new Kdsync.Map<int, ItemType>.Codec(Kdsync.FieldCodec.ForInt32(1), Kdsync.FieldCodec.ForEnum(2, x => (int) x, x => (ItemType) x), 6);
	private Kdsync.Map<int, ItemType> int32Enum_;
	public Kdsync.Map<int, ItemType> Int32Enum => int32Enum_;

	private static readonly Kdsync.Map<int, ItemData>.Codec _map_int32ItemData__codec = new Kdsync.Map<int, ItemData>.Codec(Kdsync.FieldCodec.ForInt32(1), Kdsync.FieldCodec.ForMessage<ItemData>(2), 7);
	private Kdsync.Map<int, ItemData> int32ItemData_;
	public Kdsync.Map<int, ItemData> Int32ItemData => int32ItemData_;

	private static readonly Kdsync.Map<long, long>.Codec _map_int64Int64__codec = new Kdsync.Map<long, long>.Codec(Kdsync.FieldCodec.ForInt64(1), Kdsync.FieldCodec.ForInt64(2), 8);
	private Kdsync.Map<long, long> int64Int64_;
	public Kdsync.Map<long, long> Int64Int64 => int64Int64_;

	private static readonly Kdsync.Map<long, string>.Codec _map_int64String__codec = new Kdsync.Map<long, string>.Codec(Kdsync.FieldCodec.ForInt64(1), Kdsync.FieldCodec.ForString(2), 9);
	private Kdsync.Map<long, string> int64String_;
	public Kdsync.Map<long, string> Int64String => int64String_;

	private static readonly Kdsync.Map<long, Kdsync.Timestamp>.Codec _map_int64Timestamp__codec = new Kdsync.Map<long, Kdsync.Timestamp>.Codec(Kdsync.FieldCodec.ForInt64(1), Kdsync.FieldCodec.ForTimestamp(2), 10);
	private Kdsync.Map<long, Kdsync.Timestamp> int64Timestamp_;
	public Kdsync.Map<long, Kdsync.Timestamp> Int64Timestamp => int64Timestamp_;

	private static readonly Kdsync.Map<long, Kdsync.Duration>.Codec _map_int64Duration__codec = new Kdsync.Map<long, Kdsync.Duration>.Codec(Kdsync.FieldCodec.ForInt64(1), Kdsync.FieldCodec.ForDuration(2), 11);
	private Kdsync.Map<long, Kdsync.Duration> int64Duration_;
	public Kdsync.Map<long, Kdsync.Duration> Int64Duration => int64Duration_;

	private static readonly Kdsync.Map<long, Kdsync.Empty>.Codec _map_int64Empty__codec = new Kdsync.Map<long, Kdsync.Empty>.Codec(Kdsync.FieldCodec.ForInt64(1), Kdsync.FieldCodec.ForEmpty(2), 12);
	private Kdsync.Map<long, Kdsync.Empty> int64Empty_;
	public Kdsync.Map<long, Kdsync.Empty> Int64Empty => int64Empty_;

	private static readonly Kdsync.Map<long, ItemType>.Codec _map_int64Enum__codec = new Kdsync.Map<long, ItemType>.Codec(Kdsync.FieldCodec.ForInt64(1), Kdsync.FieldCodec.ForEnum(2, x => (int) x, x => (ItemType) x), 13);
	private Kdsync.Map<long, ItemType> int64Enum_;
	public Kdsync.Map<long, ItemType> Int64Enum => int64Enum_;

	private static readonly Kdsync.Map<long, ItemData>.Codec _map_int64ItemData__codec = new Kdsync.Map<long, ItemData>.Codec(Kdsync.FieldCodec.ForInt64(1), Kdsync.FieldCodec.ForMessage<ItemData>(2), 14);
	private Kdsync.Map<long, ItemData> int64ItemData_;
	public Kdsync.Map<long, ItemData> Int64ItemData => int64ItemData_;

	private static readonly Kdsync.Map<string, int>.Codec _map_stringInt32__codec = new Kdsync.Map<string, int>.Codec(Kdsync.FieldCodec.ForString(1), Kdsync.FieldCodec.ForInt32(2), 15);
	private Kdsync.Map<string, int> stringInt32_;
	public Kdsync.Map<string, int> StringInt32 => stringInt32_;

	private static readonly Kdsync.Map<string, string>.Codec _map_stringString__codec = new Kdsync.Map<string, string>.Codec(Kdsync.FieldCodec.ForString(1), Kdsync.FieldCodec.ForString(2), 16);
	private Kdsync.Map<string, string> stringString_;
	public Kdsync.Map<string, string> StringString => stringString_;

	private static readonly Kdsync.Map<string, Kdsync.Timestamp>.Codec _map_stringTimestamp__codec = new Kdsync.Map<string, Kdsync.Timestamp>.Codec(Kdsync.FieldCodec.ForString(1), Kdsync.FieldCodec.ForTimestamp(2), 17);
	private Kdsync.Map<string, Kdsync.Timestamp> stringTimestamp_;
	public Kdsync.Map<string, Kdsync.Timestamp> StringTimestamp => stringTimestamp_;

	private static readonly Kdsync.Map<string, Kdsync.Duration>.Codec _map_stringDuration__codec = new Kdsync.Map<string, Kdsync.Duration>.Codec(Kdsync.FieldCodec.ForString(1), Kdsync.FieldCodec.ForDuration(2), 18);
	private Kdsync.Map<string, Kdsync.Duration> stringDuration_;
	public Kdsync.Map<string, Kdsync.Duration> StringDuration => stringDuration_;

	private static readonly Kdsync.Map<string, Kdsync.Empty>.Codec _map_stringEmpty__codec = new Kdsync.Map<string, Kdsync.Empty>.Codec(Kdsync.FieldCodec.ForString(1), Kdsync.FieldCodec.ForEmpty(2), 19);
	private Kdsync.Map<string, Kdsync.Empty> stringEmpty_;
	public Kdsync.Map<string, Kdsync.Empty> StringEmpty => stringEmpty_;

	private static readonly Kdsync.Map<string, ItemType>.Codec _map_stringEnum__codec = new Kdsync.Map<string, ItemType>.Codec(Kdsync.FieldCodec.ForString(1), Kdsync.FieldCodec.ForEnum(2, x => (int) x, x => (ItemType) x), 20);
	private Kdsync.Map<string, ItemType> stringEnum_;
	public Kdsync.Map<string, ItemType> StringEnum => stringEnum_;

	private static readonly Kdsync.Map<string, ItemData>.Codec _map_stringItemData__codec = new Kdsync.Map<string, ItemData>.Codec(Kdsync.FieldCodec.ForString(1), Kdsync.FieldCodec.ForMessage<ItemData>(2), 21);
	private Kdsync.Map<string, ItemData> stringItemData_;
	public Kdsync.Map<string, ItemData> StringItemData => stringItemData_;

	private static readonly Kdsync.Map<bool, int>.Codec _map_boolInt32__codec = new Kdsync.Map<bool, int>.Codec(Kdsync.FieldCodec.ForBool(1), Kdsync.FieldCodec.ForInt32(2), 22);
	private Kdsync.Map<bool, int> boolInt32_;
	public Kdsync.Map<bool, int> BoolInt32 => boolInt32_;

	private static readonly Kdsync.Map<bool, string>.Codec _map_boolString__codec = new Kdsync.Map<bool, string>.Codec(Kdsync.FieldCodec.ForBool(1), Kdsync.FieldCodec.ForString(2), 23);
	private Kdsync.Map<bool, string> boolString_;
	public Kdsync.Map<bool, string> BoolString => boolString_;

	private static readonly Kdsync.Map<bool, Kdsync.Timestamp>.Codec _map_boolTimestamp__codec = new Kdsync.Map<bool, Kdsync.Timestamp>.Codec(Kdsync.FieldCodec.ForBool(1), Kdsync.FieldCodec.ForTimestamp(2), 24);
	private Kdsync.Map<bool, Kdsync.Timestamp> boolTimestamp_;
	public Kdsync.Map<bool, Kdsync.Timestamp> BoolTimestamp => boolTimestamp_;

	private static readonly Kdsync.Map<bool, Kdsync.Duration>.Codec _map_boolDuration__codec = new Kdsync.Map<bool, Kdsync.Duration>.Codec(Kdsync.FieldCodec.ForBool(1), Kdsync.FieldCodec.ForDuration(2), 25);
	private Kdsync.Map<bool, Kdsync.Duration> boolDuration_;
	public Kdsync.Map<bool, Kdsync.Duration> BoolDuration => boolDuration_;

	private static readonly Kdsync.Map<bool, Kdsync.Empty>.Codec _map_boolEmpty__codec = new Kdsync.Map<bool, Kdsync.Empty>.Codec(Kdsync.FieldCodec.ForBool(1), Kdsync.FieldCodec.ForEmpty(2), 26);
	private Kdsync.Map<bool, Kdsync.Empty> boolEmpty_;
	public Kdsync.Map<bool, Kdsync.Empty> BoolEmpty => boolEmpty_;

	private static readonly Kdsync.Map<bool, ItemType>.Codec _map_boolEnum__codec = new Kdsync.Map<bool, ItemType>.Codec(Kdsync.FieldCodec.ForBool(1), Kdsync.FieldCodec.ForEnum(2, x => (int) x, x => (ItemType) x), 27);
	private Kdsync.Map<bool, ItemType> boolEnum_;
	public Kdsync.Map<bool, ItemType> BoolEnum => boolEnum_;

	private static readonly Kdsync.Map<bool, ItemData>.Codec _map_boolItemData__codec = new Kdsync.Map<bool, ItemData>.Codec(Kdsync.FieldCodec.ForBool(1), Kdsync.FieldCodec.ForMessage<ItemData>(2), 28);
	private Kdsync.Map<bool, ItemData> boolItemData_;
	public Kdsync.Map<bool, ItemData> BoolItemData => boolItemData_;

	private long _changed;

	public event Action<AllMap, EventChanged>? OnChanged;

	public class EventChanged
	{
		public long _changed;
		public bool Int32Int32 => (_changed & (0x01 << 1)) != 0;
		public bool Int32String => (_changed & (0x01 << 2)) != 0;
		public bool Int32Timestamp => (_changed & (0x01 << 3)) != 0;
		public bool Int32Duration => (_changed & (0x01 << 4)) != 0;
		public bool Int32Empty => (_changed & (0x01 << 5)) != 0;
		public bool Int32Enum => (_changed & (0x01 << 6)) != 0;
		public bool Int32ItemData => (_changed & (0x01 << 7)) != 0;
		public bool Int64Int64 => (_changed & (0x01 << 8)) != 0;
		public bool Int64String => (_changed & (0x01 << 9)) != 0;
		public bool Int64Timestamp => (_changed & (0x01 << 10)) != 0;
		public bool Int64Duration => (_changed & (0x01 << 11)) != 0;
		public bool Int64Empty => (_changed & (0x01 << 12)) != 0;
		public bool Int64Enum => (_changed & (0x01 << 13)) != 0;
		public bool Int64ItemData => (_changed & (0x01 << 14)) != 0;
		public bool StringInt32 => (_changed & (0x01 << 15)) != 0;
		public bool StringString => (_changed & (0x01 << 16)) != 0;
		public bool StringTimestamp => (_changed & (0x01 << 17)) != 0;
		public bool StringDuration => (_changed & (0x01 << 18)) != 0;
		public bool StringEmpty => (_changed & (0x01 << 19)) != 0;
		public bool StringEnum => (_changed & (0x01 << 20)) != 0;
		public bool StringItemData => (_changed & (0x01 << 21)) != 0;
		public bool BoolInt32 => (_changed & (0x01 << 22)) != 0;
		public bool BoolString => (_changed & (0x01 << 23)) != 0;
		public bool BoolTimestamp => (_changed & (0x01 << 24)) != 0;
		public bool BoolDuration => (_changed & (0x01 << 25)) != 0;
		public bool BoolEmpty => (_changed & (0x01 << 26)) != 0;
		public bool BoolEnum => (_changed & (0x01 << 27)) != 0;
		public bool BoolItemData => (_changed & (0x01 << 28)) != 0;

		public EventChanged(long changed)
		{
			_changed = changed;
		}
	}

	public void MergeFrom(ref Kdsync.ParseContext ctx)
	{
		uint tag;
		while ((tag = ctx.ReadTag()) != 0)
		{
			var num = Kdsync.WireFormat.GetTagFieldNumber(tag);
			switch (num)
			{
			case 1:
				int32Int32_.AddEntriesFrom(ref ctx, _map_int32Int32__codec);
				_changed |= 0x01 << 1;
				break;
			case 2:
				int32String_.AddEntriesFrom(ref ctx, _map_int32String__codec);
				_changed |= 0x01 << 2;
				break;
			case 3:
				int32Timestamp_.AddEntriesFrom(ref ctx, _map_int32Timestamp__codec);
				_changed |= 0x01 << 3;
				break;
			case 4:
				int32Duration_.AddEntriesFrom(ref ctx, _map_int32Duration__codec);
				_changed |= 0x01 << 4;
				break;
			case 5:
				int32Empty_.AddEntriesFrom(ref ctx, _map_int32Empty__codec);
				_changed |= 0x01 << 5;
				break;
			case 6:
				int32Enum_.AddEntriesFrom(ref ctx, _map_int32Enum__codec);
				_changed |= 0x01 << 6;
				break;
			case 7:
				int32ItemData_.AddEntriesFrom(ref ctx, _map_int32ItemData__codec);
				_changed |= 0x01 << 7;
				break;
			case 8:
				int64Int64_.AddEntriesFrom(ref ctx, _map_int64Int64__codec);
				_changed |= 0x01 << 8;
				break;
			case 9:
				int64String_.AddEntriesFrom(ref ctx, _map_int64String__codec);
				_changed |= 0x01 << 9;
				break;
			case 10:
				int64Timestamp_.AddEntriesFrom(ref ctx, _map_int64Timestamp__codec);
				_changed |= 0x01 << 10;
				break;
			case 11:
				int64Duration_.AddEntriesFrom(ref ctx, _map_int64Duration__codec);
				_changed |= 0x01 << 11;
				break;
			case 12:
				int64Empty_.AddEntriesFrom(ref ctx, _map_int64Empty__codec);
				_changed |= 0x01 << 12;
				break;
			case 13:
				int64Enum_.AddEntriesFrom(ref ctx, _map_int64Enum__codec);
				_changed |= 0x01 << 13;
				break;
			case 14:
				int64ItemData_.AddEntriesFrom(ref ctx, _map_int64ItemData__codec);
				_changed |= 0x01 << 14;
				break;
			case 15:
				stringInt32_.AddEntriesFrom(ref ctx, _map_stringInt32__codec);
				_changed |= 0x01 << 15;
				break;
			case 16:
				stringString_.AddEntriesFrom(ref ctx, _map_stringString__codec);
				_changed |= 0x01 << 16;
				break;
			case 17:
				stringTimestamp_.AddEntriesFrom(ref ctx, _map_stringTimestamp__codec);
				_changed |= 0x01 << 17;
				break;
			case 18:
				stringDuration_.AddEntriesFrom(ref ctx, _map_stringDuration__codec);
				_changed |= 0x01 << 18;
				break;
			case 19:
				stringEmpty_.AddEntriesFrom(ref ctx, _map_stringEmpty__codec);
				_changed |= 0x01 << 19;
				break;
			case 20:
				stringEnum_.AddEntriesFrom(ref ctx, _map_stringEnum__codec);
				_changed |= 0x01 << 20;
				break;
			case 21:
				stringItemData_.AddEntriesFrom(ref ctx, _map_stringItemData__codec);
				_changed |= 0x01 << 21;
				break;
			case 22:
				boolInt32_.AddEntriesFrom(ref ctx, _map_boolInt32__codec);
				_changed |= 0x01 << 22;
				break;
			case 23:
				boolString_.AddEntriesFrom(ref ctx, _map_boolString__codec);
				_changed |= 0x01 << 23;
				break;
			case 24:
				boolTimestamp_.AddEntriesFrom(ref ctx, _map_boolTimestamp__codec);
				_changed |= 0x01 << 24;
				break;
			case 25:
				boolDuration_.AddEntriesFrom(ref ctx, _map_boolDuration__codec);
				_changed |= 0x01 << 25;
				break;
			case 26:
				boolEmpty_.AddEntriesFrom(ref ctx, _map_boolEmpty__codec);
				_changed |= 0x01 << 26;
				break;
			case 27:
				boolEnum_.AddEntriesFrom(ref ctx, _map_boolEnum__codec);
				_changed |= 0x01 << 27;
				break;
			case 28:
				boolItemData_.AddEntriesFrom(ref ctx, _map_boolItemData__codec);
				_changed |= 0x01 << 28;
				break;
			default:
				ctx.SkipLastField();
				break;
			}
		}
	}

	public void WriteTo(Kdsync.CodedOutputStream output)
	{
	}

    public int CalculateSize()
	{
		return 0;
	}

	public void RaiseChanged()
	{
		if (_changed == 0)
			return;
		if ((_changed & (0x01 << 1)) != 0)
			int32Int32_.RaiseChanged();
		if ((_changed & (0x01 << 2)) != 0)
			int32String_.RaiseChanged();
		if ((_changed & (0x01 << 3)) != 0)
			int32Timestamp_.RaiseChanged();
		if ((_changed & (0x01 << 4)) != 0)
			int32Duration_.RaiseChanged();
		if ((_changed & (0x01 << 5)) != 0)
			int32Empty_.RaiseChanged();
		if ((_changed & (0x01 << 6)) != 0)
			int32Enum_.RaiseChanged();
		if ((_changed & (0x01 << 7)) != 0)
			int32ItemData_.RaiseChanged();
		if ((_changed & (0x01 << 8)) != 0)
			int64Int64_.RaiseChanged();
		if ((_changed & (0x01 << 9)) != 0)
			int64String_.RaiseChanged();
		if ((_changed & (0x01 << 10)) != 0)
			int64Timestamp_.RaiseChanged();
		if ((_changed & (0x01 << 11)) != 0)
			int64Duration_.RaiseChanged();
		if ((_changed & (0x01 << 12)) != 0)
			int64Empty_.RaiseChanged();
		if ((_changed & (0x01 << 13)) != 0)
			int64Enum_.RaiseChanged();
		if ((_changed & (0x01 << 14)) != 0)
			int64ItemData_.RaiseChanged();
		if ((_changed & (0x01 << 15)) != 0)
			stringInt32_.RaiseChanged();
		if ((_changed & (0x01 << 16)) != 0)
			stringString_.RaiseChanged();
		if ((_changed & (0x01 << 17)) != 0)
			stringTimestamp_.RaiseChanged();
		if ((_changed & (0x01 << 18)) != 0)
			stringDuration_.RaiseChanged();
		if ((_changed & (0x01 << 19)) != 0)
			stringEmpty_.RaiseChanged();
		if ((_changed & (0x01 << 20)) != 0)
			stringEnum_.RaiseChanged();
		if ((_changed & (0x01 << 21)) != 0)
			stringItemData_.RaiseChanged();
		if ((_changed & (0x01 << 22)) != 0)
			boolInt32_.RaiseChanged();
		if ((_changed & (0x01 << 23)) != 0)
			boolString_.RaiseChanged();
		if ((_changed & (0x01 << 24)) != 0)
			boolTimestamp_.RaiseChanged();
		if ((_changed & (0x01 << 25)) != 0)
			boolDuration_.RaiseChanged();
		if ((_changed & (0x01 << 26)) != 0)
			boolEmpty_.RaiseChanged();
		if ((_changed & (0x01 << 27)) != 0)
			boolEnum_.RaiseChanged();
		if ((_changed & (0x01 << 28)) != 0)
			boolItemData_.RaiseChanged();
		OnChanged?.Invoke(this, new EventChanged(_changed));
	}

	public void ClearChanged()
	{
		if (_changed == 0)
			return;
		if ((_changed & (0x01 << 1)) != 0)
			int32Int32_.ClearChanged();
		if ((_changed & (0x01 << 2)) != 0)
			int32String_.ClearChanged();
		if ((_changed & (0x01 << 3)) != 0)
			int32Timestamp_.ClearChanged();
		if ((_changed & (0x01 << 4)) != 0)
			int32Duration_.ClearChanged();
		if ((_changed & (0x01 << 5)) != 0)
			int32Empty_.ClearChanged();
		if ((_changed & (0x01 << 6)) != 0)
			int32Enum_.ClearChanged();
		if ((_changed & (0x01 << 7)) != 0)
			int32ItemData_.ClearChanged();
		if ((_changed & (0x01 << 8)) != 0)
			int64Int64_.ClearChanged();
		if ((_changed & (0x01 << 9)) != 0)
			int64String_.ClearChanged();
		if ((_changed & (0x01 << 10)) != 0)
			int64Timestamp_.ClearChanged();
		if ((_changed & (0x01 << 11)) != 0)
			int64Duration_.ClearChanged();
		if ((_changed & (0x01 << 12)) != 0)
			int64Empty_.ClearChanged();
		if ((_changed & (0x01 << 13)) != 0)
			int64Enum_.ClearChanged();
		if ((_changed & (0x01 << 14)) != 0)
			int64ItemData_.ClearChanged();
		if ((_changed & (0x01 << 15)) != 0)
			stringInt32_.ClearChanged();
		if ((_changed & (0x01 << 16)) != 0)
			stringString_.ClearChanged();
		if ((_changed & (0x01 << 17)) != 0)
			stringTimestamp_.ClearChanged();
		if ((_changed & (0x01 << 18)) != 0)
			stringDuration_.ClearChanged();
		if ((_changed & (0x01 << 19)) != 0)
			stringEmpty_.ClearChanged();
		if ((_changed & (0x01 << 20)) != 0)
			stringEnum_.ClearChanged();
		if ((_changed & (0x01 << 21)) != 0)
			stringItemData_.ClearChanged();
		if ((_changed & (0x01 << 22)) != 0)
			boolInt32_.ClearChanged();
		if ((_changed & (0x01 << 23)) != 0)
			boolString_.ClearChanged();
		if ((_changed & (0x01 << 24)) != 0)
			boolTimestamp_.ClearChanged();
		if ((_changed & (0x01 << 25)) != 0)
			boolDuration_.ClearChanged();
		if ((_changed & (0x01 << 26)) != 0)
			boolEmpty_.ClearChanged();
		if ((_changed & (0x01 << 27)) != 0)
			boolEnum_.ClearChanged();
		if ((_changed & (0x01 << 28)) != 0)
			boolItemData_.ClearChanged();
		_changed = 0;
	}

	public IEnumerable<KeyValuePair<string, object>> GetFields()
	{
		var fields = new List<KeyValuePair<string, object>>();
		fields.Add(new KeyValuePair<string, object>("Int32Int32", int32Int32_));
		fields.Add(new KeyValuePair<string, object>("Int32String", int32String_));
		fields.Add(new KeyValuePair<string, object>("Int32Timestamp", int32Timestamp_));
		fields.Add(new KeyValuePair<string, object>("Int32Duration", int32Duration_));
		fields.Add(new KeyValuePair<string, object>("Int32Empty", int32Empty_));
		fields.Add(new KeyValuePair<string, object>("Int32Enum", int32Enum_));
		fields.Add(new KeyValuePair<string, object>("Int32ItemData", int32ItemData_));
		fields.Add(new KeyValuePair<string, object>("Int64Int64", int64Int64_));
		fields.Add(new KeyValuePair<string, object>("Int64String", int64String_));
		fields.Add(new KeyValuePair<string, object>("Int64Timestamp", int64Timestamp_));
		fields.Add(new KeyValuePair<string, object>("Int64Duration", int64Duration_));
		fields.Add(new KeyValuePair<string, object>("Int64Empty", int64Empty_));
		fields.Add(new KeyValuePair<string, object>("Int64Enum", int64Enum_));
		fields.Add(new KeyValuePair<string, object>("Int64ItemData", int64ItemData_));
		fields.Add(new KeyValuePair<string, object>("StringInt32", stringInt32_));
		fields.Add(new KeyValuePair<string, object>("StringString", stringString_));
		fields.Add(new KeyValuePair<string, object>("StringTimestamp", stringTimestamp_));
		fields.Add(new KeyValuePair<string, object>("StringDuration", stringDuration_));
		fields.Add(new KeyValuePair<string, object>("StringEmpty", stringEmpty_));
		fields.Add(new KeyValuePair<string, object>("StringEnum", stringEnum_));
		fields.Add(new KeyValuePair<string, object>("StringItemData", stringItemData_));
		fields.Add(new KeyValuePair<string, object>("BoolInt32", boolInt32_));
		fields.Add(new KeyValuePair<string, object>("BoolString", boolString_));
		fields.Add(new KeyValuePair<string, object>("BoolTimestamp", boolTimestamp_));
		fields.Add(new KeyValuePair<string, object>("BoolDuration", boolDuration_));
		fields.Add(new KeyValuePair<string, object>("BoolEmpty", boolEmpty_));
		fields.Add(new KeyValuePair<string, object>("BoolEnum", boolEnum_));
		fields.Add(new KeyValuePair<string, object>("BoolItemData", boolItemData_));
		return fields;
	}

	public override string ToString()
	{
		return Kdsync.JsonFormatter.Format(this);
	}
}

