// Code generated by kds. DO NOT EDIT.
// source: example2.kds

using System.Collections.Generic;
using Google.Protobuf;

namespace kds
{
	public class City
	{
		private readonly long _id;
		public long Id => _id;

		private long _playerId;
		public long GetPlayerId => _playerId;

		private PlayerBasicInfo _playerBasicInfo;
		public PlayerBasicInfo GetPlayerBasicInfo => _playerBasicInfo;

		private CityBaseInfo _cityInfo;
		public CityBaseInfo GetCityInfo => _cityInfo;

		private List<long> _troops;
		public List<long> GetTroops => _troops;

		private string _city;
		public string GetCity => _city;

		public City(long id)
		{
			_id = id;
			_playerBasicInfo = new PlayerBasicInfo();
			_cityInfo = new CityBaseInfo();
			_troops = new List<long>();
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					_playerId = stream.ReadInt64();
					break;
				case 2:
					_playerBasicInfo.Unmarshal(stream.ReadBytes().ToByteArray());
					break;
				case 3:
					_cityInfo.Unmarshal(stream.ReadBytes().ToByteArray());
					break;
				case 4:
					Int64_list.Unmarshal(_troops, stream.ReadBytes().ToByteArray());
					break;
				case 5:
					_city = stream.ReadString();
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class CityBaseInfo
	{
		private List<Vector> _positions;
		public List<Vector> GetPositions => _positions;
		
		private Dictionary<int, object> _troops;
		public Dictionary<int, object> GetTroops => _troops;
		
		private byte[] _buildInfo;
		public byte[] GetBuildInfo => _buildInfo;
		
		public CityBaseInfo()
		{
			_positions = new List<Vector>();
			_troops = new Dictionary<int, object>();
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					Vector_list.Unmarshal(_positions, stream.ReadBytes().ToByteArray());
					break;
				case 2:
					Int32Empty_map.Unmarshal(_troops, stream.ReadBytes().ToByteArray());
					break;
				case 3:
					_buildInfo = stream.ReadBytes().ToByteArray();
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class Vector
	{
		private int _x;
		public int GetX => _x;
		
		private int _y;
		public int GetY => _y;
		
		public Vector()
		{
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					_x = stream.ReadInt32();
					break;
				case 2:
					_y = stream.ReadInt32();
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}

	public static class Vector_list
	{
		public static void Unmarshal(List<Vector> data, byte[] b)
		{
			data.Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				var v = new Vector();
				v.Unmarshal(stream.ReadBytes().ToByteArray());
				data.Add(v);
			}
		}
	}
}
