// Code generated by kds. DO NOT EDIT.
// source: example2.kds

using System;
using System.Collections.Generic;
using Google.Protobuf;

namespace kds
{
	public class City
	{
		private readonly long _id_;
		public long Id => _id_;

		public City(long id)
		{
			_id_ = id;
			_playerBasicInfo = new PlayerBasicInfo();
			_cityInfo = new CityBaseInfo();
			_troops = new List<long>();
		}

		private long _playerId;
		public long PlayerId => _playerId;
		public bool IsPlayerIdChanged => _changed&(0x01<<1) != 0;

		private PlayerBasicInfo _playerBasicInfo;
		public PlayerBasicInfo PlayerBasicInfo => _playerBasicInfo;
		public bool IsPlayerBasicInfoChanged => _changed&(0x01<<2) != 0;

		private CityBaseInfo _cityInfo;
		public CityBaseInfo CityInfo => _cityInfo;
		public bool IsCityInfoChanged => _changed&(0x01<<3) != 0;

		private List<long> _troops;
		public List<long> Troops => _troops;
		public bool IsTroopsChanged => _changed&(0x01<<4) != 0;

		private string _city;
		public string City_ => _city;
		public bool IsCityChanged => _changed&(0x01<<5) != 0;

		private int _id;
		public int Id_ => _id;
		public bool IsIdChanged => _changed&(0x01<<6) != 0;

		private long _changed;

		public event Action<City> OnChanged;

		public void InvokeChange()
		{
			if (_changed == 0)
				return;
			if (_changed & (0x01<<2) != 0)
				_playerBasicInfo.InvokeChange();
			if (_changed & (0x01<<3) != 0)
				_cityInfo.InvokeChange();
			OnChanged.Invoke(this);
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					_playerId = stream.ReadInt64();
					_changed |= 0x01<<1;
					break;
				case 2:
					_playerBasicInfo.Unmarshal(stream.ReadBytes().ToByteArray());
					_changed |= 0x01<<2;
					break;
				case 3:
					_cityInfo.Unmarshal(stream.ReadBytes().ToByteArray());
					_changed |= 0x01<<3;
					break;
				case 4:
					Int64_list.Unmarshal(_troops, stream.ReadBytes().ToByteArray());
					_changed |= 0x01<<4;
					break;
				case 5:
					_city = stream.ReadString();
					_changed |= 0x01<<5;
					break;
				case 6:
					_id = stream.ReadInt32();
					_changed |= 0x01<<6;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class CityBaseInfo
	{
		public CityBaseInfo()
		{
			_positions = new List<Vector>();
			_troops = new Dictionary<int, object>();
		}

		private List<Vector> _positions;
		public List<Vector> Positions => _positions;
		public bool IsPositionsChanged => _changed&(0x01<<1) != 0;

		private Dictionary<int, object> _troops;
		public Dictionary<int, object> Troops => _troops;
		public bool IsTroopsChanged => _changed&(0x01<<2) != 0;

		private byte[] _buildInfo;
		public byte[] BuildInfo => _buildInfo;
		public bool IsBuildInfoChanged => _changed&(0x01<<3) != 0;

		private long _changed;

		public event Action<CityBaseInfo> OnChanged;

		public void InvokeChange()
		{
			if (_changed == 0)
				return;
			if (_changed & (0x01<<1) != 0)
				_positions.InvokeChange();
			OnChanged.Invoke(this);
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					Vector_list.Unmarshal(_positions, stream.ReadBytes().ToByteArray());
					_changed |= 0x01<<1;
					break;
				case 2:
					Int32Empty_map.Unmarshal(_troops, stream.ReadBytes().ToByteArray());
					_changed |= 0x01<<2;
					break;
				case 3:
					_buildInfo = stream.ReadBytes().ToByteArray();
					_changed |= 0x01<<3;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}
	public class Vector
	{
		public Vector()
		{
		}

		private int _x;
		public int X => _x;
		public bool IsXChanged => _changed&(0x01<<1) != 0;

		private int _y;
		public int Y => _y;
		public bool IsYChanged => _changed&(0x01<<2) != 0;

		private long _changed;

		public event Action<Vector> OnChanged;

		public void InvokeChange()
		{
			if (_changed == 0)
				return;
			OnChanged.Invoke(this);
		}

		public void Unmarshal(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					_x = stream.ReadInt32();
					_changed |= 0x01<<1;
					break;
				case 2:
					_y = stream.ReadInt32();
					_changed |= 0x01<<2;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}
	}

	public static class Vector_list
	{
		public static void Unmarshal(List<Vector> data, byte[] b)
		{
			data.Clear();
			var stream = new CodedInputStream(b);
			while (!stream.IsAtEnd)
			{
				var v = new Vector();
				v.Unmarshal(stream.ReadBytes().ToByteArray());
				data.Add(v);
			}
		}
	}
}
