// Code generated by kds. DO NOT EDIT.
// source: example\example1.kds

using System;
using System.Collections.Generic;
using Google.Protobuf;

namespace kds
{

	public class Player
	{
		private long _id;
		private PlayerBasicInfo _Info;
		private PlayerHero _Hero;
		private PlayerBag _Bag;

		public Player(long id)
		{
			_id = id;
			_Info = new PlayerBasicInfo();
			_Hero = new PlayerHero();
			_Bag = new PlayerBag();
		}

		public long Id => _id;

		public PlayerBasicInfo Info
		{
			get { return _Info; }
		}

		public PlayerHero Hero
		{
			get { return _Hero; }
		}

		public PlayerBag Bag
		{
			get { return _Bag; }
		}
	}

	public class PlayerBasicInfo
	{
		private string _Name;
		private bool _IsNew;
		private DateTime _CreateTime;

		public PlayerBasicInfo(long id)
		{
			_id = id;
		}

		public string Name
		{
			get { return _Name; }
		}

		public bool IsNew
		{
			get { return _IsNew; }
		}

		public DateTime CreateTime
		{
			get { return _CreateTime; }
		}
	}

	public class PlayerHero
	{
		private Map<int64, Hero> _Heroes;

		public PlayerHero(long id)
		{
			_id = id;
			_Heroes = new Map<int64, Hero>();
		}

		public Map<int64, Hero> Heroes
		{
			get { return _Heroes; }
		}
	}

	public class PlayerBag
	{
		private Map<int32, int> _Resources;

		public PlayerBag(long id)
		{
			_id = id;
			_Resources = new Map<int32, int>();
		}

		public Map<int32, int> Resources
		{
			get { return _Resources; }
		}
	}

	public class Hero
	{
		private int _HeroId;
		private int _HeroLevel;
		private HeroType _Type;
		private TimeSpan _NeedTime;

		public Hero(long id)
		{
			_id = id;
		}

		public int HeroId
		{
			get { return _HeroId; }
		}

		public int HeroLevel
		{
			get { return _HeroLevel; }
		}

		public HeroType Type
		{
			get { return _Type; }
		}

		public TimeSpan NeedTime
		{
			get { return _NeedTime; }
		}
	}

	public enum HeroType
	{
		HeroType1 = 0,
		HeroType2 = 2,
		HeroType3 = -5,
	}
}
