// Code generated by kds. DO NOT EDIT.
// source: kds/example.kds

using System;
using System.Collections.Generic;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;

namespace kds
{
	public class All
	{
		private readonly long _id;
		public long Id => _id;

		public All(long id)
		{
			_id = id;
			types_ = new AllType();
			lists_ = new AllList();
			maps_ = new AllMap();
		}

		private AllType types_;
		public AllType Types => types_;

		private AllList lists_;
		public AllList Lists => lists_;

		private AllMap maps_;
		public AllMap Maps => maps_;

		private long _changed;

		public event Action<All, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Types => (_changed & (0x01 << 1)) != 0;
			public bool Lists => (_changed & (0x01 << 2)) != 0;
			public bool Maps => (_changed & (0x01 << 3)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void ApplySync(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					types_.ApplySync(stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 1;
					break;
				case 2:
					lists_.ApplySync(stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 2;
					break;
				case 3:
					maps_.ApplySync(stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 3;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				types_.RaiseChanged();
			if ((_changed & (0x01 << 2)) != 0)
				lists_.RaiseChanged();
			if ((_changed & (0x01 << 3)) != 0)
				maps_.RaiseChanged();
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				types_.ClearChanged();
			if ((_changed & (0x01 << 2)) != 0)
				lists_.ClearChanged();
			if ((_changed & (0x01 << 3)) != 0)
				maps_.ClearChanged();
			_changed = 0;
		}
	}
	public class AllType
	{
		public AllType()
		{
			stringVal_ = string.Empty;
			bytesVal_ = [];
			emptyVal_ = default;
			itemData_ = new ItemData();
		}

		private int int32Val_;
		public int Int32Val => int32Val_;

		private long int64Val_;
		public long Int64Val => int64Val_;

		private uint uint32Val_;
		public uint Uint32Val => uint32Val_;

		private ulong uint64Val_;
		public ulong Uint64Val => uint64Val_;

		private int sint32Val_;
		public int Sint32Val => sint32Val_;

		private long sint64Val_;
		public long Sint64Val => sint64Val_;

		private uint fixed32Val_;
		public uint Fixed32Val => fixed32Val_;

		private ulong fixed64Val_;
		public ulong Fixed64Val => fixed64Val_;

		private int sfixed32Val_;
		public int Sfixed32Val => sfixed32Val_;

		private long sfixed64Val_;
		public long Sfixed64Val => sfixed64Val_;

		private float floatVal_;
		public float FloatVal => floatVal_;

		private double doubleVal_;
		public double DoubleVal => doubleVal_;

		private bool boolVal_;
		public bool BoolVal => boolVal_;

		private string stringVal_;
		public string StringVal => stringVal_;

		private byte[] bytesVal_;
		public byte[] BytesVal => bytesVal_;

		private DateTime timestampVal_;
		public DateTime TimestampVal => timestampVal_;

		private TimeSpan durationVal_;
		public TimeSpan DurationVal => durationVal_;

		private ValueTuple emptyVal_;
		public ValueTuple EmptyVal => emptyVal_;

		private ItemType enumVal_;
		public ItemType EnumVal => enumVal_;

		private ItemData itemData_;
		public ItemData ItemData => itemData_;

		private long _changed;

		public event Action<AllType, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Int32Val => (_changed & (0x01 << 1)) != 0;
			public bool Int64Val => (_changed & (0x01 << 2)) != 0;
			public bool Uint32Val => (_changed & (0x01 << 3)) != 0;
			public bool Uint64Val => (_changed & (0x01 << 4)) != 0;
			public bool Sint32Val => (_changed & (0x01 << 5)) != 0;
			public bool Sint64Val => (_changed & (0x01 << 6)) != 0;
			public bool Fixed32Val => (_changed & (0x01 << 7)) != 0;
			public bool Fixed64Val => (_changed & (0x01 << 8)) != 0;
			public bool Sfixed32Val => (_changed & (0x01 << 9)) != 0;
			public bool Sfixed64Val => (_changed & (0x01 << 10)) != 0;
			public bool FloatVal => (_changed & (0x01 << 11)) != 0;
			public bool DoubleVal => (_changed & (0x01 << 12)) != 0;
			public bool BoolVal => (_changed & (0x01 << 13)) != 0;
			public bool StringVal => (_changed & (0x01 << 14)) != 0;
			public bool BytesVal => (_changed & (0x01 << 15)) != 0;
			public bool TimestampVal => (_changed & (0x01 << 16)) != 0;
			public bool DurationVal => (_changed & (0x01 << 17)) != 0;
			public bool EmptyVal => (_changed & (0x01 << 18)) != 0;
			public bool EnumVal => (_changed & (0x01 << 19)) != 0;
			public bool ItemData => (_changed & (0x01 << 20)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void ApplySync(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					int32Val_ = stream.ReadInt32();
					_changed |= 0x01 << 1;
					break;
				case 2:
					int64Val_ = stream.ReadInt64();
					_changed |= 0x01 << 2;
					break;
				case 3:
					uint32Val_ = stream.ReadUInt32();
					_changed |= 0x01 << 3;
					break;
				case 4:
					uint64Val_ = stream.ReadUInt64();
					_changed |= 0x01 << 4;
					break;
				case 5:
					sint32Val_ = stream.ReadSInt32();
					_changed |= 0x01 << 5;
					break;
				case 6:
					sint64Val_ = stream.ReadSInt64();
					_changed |= 0x01 << 6;
					break;
				case 7:
					fixed32Val_ = stream.ReadFixed32();
					_changed |= 0x01 << 7;
					break;
				case 8:
					fixed64Val_ = stream.ReadFixed64();
					_changed |= 0x01 << 8;
					break;
				case 9:
					sfixed32Val_ = stream.ReadSFixed32();
					_changed |= 0x01 << 9;
					break;
				case 10:
					sfixed64Val_ = stream.ReadSFixed64();
					_changed |= 0x01 << 10;
					break;
				case 11:
					floatVal_ = stream.ReadFloat();
					_changed |= 0x01 << 11;
					break;
				case 12:
					doubleVal_ = stream.ReadDouble();
					_changed |= 0x01 << 12;
					break;
				case 13:
					boolVal_ = stream.ReadBool();
					_changed |= 0x01 << 13;
					break;
				case 14:
					stringVal_ = stream.ReadString();
					_changed |= 0x01 << 14;
					break;
				case 15:
					bytesVal_ = stream.ReadBytes().ToByteArray();
					_changed |= 0x01 << 15;
					break;
				case 16:
					timestampVal_ = Timestamp.Parser.ParseFrom(stream.ReadBytes().ToByteArray()).ToDateTime();
					_changed |= 0x01 << 16;
					break;
				case 17:
					durationVal_ = Duration.Parser.ParseFrom(stream.ReadBytes().ToByteArray()).ToTimeSpan();
					_changed |= 0x01 << 17;
					break;
				case 18:
					Empty.Parser.ParseFrom(stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 18;
					break;
				case 19:
					enumVal_ = (ItemType)stream.ReadEnum();
					_changed |= 0x01 << 19;
					break;
				case 20:
					itemData_.ApplySync(stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 20;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 20)) != 0)
				itemData_.RaiseChanged();
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 20)) != 0)
				itemData_.ClearChanged();
			_changed = 0;
		}
	}
	public class AllList
	{
		public AllList()
		{
			int32List_ = new List<int>();
			int64List_ = new List<long>();
			floatList_ = new List<float>();
			doubleList_ = new List<double>();
			boolList_ = new List<bool>();
			stringList_ = new List<string>();
			timestampList_ = new List<DateTime>();
			durationList_ = new List<TimeSpan>();
			emptyList_ = new List<ValueTuple>();
			enumList_ = new List<ItemType>();
			itemList_ = new List<ItemData>();
		}

		private List<int> int32List_;
		public List<int> Int32List => int32List_;

		private List<long> int64List_;
		public List<long> Int64List => int64List_;

		private List<float> floatList_;
		public List<float> FloatList => floatList_;

		private List<double> doubleList_;
		public List<double> DoubleList => doubleList_;

		private List<bool> boolList_;
		public List<bool> BoolList => boolList_;

		private List<string> stringList_;
		public List<string> StringList => stringList_;

		private List<DateTime> timestampList_;
		public List<DateTime> TimestampList => timestampList_;

		private List<TimeSpan> durationList_;
		public List<TimeSpan> DurationList => durationList_;

		private List<ValueTuple> emptyList_;
		public List<ValueTuple> EmptyList => emptyList_;

		private List<ItemType> enumList_;
		public List<ItemType> EnumList => enumList_;

		private List<ItemData> itemList_;
		public List<ItemData> ItemList => itemList_;

		private long _changed;

		public event Action<AllList, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Int32List => (_changed & (0x01 << 1)) != 0;
			public bool Int64List => (_changed & (0x01 << 2)) != 0;
			public bool FloatList => (_changed & (0x01 << 3)) != 0;
			public bool DoubleList => (_changed & (0x01 << 4)) != 0;
			public bool BoolList => (_changed & (0x01 << 5)) != 0;
			public bool StringList => (_changed & (0x01 << 6)) != 0;
			public bool TimestampList => (_changed & (0x01 << 7)) != 0;
			public bool DurationList => (_changed & (0x01 << 8)) != 0;
			public bool EmptyList => (_changed & (0x01 << 9)) != 0;
			public bool EnumList => (_changed & (0x01 << 10)) != 0;
			public bool ItemList => (_changed & (0x01 << 11)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void ApplySync(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					Int32_list.ApplySync(int32List_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 1;
					break;
				case 2:
					Int64_list.ApplySync(int64List_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 2;
					break;
				case 3:
					Float_list.ApplySync(floatList_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 3;
					break;
				case 4:
					Double_list.ApplySync(doubleList_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 4;
					break;
				case 5:
					Bool_list.ApplySync(boolList_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 5;
					break;
				case 6:
					String_list.ApplySync(stringList_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 6;
					break;
				case 7:
					Timestamp_list.ApplySync(timestampList_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 7;
					break;
				case 8:
					Duration_list.ApplySync(durationList_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 8;
					break;
				case 9:
					Empty_list.ApplySync(emptyList_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 9;
					break;
				case 10:
					ItemType_list.ApplySync(enumList_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 10;
					break;
				case 11:
					ItemData_list.ApplySync(itemList_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 11;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				Int32_list.RaiseChanged(int32List_);
			if ((_changed & (0x01 << 2)) != 0)
				Int64_list.RaiseChanged(int64List_);
			if ((_changed & (0x01 << 3)) != 0)
				Float_list.RaiseChanged(floatList_);
			if ((_changed & (0x01 << 4)) != 0)
				Double_list.RaiseChanged(doubleList_);
			if ((_changed & (0x01 << 5)) != 0)
				Bool_list.RaiseChanged(boolList_);
			if ((_changed & (0x01 << 6)) != 0)
				String_list.RaiseChanged(stringList_);
			if ((_changed & (0x01 << 7)) != 0)
				Timestamp_list.RaiseChanged(timestampList_);
			if ((_changed & (0x01 << 8)) != 0)
				Duration_list.RaiseChanged(durationList_);
			if ((_changed & (0x01 << 9)) != 0)
				Empty_list.RaiseChanged(emptyList_);
			if ((_changed & (0x01 << 10)) != 0)
				ItemType_list.RaiseChanged(enumList_);
			if ((_changed & (0x01 << 11)) != 0)
				ItemData_list.RaiseChanged(itemList_);
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				Int32_list.ClearChanged(int32List_);
			if ((_changed & (0x01 << 2)) != 0)
				Int64_list.ClearChanged(int64List_);
			if ((_changed & (0x01 << 3)) != 0)
				Float_list.ClearChanged(floatList_);
			if ((_changed & (0x01 << 4)) != 0)
				Double_list.ClearChanged(doubleList_);
			if ((_changed & (0x01 << 5)) != 0)
				Bool_list.ClearChanged(boolList_);
			if ((_changed & (0x01 << 6)) != 0)
				String_list.ClearChanged(stringList_);
			if ((_changed & (0x01 << 7)) != 0)
				Timestamp_list.ClearChanged(timestampList_);
			if ((_changed & (0x01 << 8)) != 0)
				Duration_list.ClearChanged(durationList_);
			if ((_changed & (0x01 << 9)) != 0)
				Empty_list.ClearChanged(emptyList_);
			if ((_changed & (0x01 << 10)) != 0)
				ItemType_list.ClearChanged(enumList_);
			if ((_changed & (0x01 << 11)) != 0)
				ItemData_list.ClearChanged(itemList_);
			_changed = 0;
		}
	}
	public class AllMap
	{
		public AllMap()
		{
			int32Int32_ = new Dictionary<int, int>();
			int32String_ = new Dictionary<int, string>();
			int32Timestamp_ = new Dictionary<int, DateTime>();
			int32Duration_ = new Dictionary<int, TimeSpan>();
			int32Empty_ = new Dictionary<int, ValueTuple>();
			int32Enum_ = new Dictionary<int, ItemType>();
			int32ItemData_ = new Dictionary<int, ItemData>();
			int64Int64_ = new Dictionary<long, long>();
			int64String_ = new Dictionary<long, string>();
			int64Timestamp_ = new Dictionary<long, DateTime>();
			int64Duration_ = new Dictionary<long, TimeSpan>();
			int64Empty_ = new Dictionary<long, ValueTuple>();
			int64Enum_ = new Dictionary<long, ItemType>();
			int64ItemData_ = new Dictionary<long, ItemData>();
			stringInt32_ = new Dictionary<string, int>();
			stringString_ = new Dictionary<string, string>();
			stringTimestamp_ = new Dictionary<string, DateTime>();
			stringDuration_ = new Dictionary<string, TimeSpan>();
			stringEmpty_ = new Dictionary<string, ValueTuple>();
			stringEnum_ = new Dictionary<string, ItemType>();
			stringItemData_ = new Dictionary<string, ItemData>();
			boolInt32_ = new Dictionary<bool, int>();
			boolString_ = new Dictionary<bool, string>();
			boolTimestamp_ = new Dictionary<bool, DateTime>();
			boolDuration_ = new Dictionary<bool, TimeSpan>();
			boolEmpty_ = new Dictionary<bool, ValueTuple>();
			boolEnum_ = new Dictionary<bool, ItemType>();
			boolItemData_ = new Dictionary<bool, ItemData>();
		}

		private Dictionary<int, int> int32Int32_;
		public Dictionary<int, int> Int32Int32 => int32Int32_;

		private Dictionary<int, string> int32String_;
		public Dictionary<int, string> Int32String => int32String_;

		private Dictionary<int, DateTime> int32Timestamp_;
		public Dictionary<int, DateTime> Int32Timestamp => int32Timestamp_;

		private Dictionary<int, TimeSpan> int32Duration_;
		public Dictionary<int, TimeSpan> Int32Duration => int32Duration_;

		private Dictionary<int, ValueTuple> int32Empty_;
		public Dictionary<int, ValueTuple> Int32Empty => int32Empty_;

		private Dictionary<int, ItemType> int32Enum_;
		public Dictionary<int, ItemType> Int32Enum => int32Enum_;

		private Dictionary<int, ItemData> int32ItemData_;
		public Dictionary<int, ItemData> Int32ItemData => int32ItemData_;

		private Dictionary<long, long> int64Int64_;
		public Dictionary<long, long> Int64Int64 => int64Int64_;

		private Dictionary<long, string> int64String_;
		public Dictionary<long, string> Int64String => int64String_;

		private Dictionary<long, DateTime> int64Timestamp_;
		public Dictionary<long, DateTime> Int64Timestamp => int64Timestamp_;

		private Dictionary<long, TimeSpan> int64Duration_;
		public Dictionary<long, TimeSpan> Int64Duration => int64Duration_;

		private Dictionary<long, ValueTuple> int64Empty_;
		public Dictionary<long, ValueTuple> Int64Empty => int64Empty_;

		private Dictionary<long, ItemType> int64Enum_;
		public Dictionary<long, ItemType> Int64Enum => int64Enum_;

		private Dictionary<long, ItemData> int64ItemData_;
		public Dictionary<long, ItemData> Int64ItemData => int64ItemData_;

		private Dictionary<string, int> stringInt32_;
		public Dictionary<string, int> StringInt32 => stringInt32_;

		private Dictionary<string, string> stringString_;
		public Dictionary<string, string> StringString => stringString_;

		private Dictionary<string, DateTime> stringTimestamp_;
		public Dictionary<string, DateTime> StringTimestamp => stringTimestamp_;

		private Dictionary<string, TimeSpan> stringDuration_;
		public Dictionary<string, TimeSpan> StringDuration => stringDuration_;

		private Dictionary<string, ValueTuple> stringEmpty_;
		public Dictionary<string, ValueTuple> StringEmpty => stringEmpty_;

		private Dictionary<string, ItemType> stringEnum_;
		public Dictionary<string, ItemType> StringEnum => stringEnum_;

		private Dictionary<string, ItemData> stringItemData_;
		public Dictionary<string, ItemData> StringItemData => stringItemData_;

		private Dictionary<bool, int> boolInt32_;
		public Dictionary<bool, int> BoolInt32 => boolInt32_;

		private Dictionary<bool, string> boolString_;
		public Dictionary<bool, string> BoolString => boolString_;

		private Dictionary<bool, DateTime> boolTimestamp_;
		public Dictionary<bool, DateTime> BoolTimestamp => boolTimestamp_;

		private Dictionary<bool, TimeSpan> boolDuration_;
		public Dictionary<bool, TimeSpan> BoolDuration => boolDuration_;

		private Dictionary<bool, ValueTuple> boolEmpty_;
		public Dictionary<bool, ValueTuple> BoolEmpty => boolEmpty_;

		private Dictionary<bool, ItemType> boolEnum_;
		public Dictionary<bool, ItemType> BoolEnum => boolEnum_;

		private Dictionary<bool, ItemData> boolItemData_;
		public Dictionary<bool, ItemData> BoolItemData => boolItemData_;

		private long _changed;

		public event Action<AllMap, EventChanged>? OnChanged;

		public class EventChanged
		{
			public long _changed;
			public bool Int32Int32 => (_changed & (0x01 << 1)) != 0;
			public bool Int32String => (_changed & (0x01 << 2)) != 0;
			public bool Int32Timestamp => (_changed & (0x01 << 3)) != 0;
			public bool Int32Duration => (_changed & (0x01 << 4)) != 0;
			public bool Int32Empty => (_changed & (0x01 << 5)) != 0;
			public bool Int32Enum => (_changed & (0x01 << 6)) != 0;
			public bool Int32ItemData => (_changed & (0x01 << 7)) != 0;
			public bool Int64Int64 => (_changed & (0x01 << 8)) != 0;
			public bool Int64String => (_changed & (0x01 << 9)) != 0;
			public bool Int64Timestamp => (_changed & (0x01 << 10)) != 0;
			public bool Int64Duration => (_changed & (0x01 << 11)) != 0;
			public bool Int64Empty => (_changed & (0x01 << 12)) != 0;
			public bool Int64Enum => (_changed & (0x01 << 13)) != 0;
			public bool Int64ItemData => (_changed & (0x01 << 14)) != 0;
			public bool StringInt32 => (_changed & (0x01 << 15)) != 0;
			public bool StringString => (_changed & (0x01 << 16)) != 0;
			public bool StringTimestamp => (_changed & (0x01 << 17)) != 0;
			public bool StringDuration => (_changed & (0x01 << 18)) != 0;
			public bool StringEmpty => (_changed & (0x01 << 19)) != 0;
			public bool StringEnum => (_changed & (0x01 << 20)) != 0;
			public bool StringItemData => (_changed & (0x01 << 21)) != 0;
			public bool BoolInt32 => (_changed & (0x01 << 22)) != 0;
			public bool BoolString => (_changed & (0x01 << 23)) != 0;
			public bool BoolTimestamp => (_changed & (0x01 << 24)) != 0;
			public bool BoolDuration => (_changed & (0x01 << 25)) != 0;
			public bool BoolEmpty => (_changed & (0x01 << 26)) != 0;
			public bool BoolEnum => (_changed & (0x01 << 27)) != 0;
			public bool BoolItemData => (_changed & (0x01 << 28)) != 0;

			public EventChanged(long changed)
			{
				_changed = changed;
			}
		}

		public void ApplySync(byte[] b)
		{
			var stream = new CodedInputStream(b);
			uint tag;
			while ((tag = stream.ReadTag()) != 0)
			{
				var num = WireFormat.GetTagFieldNumber(tag);
				switch (num)
				{
				case 1:
					Int32Int32_map.ApplySync(int32Int32_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 1;
					break;
				case 2:
					Int32String_map.ApplySync(int32String_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 2;
					break;
				case 3:
					Int32Timestamp_map.ApplySync(int32Timestamp_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 3;
					break;
				case 4:
					Int32Duration_map.ApplySync(int32Duration_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 4;
					break;
				case 5:
					Int32Empty_map.ApplySync(int32Empty_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 5;
					break;
				case 6:
					Int32ItemType_map.ApplySync(int32Enum_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 6;
					break;
				case 7:
					Int32ItemData_map.ApplySync(int32ItemData_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 7;
					break;
				case 8:
					Int64Int64_map.ApplySync(int64Int64_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 8;
					break;
				case 9:
					Int64String_map.ApplySync(int64String_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 9;
					break;
				case 10:
					Int64Timestamp_map.ApplySync(int64Timestamp_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 10;
					break;
				case 11:
					Int64Duration_map.ApplySync(int64Duration_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 11;
					break;
				case 12:
					Int64Empty_map.ApplySync(int64Empty_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 12;
					break;
				case 13:
					Int64ItemType_map.ApplySync(int64Enum_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 13;
					break;
				case 14:
					Int64ItemData_map.ApplySync(int64ItemData_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 14;
					break;
				case 15:
					StringInt32_map.ApplySync(stringInt32_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 15;
					break;
				case 16:
					StringString_map.ApplySync(stringString_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 16;
					break;
				case 17:
					StringTimestamp_map.ApplySync(stringTimestamp_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 17;
					break;
				case 18:
					StringDuration_map.ApplySync(stringDuration_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 18;
					break;
				case 19:
					StringEmpty_map.ApplySync(stringEmpty_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 19;
					break;
				case 20:
					StringItemType_map.ApplySync(stringEnum_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 20;
					break;
				case 21:
					StringItemData_map.ApplySync(stringItemData_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 21;
					break;
				case 22:
					BoolInt32_map.ApplySync(boolInt32_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 22;
					break;
				case 23:
					BoolString_map.ApplySync(boolString_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 23;
					break;
				case 24:
					BoolTimestamp_map.ApplySync(boolTimestamp_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 24;
					break;
				case 25:
					BoolDuration_map.ApplySync(boolDuration_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 25;
					break;
				case 26:
					BoolEmpty_map.ApplySync(boolEmpty_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 26;
					break;
				case 27:
					BoolItemType_map.ApplySync(boolEnum_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 27;
					break;
				case 28:
					BoolItemData_map.ApplySync(boolItemData_, stream.ReadBytes().ToByteArray());
					_changed |= 0x01 << 28;
					break;
				default:
					stream.SkipLastField();
					break;
				}
			}
		}

		public void RaiseChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				Int32Int32_map.RaiseChanged(int32Int32_);
			if ((_changed & (0x01 << 2)) != 0)
				Int32String_map.RaiseChanged(int32String_);
			if ((_changed & (0x01 << 3)) != 0)
				Int32Timestamp_map.RaiseChanged(int32Timestamp_);
			if ((_changed & (0x01 << 4)) != 0)
				Int32Duration_map.RaiseChanged(int32Duration_);
			if ((_changed & (0x01 << 5)) != 0)
				Int32Empty_map.RaiseChanged(int32Empty_);
			if ((_changed & (0x01 << 6)) != 0)
				Int32ItemType_map.RaiseChanged(int32Enum_);
			if ((_changed & (0x01 << 7)) != 0)
				Int32ItemData_map.RaiseChanged(int32ItemData_);
			if ((_changed & (0x01 << 8)) != 0)
				Int64Int64_map.RaiseChanged(int64Int64_);
			if ((_changed & (0x01 << 9)) != 0)
				Int64String_map.RaiseChanged(int64String_);
			if ((_changed & (0x01 << 10)) != 0)
				Int64Timestamp_map.RaiseChanged(int64Timestamp_);
			if ((_changed & (0x01 << 11)) != 0)
				Int64Duration_map.RaiseChanged(int64Duration_);
			if ((_changed & (0x01 << 12)) != 0)
				Int64Empty_map.RaiseChanged(int64Empty_);
			if ((_changed & (0x01 << 13)) != 0)
				Int64ItemType_map.RaiseChanged(int64Enum_);
			if ((_changed & (0x01 << 14)) != 0)
				Int64ItemData_map.RaiseChanged(int64ItemData_);
			if ((_changed & (0x01 << 15)) != 0)
				StringInt32_map.RaiseChanged(stringInt32_);
			if ((_changed & (0x01 << 16)) != 0)
				StringString_map.RaiseChanged(stringString_);
			if ((_changed & (0x01 << 17)) != 0)
				StringTimestamp_map.RaiseChanged(stringTimestamp_);
			if ((_changed & (0x01 << 18)) != 0)
				StringDuration_map.RaiseChanged(stringDuration_);
			if ((_changed & (0x01 << 19)) != 0)
				StringEmpty_map.RaiseChanged(stringEmpty_);
			if ((_changed & (0x01 << 20)) != 0)
				StringItemType_map.RaiseChanged(stringEnum_);
			if ((_changed & (0x01 << 21)) != 0)
				StringItemData_map.RaiseChanged(stringItemData_);
			if ((_changed & (0x01 << 22)) != 0)
				BoolInt32_map.RaiseChanged(boolInt32_);
			if ((_changed & (0x01 << 23)) != 0)
				BoolString_map.RaiseChanged(boolString_);
			if ((_changed & (0x01 << 24)) != 0)
				BoolTimestamp_map.RaiseChanged(boolTimestamp_);
			if ((_changed & (0x01 << 25)) != 0)
				BoolDuration_map.RaiseChanged(boolDuration_);
			if ((_changed & (0x01 << 26)) != 0)
				BoolEmpty_map.RaiseChanged(boolEmpty_);
			if ((_changed & (0x01 << 27)) != 0)
				BoolItemType_map.RaiseChanged(boolEnum_);
			if ((_changed & (0x01 << 28)) != 0)
				BoolItemData_map.RaiseChanged(boolItemData_);
			OnChanged?.Invoke(this, new EventChanged(_changed));
		}

		public void ClearChanged()
		{
			if (_changed == 0)
				return;
			if ((_changed & (0x01 << 1)) != 0)
				Int32Int32_map.ClearChanged(int32Int32_);
			if ((_changed & (0x01 << 2)) != 0)
				Int32String_map.ClearChanged(int32String_);
			if ((_changed & (0x01 << 3)) != 0)
				Int32Timestamp_map.ClearChanged(int32Timestamp_);
			if ((_changed & (0x01 << 4)) != 0)
				Int32Duration_map.ClearChanged(int32Duration_);
			if ((_changed & (0x01 << 5)) != 0)
				Int32Empty_map.ClearChanged(int32Empty_);
			if ((_changed & (0x01 << 6)) != 0)
				Int32ItemType_map.ClearChanged(int32Enum_);
			if ((_changed & (0x01 << 7)) != 0)
				Int32ItemData_map.ClearChanged(int32ItemData_);
			if ((_changed & (0x01 << 8)) != 0)
				Int64Int64_map.ClearChanged(int64Int64_);
			if ((_changed & (0x01 << 9)) != 0)
				Int64String_map.ClearChanged(int64String_);
			if ((_changed & (0x01 << 10)) != 0)
				Int64Timestamp_map.ClearChanged(int64Timestamp_);
			if ((_changed & (0x01 << 11)) != 0)
				Int64Duration_map.ClearChanged(int64Duration_);
			if ((_changed & (0x01 << 12)) != 0)
				Int64Empty_map.ClearChanged(int64Empty_);
			if ((_changed & (0x01 << 13)) != 0)
				Int64ItemType_map.ClearChanged(int64Enum_);
			if ((_changed & (0x01 << 14)) != 0)
				Int64ItemData_map.ClearChanged(int64ItemData_);
			if ((_changed & (0x01 << 15)) != 0)
				StringInt32_map.ClearChanged(stringInt32_);
			if ((_changed & (0x01 << 16)) != 0)
				StringString_map.ClearChanged(stringString_);
			if ((_changed & (0x01 << 17)) != 0)
				StringTimestamp_map.ClearChanged(stringTimestamp_);
			if ((_changed & (0x01 << 18)) != 0)
				StringDuration_map.ClearChanged(stringDuration_);
			if ((_changed & (0x01 << 19)) != 0)
				StringEmpty_map.ClearChanged(stringEmpty_);
			if ((_changed & (0x01 << 20)) != 0)
				StringItemType_map.ClearChanged(stringEnum_);
			if ((_changed & (0x01 << 21)) != 0)
				StringItemData_map.ClearChanged(stringItemData_);
			if ((_changed & (0x01 << 22)) != 0)
				BoolInt32_map.ClearChanged(boolInt32_);
			if ((_changed & (0x01 << 23)) != 0)
				BoolString_map.ClearChanged(boolString_);
			if ((_changed & (0x01 << 24)) != 0)
				BoolTimestamp_map.ClearChanged(boolTimestamp_);
			if ((_changed & (0x01 << 25)) != 0)
				BoolDuration_map.ClearChanged(boolDuration_);
			if ((_changed & (0x01 << 26)) != 0)
				BoolEmpty_map.ClearChanged(boolEmpty_);
			if ((_changed & (0x01 << 27)) != 0)
				BoolItemType_map.ClearChanged(boolEnum_);
			if ((_changed & (0x01 << 28)) != 0)
				BoolItemData_map.ClearChanged(boolItemData_);
			_changed = 0;
		}
	}
}
